### ISSUE TITLE
Redundancy typo in "list.md"

### ISSUE THREAD

**Issue by CalebProvost** [treehouses/treehouses.github.io#102]
The line in github.io/pages/blog/list.md:
 > [treehouses.io in DevOpsDay Jakarta](20180505-devopsdayjkt18.md) 2018 on May 5, 2018 by empeje

should be:
 > [treehouses.io in DevOpsDay Jakarta](20180505-devopsdayjkt18.md) on May 5, 2018 by empeje

**Comment by dogi** [comment]
@CalebProvost good catch, but I think it should more be

 > [treehouses.io in DevOpsDay Jakarta 2018](20180505-devopsdayjkt18.md) on May 5, 2018 by empeje
