### ISSUE TITLE
Command missing from Step 7 (Nextcloud)

### ISSUE THREAD

**Issue by CalebProvost** [treehouses/treehouses.github.io#103]
The command to start the tor service which allows users to access Nextcloud is missing.

>Start up Tor
>As we have run Nextcloud on port 8080, that's the port that we will have to open up with Tor. >While still in the root of treehouses, run treehouses tor add 80 8080, treehouses tor notice on, >then treehouses tor to find the tor address. You should see something like this:

Should be:
>Start up Tor
>As we have run Nextcloud on port 8080, that's the port that we will have to open up with Tor. >While still in the root of treehouses, run treehouses tor add 80 8080, treehouses tor notice on, >treehouses tor (to find the tor address), and then treehouses tor _**start**_. You should see something like this:

**Comment by CalebProvost** [comment]
Also, it might be helpful to add into the segment above
> Now that the container has been created, you can stop and start it with docker stop nextcloud and docker start nextcloud. To view all running and stopped containers, run docker ps -a.

a statement to turn off any other docker containers which might be running.

**Comment by dogi** [comment]
@CalebProvost I also under that impression until @Liew211 corrected me ... no `treehouses tor start` needed (the command kinda degraded to counter `treehouses tor stop`)

**Comment by dogi** [comment]
> Also, it might be helpful to add into the segment above
> 
> > Now that the container has been created, you can stop and start it with docker stop nextcloud and docker start nextcloud. To view all running and stopped containers, run docker ps -a.
> 
> a statement to turn off any other docker containers which might be running.

I like this one can you make a new issue with before after in the context

**Comment by CalebProvost** [comment]
@dogi guess that makes sense. After further investigation into why I was having issues accessing Nextcloud I realized it wasn't because it wasn't started. It because I didnt stop the other containers first and it caused conflicts.
