### ISSUE TITLE
Add stop Docker container clarification for Nextcloud (Step 7)

### ISSUE THREAD

**Issue by CalebProvost** [treehouses/treehouses.github.io#104]
In order to avoid containers from conflicting and causing issues with tor loading Nextcloud, if would be helpful to add a clarification clause to:
> Now that the container has been created, you can stop and start it with `docker stop nextcloud` and `docker start nextcloud`. To view all running and stopped containers, run `docker ps -a`.

Something like:
> Note: use `docker stop <container>` on any running containers other than Nextcloud.

**Comment by ArranHL** [comment]
Looks good, go ahead and create a PR :)

**Comment by CalebProvost** [comment]
@ArranHL I'm awaiting @dogi for clarification as there seems to  be a misunderstanding.
See #107
