### ISSUE TITLE
explain which kind of commands work in treehouses remote

### ISSUE THREAD

**Issue by BindushreeRamakrishna** [treehouses/treehouses.github.io#111]
In Step 1 , section 2: 
No Response from android treehouses remote app when trying to execute commands.
![Screenshot_20190901-213030__01__01](https://user-images.githubusercontent.com/47194274/64134410-56bb7580-cda3-11e9-9c2d-e8fa16763948.jpg)

**Comment by dogi** [comment]
copied from chat"
> treehouses remote is a serial line terminal interface
> so only commands with line output are working
> no vim no top no ping
> anyhow @BindushreeRamakrishna you was looking for the command `treehouses internet`
> which will tell you if your rpi sees the internet

**Comment by dogi** [comment]
@BindushreeRamakrishna the question is where to add above information

**Comment by vmnet8** [comment]
The markdown page content is a little bit confusing, I thought I was supposed to try 'ping' on treehouse remote, but I figured I couldn't do "ctrl+C" on Android.

**Comment by dogi** [comment]
> The markdown page content is a little bit confusing, I thought I was supposed to try 'ping' on treehouse remote, but I figured I couldn't do "ctrl+C" on Android.

bingo
