### ISSUE TITLE
Navigate to track VI's process 

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#112]
On [step 9](https://treehouses.io/#!pages/vi/firststeps.md#Step_9_-_Be_Part_of_the_Team)
Direction tells user to view the process via [ process tracking web](https://treehouses.io/#!pages/vi/trackprogress.md).
https://treehouses.io/#!pages/vi/firststeps.md#Step_9_-_Be_Part_of_the_Team
> NOTE: You can track your progress with the number of pull requests and issues **here**.

However, this fails to link users to [trackprogress.md.](https://treehouses.io/#!pages/vi/trackprogress.md)

**Comment by dogi** [comment]
@phamduchongan93 :)
we know about that `dogi` is hard coded ... if you know a way to know which github user is using http://treehouses.io then step up

look at https://github.com/treehouses/treehouses.github.io/blob/master/pages/vi/trackprogress.md#L24

I am closing this issue ;)
but feel free to reopen if you know a way
