### ISSUE TITLE
Add content for "Introductory Step"

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#114]
I have been using this WSL for a while and see that it has offer a real terminal experience as well as built in git and common editors. As a part of Setting up your environment for window device, this WSL is essential for command tools for developers. Couple command lines will quickly get this WSL running. @ArranHL @dogi @lmmrssa.

**Is it possible that we can add an installation guide for this tool other than putty or git bash?**
Raw Git Hack file I want to add.

[Setting up your environment](https://treehouses.io/#!pages/vi/firststeps.md#Step_1_-_Installing_and_finding_your_Raspberry_Pi)

**Comment by dogi** [comment]
@phamduchongan93 
first we never suggested `putty` anywhere ... please do not mislead us ;)
second `git bash` is doing a fine job on any windows system (vista, xp nt 2000 7 8 8.1 ... and 10)
third `WSL2` is most likely only working on 90% of windows 10's and will cause for some of them a complete reinstall ... which is in itself is kinda unacceptable

also look at our future blog post https://github.com/treehouses/treehouses.github.io/pull/21

generally we want to but we wanted to be very inclusive so we first tackled the easy solution for everybody ... `git bash`

**Comment by phamduchongan93** [comment]
I see. Just a thought. But I agree that git bash probably a solution for everyone. :)

**Comment by dogi** [comment]
@phamduchongan93 now that you are in the right mindset as I mentioned before we want to include WSL2, but right now we still need to publish the blog post, that is why we set this issue on hold for now

**Comment by jamjakpa** [comment]
Generally speaking, wouldn't that be a great Idea to make a step by step video introduction for the 8 steps. Some people get it when they see it visually . I mean there are people they learn better text based and there are people ( we live in a world of Images and Media ) they learn better visually . Just an Idea :)

**Comment by dogi** [comment]
@jamjakpa good idea but since steps change over time wonder how to do best there ...

**Comment by dogi** [comment]
@phamduchongan93 https://treehouses.io/#!./pages/blog/20190808-debianforwindows.md
