### ISSUE TITLE
Unknown public keys in  ~/.ssh/authorized_keys file

### ISSUE THREAD

**Issue by BindushreeRamakrishna** [treehouses/treehouses.github.io#115]
On executing below command, I see few unknown keys under .ssh/authorized_keys file.
sudo treehouses sshkey add "your SSH key"

**Comment by dogi** [comment]
@BindushreeRamakrishna good job was wonder when first aspiring intern will bring this up

this keys are the keys of our support team https://github.com/orgs/treehouses/teams/support/members

they are there by default and can be disabled by https://github.com/treehouses/builder/blob/master/autorunonce#L17 in the `autorunonce` file

anyhow wonder where in the 10 steps we should inform the aspiring virtual interns

**Comment by BindushreeRamakrishna** [comment]
Thanks.
I think, including this in the same step as a "Note" would help.

**Comment by jpadilla9** [comment]
@dogi I might need your help replacing these. I noticed them all in there when I was trying to get my new ssh key to work and deleted them all. oops

**Comment by dogi** [comment]
@jpadilla9 no worries our rpi images are very disposable

**Comment by phamduchongan93** [comment]
@BindushreeRamakrishna Uh-Oh, `treehouses tor add 22` will get you an open port 22, and there are public keys on you pi. Some people can remotely get in your pi :)

**Comment by dogi** [comment]
> @BindushreeRamakrishna Uh-Oh, `treehouses tor add 22` will get you an open port 22, and there are public keys on you pi. Some people can remotely get in your pi :)

@phamduchongan93 ;) some = https://github.com/orgs/treehouses/teams/support/members

also ssh over tor is not so easy ... our treehouses images are kinda already configured ... so @lmmrssa and I are the only people of the support team which in my knowledge successfully did it :)

**Comment by GoogleAgent** [comment]
Hello!!
How can I get Phish my girlfriend email in the UK?
