### ISSUE TITLE
Make image path relative

### ISSUE THREAD

**Issue by lmmrssa** [treehouses/treehouses.github.io#117]
Image path needs to be relative as it does not show up on raw.githack link
![image](https://user-images.githubusercontent.com/2909490/64220812-68f3fb80-ceea-11e9-841f-36f51b9859af.png)

**Comment by CalebProvost** [comment]
The links are already relative:
```
Go to the "Issues" tab and click on "New issue" to create a new issue:

![New Issue](/images/fs6-new-issue.png)

Give it a short title and a decriptive body and you can now submit your issue. If you are explaining a bug or how to replicate an issue, please be as explicit as possible and use pictures as necessary.

![New Issue 2](/images/fs6-issue.png)
```

From what I can tell, they're actually in a different location `USER.github.io/images` instead of `USER.github.io/pages/vi/images`.

So the question I have is:
Do we move the photos to the directory already linked, or change the link to the current directory?

**Comment by dogi** [comment]
@CalebProvost in unix style paths with leading `/` start on the root
a relative path starts for sure without a slash

**Comment by CalebProvost** [comment]
Yup... don't know what I was thinking. Sorry about that.

If that's the case, should we pursue the _move files_ route or _change to relative_ route?
I'm thinking it would make more sense to keep things constant and move the photos as all the vi pages are already sharing the same directory for their images.

**Comment by dogi** [comment]
good questition ... it is part of this issue to find out if the images are on the right place

**Comment by MatthewMarroquin** [comment]
@dogi @lmmrssa I suggest we move the two images to `pages/vi/images` then change to relative paths for these images. Can this be assigned to me?
