### ISSUE TITLE
add flowchart

### ISSUE THREAD

**Issue by MatthewMarroquin** [treehouses/treehouses.github.io#118]
In step 6 "GitHub Issues" there is a missing flowchart diagram. I suggest adding a diagram in place of the "NEED DIAGRAM HERE"  text (see picture below)
![image](https://user-images.githubusercontent.com/44531565/64225234-59939480-ce8f-11e9-9350-9bb146a527a6.png)

here is the flowchart I have drafted:
![image](https://user-images.githubusercontent.com/44531565/64226156-14716180-ce93-11e9-85e7-eb4b625256d2.png)

**Comment by ArranHL** [comment]
Hi matt, I feel the OLE may have served as inspiration for this :) 
![image](https://user-images.githubusercontent.com/47016295/64246874-4ed01280-cf16-11e9-91cf-e5db201f9ce0.png)

100% missing from treehouses! Go ahead and create a PR 👍

**Comment by MatthewMarroquin** [comment]
@ArranHL ahah yes I used the OLE as a reference,    thanks for giving me the green light
