### ISSUE TITLE
edit text in issues

### ISSUE THREAD

**Issue by MatthewMarroquin** [treehouses/treehouses.github.io#119]
Edit the reasons why an issue may be denied. currently the formatting is off where some words are italicized others are not and there is a random line break

![image](https://user-images.githubusercontent.com/44531565/64225559-bfcce700-ce90-11e9-8dcd-affbbb3bd2e1.png)

**Comment by Liew211** [comment]
@Mattmtech Yes, this is supposed to be an unordered list, meaning it is an issue with the Markdown syntax of newline in the document.  Go ahead and work on this!

**Comment by MatthewMarroquin** [comment]
@Liew211 Thank you!!
