### ISSUE TITLE
Wording on Step 6 a little confusing.

### ISSUE THREAD

**Issue by jpadilla9** [treehouses/treehouses.github.io#121]
This is a small issue, but on step 6, it says this- "Therefore, open a command line and open your username.github.io repository on the GitHub user interface. You then need to copy the link provided in the repository.
Then, turn to your command prompt and type your repository URL in the form of git clone https://github.com/EmilyLarkin/EmilyLarkin.github.io.git into the command line. Be sure to use the correct URL to clone your repository (you will obviously type your own username). "

So first we copy the url to clone it, but then it goes on to say "type git clone https://github.com/EmilyLarkin/EmilyLarkin.github.io.git" This is somewhat confusing because it sounds like we need to type just that with our name and the copy we made of the url isn't needed yet. My clone wasn't called this, so if I typed this with my name it wouldn't work. Maybe it should say something like, type git clone and then paste the url you copied. Just an idea to make it a little more clear!

**Comment by lmmrssa** [comment]
@jpadilla9 I understand your confusion there. We usually ask people to fork repository like <username>.github.io but yes you are right everybody does not fork in that format. So we can try to change the working to make it clear. so syntax will be `git clone <repository_url>` and we can put previous code as example so people understand what <repository_url> means.

Does that sound clear enough? Also before working on if you could provide your solution text here that will be helpful.

**Comment by jpadilla9** [comment]
Yes, that sounds good. I would word it this way. "You then need to copy the link provided in the repository.
Then, turn to your command prompt and type git clone <repository _url> (paste from previous step or type in manually) ex. https://github.com/EmilyLarkin/EmilyLarkin.github.io.git.  Be sure to use the correct URL to clone your repository (you will obviously type your own username). "

Does this sound right?

**Comment by dogi** [comment]
@jpadilla9 just checked you have already a `<username>.github.io`
please look at https://treehouses.io/#!pages/vi/faq.md#Q10:_What_do_I_do_if_'%3CYourUserName%3E.github.io'_is_already_in_use%3F

**Comment by Nida8930** [comment]
In addition to what was mentioned above I also found the quoted section to be sort of awkward and confusing. 

> Therefore, open a command line and open your username.github.io repository on the GitHub user interface. You then need to copy the link provided in the repository.

I think it would be more clear and flow better if it were worded...

>Therefore, open your username.github.io repository on the GitHub user interface and copy the link provided by clicking the "Clone or download" button. Then open a command line and...

followed by the changes mentioned in the above comments. This section is also located in step 5 at the time of posting this comment.

**Comment by Nida8930** [comment]
@pattanawadee88 would you like me to work on resolving this issue with the changes discussed in the previous comments?
