### ISSUE TITLE
SSH clarity for Step 7 (Nextcloud).

### ISSUE THREAD

**Issue by CalebProvost** [treehouses/treehouses.github.io#122]
Step 2 walks through how to set up the SSH keys and then step 7 (Nextcloud) requires a fresh image with a rewrite to `autorunonce`. There's no mention on readding the prior made key back into the RPi, yet it requests that the user ssh into the RPi which can prompt an error.

I feel it would be beneficial to add: 

> "If you encounter an SSH error such as 
> ```
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@> > @@@@@@@@@@@@@@@
> @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@> @@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
> Someone could be eavesdropping on you right now (man-in-the-middle attack)!
> It is also possible that a host key has just been changed.
> The fingerprint for the ECDSA key sent by the remote host is
> SHA256:nVgL71cf8dHCqarTM8ld4wVvaAnE+vMEn+bFRbL+EPQ.
> Please contact your system administrator.
> Add correct host key in /home/hipr/.ssh/known_hosts to get rid of this message.
> Offending ECDSA key in /home/hipr/.ssh/known_hosts:1
>   remove with:
>   ssh-keygen -f "/home/hipr/.ssh/known_hosts" -R 192.168.1.189
> ECDSA host key for 192.168.1.189 has changed and you have requested strict checking.
> Host key verification failed.
> ```
> 
> then proceed to run the command `ssh-keygen -f "/home/username/.ssh/known_hosts" -R <local ip-address>`, followed by `sudo treehouses sshkey add "SSH key"` to reinsert your ssh made in [step 2]()."

Thoughts?

**Comment by dogi** [comment]
@CalebProvost look at [FAQ Q11](https://treehouses.io/#!pages/vi/faq.md#https://treehouses.io/pages/vi/#Q11:_What_if_you_encounter_Host_key_verification_fail?)

**Comment by CalebProvost** [comment]
@dogi 
That was my bad. I didn't notice that addition.
Should we place a note to reference that [FAQ](https://treehouses.io/#!pages/vi/faq.md#https://treehouses.io/pages/vi/#Q11:_What_if_you_encounter_Host_key_verification_fail?) if they encounter this error at that point?

If not, issue closed no problem.

**Comment by Liew211** [comment]
@CalebProvost Yes, adding a link to that FAQ will definitely be helpful, go for it 😃
