### ISSUE TITLE
fix link

### ISSUE THREAD

**Issue by MatthewMarroquin** [treehouses/treehouses.github.io#134]
link in picture below goes to "sorry, page you are looking for doesn't exist" error
![image](https://user-images.githubusercontent.com/44531565/64483097-e1d8a900-d1b1-11e9-9912-66f648c139d1.png)

Here is a picture of the error page:
![image](https://user-images.githubusercontent.com/44531565/64483101-f61ca600-d1b1-11e9-930d-8ef5998d2b67.png)

I suggest to edit the link so it goes to the proper page

**Comment by dogi** [comment]
@Mattmtech good catch
