### ISSUE TITLE
Requisites - 3 microSD cards?

### ISSUE THREAD

**Issue by vmnet8** [treehouses/treehouses.github.io#139]
https://treehouses.io/#!./pages/vi/firststeps.md#Pre-Requisites
It doesn't mention why 3 cards are required. My understanding is we need at least one for step 2(installing and configuring pi), maybe need another one for step 7(nextcloud and tor).

**Comment by MatthewMarroquin** [comment]
@vmnet8 good point, I only needed 2SD cards

**Comment by Liew211** [comment]
@vmnet8 While 2 cards may be enough to complete the first steps, it's very useful to have multiple cards in a testing environment to be able to test different images without needing to wait for them to flash.

**Comment by dogi** [comment]
thanks @Liew211
