### ISSUE TITLE
Netcloud-tor: better have official nextloud website and docker image links

### ISSUE THREAD

**Issue by vmnet8** [treehouses/treehouses.github.io#140]
https://treehouses.io/#!./pages/vi/nextcloud-tor.md

netcloud website:
[nextcloud](https://nextcloud.com)

netcloud docker image:
[netcloud docker image](https://hub.docker.com/_/nextcloud/)

**Comment by Liew211** [comment]
You should add these links in the introduction section 👍

**Comment by CalebProvost** [comment]
I agree with @Liew211 
Having the images which demonstrates the results of this step lead to another site (and thereby contradict the results) might lead to some confusion.

**Comment by dogi** [comment]
@Liew211 thanks
