### ISSUE TITLE
step1: add a step to extract the image file after downloading

### ISSUE THREAD

**Issue by vmnet8** [treehouses/treehouses.github.io#141]
I remembered I extracted the gz file before flashing the image to sd card.
https://treehouses.io/#!./pages/vi/pi-setup.md

**Comment by Liew211** [comment]
@vmnet8 this is not needed, balenaEtcher can flash the image directly from the .gz file.

**Comment by vmnet8** [comment]
> @vmnet8 this is not needed, balenaEtcher can flash the image directly from the .gz file.

Thank, good to know

**Comment by dogi** [comment]
@vmnet8 also as root `zcat treehouse-108.img.gz > /dev/sdb` works like a charm

(I mean much better then `dd`)
