### ISSUE TITLE
punctuation and markdown errors in github-issues.md

### ISSUE THREAD

**Issue by CalebProvost** [treehouses/treehouses.github.io#146]
**Punctuation Error:** [Create a New Branch](https://treehouses.io/#!./pages/vi/github-issues.md#Create_a_New_Branch)

>To create a new branch, go to your github repo and create it using the same steps as you can see[here](https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository) (do not delete your branch)

There should be a space between `see` and [`here`](https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository)

**Markdown Errors:** [Notes](https://treehouses.io/#!./pages/vi/github-issues.md#Preview_Changes_Locally)

Linked above is an example of a markdown error where a note is not being rendered correctly due to the markdown style used.

**Comment by dogi** [comment]
@CalebProvost :D

**Comment by XavierElon** [comment]
I fixed this issue and sent a PR
