### ISSUE TITLE
Text alignment treehouses chat

### ISSUE THREAD

**Issue by saraive16** [treehouses/treehouses.github.io#147]
**Problem**
There is an extra space in front the word "Gitter" in the treehouses/chat page causes a misalignment

**Steps to reproduce the problem**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/53923848/64670126-d3d89180-d418-11e9-894e-5566b5bfdf55.png)

**Proposed solution**
Remove the extra space in front the word "Gitter" in the treehouses/chat page

**Comment by ArranHL** [comment]
That some attention detail there @saraive16 !
Approved for PR

**Comment by Liew211** [comment]
@saraive16 @ArranHL This is actually not an issue, if you scroll through the page you'll notice that the currently displayed section will become bold and indented.
