### ISSUE TITLE
Adding Tip to getting treehouse image

### ISSUE THREAD

**Issue by saraive16** [treehouses/treehouses.github.io#149]
**Problem**
Need to add a comment that states you must be using Firefox to get the latest treehouse image because if your using Google is downloads as a .crdownload file.

**Steps to reproduce the problem**
Download any treehouse image from the site. 

**Screenshots**
![image](https://user-images.githubusercontent.com/53923848/64670580-80ffd980-d41a-11e9-984c-77fd8bd55d88.png)

**Proposed solution**
Add a comment that you need to be in FIrefox to get the correct download to make it easier to prevent a problem from occurring.

**Comment by Liew211** [comment]
@dogi Thoughts?  Don't think I've had this happen to me before

**Comment by CalebProvost** [comment]
@saraive16 @Liew211 
The `.crdownload` extension is a temporary extension which chrome uses to indicate if the download is complete or not (among other things). In chrome, if the download finishes without error then you shouldn't see the `.crdownload` extension on the file. This means it's indifferent on what browser type you use.

**Comment by dogi** [comment]
@saraive16 thanks
but I would say a non-issue ;)
