### ISSUE TITLE
Add description of blogs

### ISSUE THREAD

**Issue by Liew211** [treehouses/treehouses.github.io#154]
On the blogs page before the list of blogposts and after the header, there should be some kind of introduction paragraph describing the purpose of the blogs, i.e. "these are blog posts written by virtual interns on projects they have worked on at treehouses" etc etc

**Comment by Liew211** [comment]
@Kid243 @irisb1701 @ArranHL any of you up for this?

**Comment by phamduchongan93** [comment]
@Liew211 I've been writing md file for this. So, yes

**Comment by Liew211** [comment]
@phamduchongan93 in that case, whenever you decide to work on an issue assign it to yourself, or ask to be assigned so that other people don’t work on it too :)

**Comment by phamduchongan93** [comment]
@Liew211 my bad, should have noticed you guys :)

**Comment by phamduchongan93** [comment]
@/all Need your input about the blog outline before I go off track.
 https://raw.githack.com/treehouses/treehouses.github.io/blog_outline/#!pages/blog/list.md :)

**Comment by Liew211** [comment]
@phamduchongan93 I think just a short paragraph is sufficient, we want the blogs to be easily accessible and any more than a description isn't necessary.
