### ISSUE TITLE
Ask interns to star repo before joining

### ISSUE THREAD

**Issue by Liew211** [treehouses/treehouses.github.io#156]
This can probably be done in the intern orientation document, before listing out all of treehouses projects.

**Comment by XavierElon** [comment]
Do you mean for them to fork the treehouses repository?

**Comment by Liew211** [comment]
![image](https://user-images.githubusercontent.com/43839884/65056168-678cef00-d93e-11e9-899c-2bef24f927b6.png)
@xavierh93

**Comment by vmnet8** [comment]
Good idea.

**Comment by obulaworld** [comment]
hi @Liew211, trying to understand fully, what file is meant to be edited and with what copy?
