### ISSUE TITLE
Need to add a password to RPi before you can SSH into it

### ISSUE THREAD

**Issue by XavierElon** [treehouses/treehouses.github.io#157]
While completing the "First Steps", when I was SSHing into my Raspberry Pi it asked me for a password but I had never created one and the default password "raspberry" did not work. We should add another step to "Using treehouses remote" that explains to new interns that they can create a new password for the Raspberry Pi in the RPi terminal via the password command. This is what I had to do in order to connect to mine via SSH. I also think it should be mentioned that the default password might be "raspberry"

**Comment by CalebProvost** [comment]
Hm... There's a lot to unravel here. DM sent for more details.

**Comment by dogi** [comment]
@xavierh93 treehouses images are working there the same way as raspbian
