### ISSUE TITLE
There is image below "Delete the Branch" on github-issues.md

### ISSUE THREAD

**Issue by XavierElon** [treehouses/treehouses.github.io#159]
At the very end of the text it mentions a picture but there is not picture to be found. I recommend that we add one or remove the text that mentions it.

> Delete the branch from your remote repository.
> After your pull request has been approved and merged by OLE staff, you might want to delete the branch that is associated with your pull request. It can keep your local and remote (yourUserName.github.io on GitHub) repository away from a mess of defunct branches. To delete the defunct branch in your remote repository, you can click the "Delete branch" button in your pull request *(see the picture below).*

**Comment by CalebProvost** [comment]
Good catch. Go ahead and create a PR.
