### ISSUE TITLE
Add sudo option to root part of step 7

### ISSUE THREAD

**Issue by XavierElon** [treehouses/treehouses.github.io#162]
A second option should be given when _Start up Nextcloud_ where you can just sudo the commands instead of logging in as root. I had trouble logging into root and eventually just ran the commands as sudo and everything worked fine.

**Comment by kgsexcastelocash** [comment]
Hello

**Comment by dogi** [comment]
understand @xavierh93 but you should be able to login directly as root with sshkeys ;)

**Comment by XavierElon** [comment]
@dogi does that mean the passphrase is the sshkey?

**Comment by dogi** [comment]
@xavierh93 you would have had this problem if you was able to use sshkey the `root` way ;) ... normal 10 steps do not require `sudo` in the case you used it

**Comment by CalebProvost** [comment]
> @dogi does that mean the passphrase is the sshkey?

Kind of. [Give this a read](https://www.hostinger.com/tutorials/ssh-tutorial-how-does-ssh-work)
