### ISSUE TITLE
how to my own github 

### ISSUE THREAD

**Issue by amckiss0** [treehouses/treehouses.github.io#165]
I have make my own github because all the website I don,t have my image from my introduction or contract I have stuck on getting back before miss out the lessons I can't understand any type of websites

**Comment by pattanawadee88** [comment]
I don't quite understand what you are trying to say.

**Comment by CalebProvost** [comment]
The answer to your question can be resolved by following [the Answer to Question 10 of the FAQs](https://treehouses.io/#!pages/vi/faq.md#Q10:_What_do_I_do_if_'%3CYourUserName%3E.github.io'_is_already_in_use?).
