### ISSUE TITLE
add how to review PR github.io into orientation.md

### ISSUE THREAD

**Issue by dogi** [treehouses/treehouses.github.io#182]

**Comment by dogi** [comment]
example review https://github.com/treehouses/treehouses.github.io/pull/180

**Comment by vmnet8** [comment]
https://github.com/treehouses/treehouses.github.io/blob/master/pages/vi/orientation.md
orientation.md has already describled the PR review, are we supposed to give more details and examples to it?

**Comment by kjong** [comment]
Is this issue still relevant?
