### ISSUE TITLE
treehouses.io/#!index.md: Home page - needs more information

### ISSUE THREAD

**Issue by sonAndrew** [treehouses/treehouses.github.io#193]
### * Home page - needs more information

---

When arriving at the **Home page** on treehouses.io, you are welcomed with a large "Welcome!" and some text. This seems a little **ineffective** from a usability standpoint because:

* the text is small
* text is too close together
* there is no other information 
* no visual cues about what people are doing on the page

---

### This page should have a section about:

* The **MDwiki**
* The way we **Communicate**
* The **Virtual Intern Program**
* **Photos** and **visual cues**
* The **Open Learning Exchange**
* The **leaders** of treehouses.io 
* Where to **connect** with Open Learning Exchange

And maybe any **other information** that people may need.

**Comment by dogi** [comment]
@sonAndrew good point
maybe this picture works
![image](https://user-images.githubusercontent.com/13684059/66092041-43ddc180-e558-11e9-93b5-f4d074821fcd.png)

**Comment by pattanawadee88** [comment]
you can start working on it!

**Comment by sonAndrew** [comment]
Hey @dogi are you able to host that image somewhere? Also, do you have other images?
