### ISSUE TITLE
ssh remote host identification when installing new image

### ISSUE THREAD

**Issue by XavierElon** [treehouses/treehouses.github.io#197]
Anytime I install a new treehouses image and I try to SSH into the raspberry pi I get the following error: 
`@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.`

We need to add an FAQ to the wiki on how to fix this

**Comment by sonAndrew** [comment]
Hey this might help -> [Click This - SSH - "REMOTE HOST IDENTIFICATION HAS CHANGED"](https://support.rackspace.com/how-to/ssh-remote-host-identification-has-changed/)
