### ISSUE TITLE
Former members page does not exist

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/treehouses.github.io#200]
When going to the **members page**, at the bottom of the page, it says "To view the list of former interns, go to former members page". However, when clicking the link, the page displays a **"Sorry, the page you are looking for doesn't exist"** message. 
On inspecting the raw source of the page:

`To view the list of former interns, go to [former members page](retiredinterns.md).`

The file **retiredinterns.md** is not a file in the repository treehouses.github.io, which gives the "page not found" error.

**Comment by sonAndrew** [comment]
### Yeah, this does seem like a problem. I checked pretty much all of the interns and these are the ones that don't have a page:

#### Active Members

1. Liew211 - https://treehouses.io/#!./pages/vi/profiles/Liew211.md
2. Kid243 - https://treehouses.io/#!./pages/vi/profiles/Kid243.md
3. Chiragawale - https://treehouses.io/#!./pages/vi/profiles/chiragawale.md
4. hiroTochigi - https://treehouses.io/#!./pages/vi/profiles/hiroTochigi.md
5. Irisb1701 - https://treehouses.io/#!./pages/vi/profiles/irisb1701.md
6. Lillyxxx - https://treehouses.io/#!./pages/vi/profiles/lillyxxx.md

#### Former Members

1. jeevast - https://treehouses.io/#!./pages/vi/profiles/jeevast.md
2. samuelchen1213 - https://treehouses.io/#!./pages/vi/profiles/samuelchen1213.md

#### Former Members - Page

**Comment by sriharivishnu** [comment]
Interestingly, [The OLE Site](https://open-learning-exchange.github.io/#!pages/vi/vi-team.md)'s former members page works. I'm not sure why that's the case, but if anyone could offer insight, that would be great!

**Comment by dogi** [comment]
;) treehouses.io is kinda 7 weeks old ... plz fix

**Comment by sriharivishnu** [comment]
@dogi Ok I will work on it
