### ISSUE TITLE
Step 5 - some Hyperlinks cannot work properly

### ISSUE THREAD

**Issue by jingtu87** [treehouses/treehouses.github.io#201]
In the STEP 5 - ["Git Repositories" website](https://treehouses.io/#!./pages/vi/gitrepositories.md). The ***Start here*** part, the hyperlink ***"Clone with HTTPS or Clone with SSH?"*** and ***"Explanation About Repositories and Syncing Process"*** cannot jump to the right place.

**Comment by AninditaBasu** [comment]
May I take up this issue? I submitted a PR: https://github.com/treehouses/treehouses.github.io/pull/205

**Comment by jingtu87** [comment]
Sure. No Problem.

Anindita Basu <notifications@github.com> 于2019年10月10日周四 上午3:57写道：

**Comment by jingtu87** [comment]
> 
> 
> May I take up this issue? I submitted a PR: #205

Hi AninditaBasu,

I am so sorry. I wonder if I can fix the issue myself because I need to complete the STEP.6 for the new intern tutorial. So sorry for that.

**Comment by AninditaBasu** [comment]
Not a problem
