### ISSUE TITLE
"Page not found" link to home goes to different website

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/treehouses.github.io#203]
When clicking on the **"Go home"** link in the page not found section,

<img width="623" alt="Screen Shot 2019-10-09 at 9 43 41 PM" src="https://user-images.githubusercontent.com/37857112/66532621-03dd8800-eade-11e9-9d4b-ae60c1dce530.png">

 instead of going to the home page of treehouses.io, it goes to this website instead.
<img width="1404" alt="Screen Shot 2019-10-09 at 9 44 01 PM" src="https://user-images.githubusercontent.com/37857112/66532609-fa542000-eadd-11e9-9465-b2a942170dc7.png">

I am not sure if this was the intended effect, but I'd recommend linking it back to the treehouses.io home page instead of the OLE website one.

**Comment by pattanawadee88** [comment]
you can start working on this :)
