### ISSUE TITLE
add vim links/videos

### ISSUE THREAD

**Issue by sonAndrew** [treehouses/treehouses.github.io#207]
We should probably add a Vim Tutorial inside one of the steps or even inside the blog section. This can give interns a little more understanding of working inside a text editor if they have not worked with one yet.

**Comment by CalebProvost** [comment]
True. It does appear that Vim is listed as used software, yet no reference-able material is noted anywhere for how to familiarize one's self with it. A simple note with a link to external source should do fine, or even just adding the sentence and link inline in the start-up page would do too.

Will mark ready when a proposed and appropriate location is suggested.

**Comment by dogi** [comment]
hmm I am not convinced we (treehouses.io) need whole tutorial
there are already good tutorials in the internet

adding a link to some good links and/or videos should be enough

**Comment by sonAndrew** [comment]
Hey @dogi @CalebProvost where do you guys want me to place the links and videos?

**Comment by CalebProvost** [comment]
> Hey @dogi @CalebProvost where do you guys want me to place the links and videos?

It's first referenced [here](https://treehouses.io/#!pages/vi/firststeps.md#The_Steps). Other than that, if there's any other location you would recommend, we'll evaluate it.
