### ISSUE TITLE
Terminal Tutorial 

### ISSUE THREAD

**Issue by sonAndrew** [treehouses/treehouses.github.io#208]
We should add a terminal tutorial to one of the steps or to the blog section to introduce interns to the command line if they have not already worked with it other than the command provided through the steps.

**Comment by CalebProvost** [comment]
@sonAndrew 
As much as I agree that this would be helpful learning material, I also feel that there is a minimum set requirement for being apart of the internship. One of which is programming and working through the terminal interface. 

Closing issue.
