### ISSUE TITLE
Clarify Raspberry Pi RAM requirements

### ISSUE THREAD

**Issue by kjong** [treehouses/treehouses.github.io#239]
## Issue
![Screenshot 2019-10-22 16 48 34](https://user-images.githubusercontent.com/36876018/67344110-0e3f4f00-f4ec-11e9-8d93-f261a3b20c1f.png)

Under "Pre-Requisites -> Hardware requirement", RAM requirements are not stated.

## Proposed Solution
State that any RAM amount is fine to remove confusion when purchasing Raspberry Pis.

**Comment by dogi** [comment]
and more is better :P
