### ISSUE TITLE
Fix embedded Youtube video thumbnail on Git Repositories page

### ISSUE THREAD

**Issue by kjong** [treehouses/treehouses.github.io#253]
* Embedded video currently looks like this:

![Screenshot 2019-10-28 03 45 00](https://user-images.githubusercontent.com/36876018/67672553-68e60a00-f935-11e9-9f92-104989538759.png)

* Fix markdown to correctly display video thumbnail.

**Comment by CalebProvost** [comment]
I'm not sure if @dogi wants it to have an embedded video, or to link to the video.
My guess would be the latter.

Awaiting his input.

**Comment by dogi** [comment]
sure we can always look at the output ;)

**Comment by kjong** [comment]
Embedded was the wrong choice of word. I was primarily looking to fix the broken thumbnail, not actually embed the video.
