### ISSUE TITLE
Step 2 - Add ssh key to the Raspberry Pi - sshkey passphrase

### ISSUE THREAD

**Issue by Nida8930** [treehouses/treehouses.github.io#260]
### Problem
The final paragraph of the add ssh key to the Raspberry Pi section mentions that after adding your public ssh key the password to log into ssh into the pi will be set to the passphrase created when generating the ssh key. After following the steps in this section closely the password was still set to the default "raspberry"

### Steps to reproduce the problem
N/A

### Screenshots
![Screen Shot 2019-11-01 at 11 41 32 PM](https://user-images.githubusercontent.com/49969541/68066153-43744a00-fd01-11e9-8079-215a8892fdac.png)

### Proposed solution
Inform users that the password will become the ssh key passphrase only after rebooting the pi.

**Comment by dogi** [comment]
@Nida8930 this not right
