### ISSUE TITLE
Step 2 typo

### ISSUE THREAD

**Issue by Nida8930** [treehouses/treehouses.github.io#262]
### Problem
The note in the Create your SSH key section of step 2 contains a typo. I think there is an **and** missing from the second sentence following the word passphrase.
>NOTE: With cat ~/.ssh/id_rsa* you can check your SSH key pair. Both parts (private and public) of your recently created SSH key should show up. Please be sure that your (private) key is protected by a passphrase has been created on your computer and not on the Raspberry Pi.

### Steps to reproduce the problem
N/A

### Screenshots
![Screen Shot 2019-11-03 at 8 48 51 AM](https://user-images.githubusercontent.com/49969541/68087044-ae17a980-fe17-11e9-9392-14f6537f6cf7.png)

### Proposed solution
The second sentence could be stated more clearly
>Please be sure that your (private) key is protected by a passphrase and has been created on your computer and not on the Raspberry Pi.

**Comment by pattanawadee88** [comment]
I believe it is not really a problem. Adding an "and " would not be necessary.

**Comment by CalebProvost** [comment]
The grammar could be worked on a bit. But I would try to stay away from too many "and"s so close to each other:

> Please be sure that your (private) key is protected by a passphrase and has been created on your computer; not on the Raspberry Pi.

**Comment by Nida8930** [comment]
@CalebProvost Should I go ahead and begin working on this issue?

**Comment by CalebProvost** [comment]
Yup. Go for it.
