### ISSUE TITLE
Step 5 unclear writing.

### ISSUE THREAD

**Issue by Nida8930** [treehouses/treehouses.github.io#263]
### Problem
In the Repositories and the syncing process section of step 5 there is a group of texts that reads

>For example, this link explains how to sync a fork with the correct upstream repo, because as you renamed your repository, it does not automatically assume that treehouses.github.io is the source. Instead, it assumes that username.github.io This means that when you do git diff and git status, it only looks at your username.github.io. You will therefore need to use git fetch upstream, git checkout master, and git merge upstream/master to correctly sync to treehouses.github.io as we will see below.

The second sentence seems incomplete. I seems to be saying that username.github.io is assumed to be the source.

### Steps to reproduce the problem
N/A

### Proposed solution
>For example, this link explains how to sync a fork with the correct upstream repo, because as you renamed your repository, it does not automatically assume that treehouses.github.io is the source. Instead, it assumes that username.github.io is the source. This means that when you do git diff and git status, it only looks at your username.github.io. You will therefore need to use git fetch upstream, git checkout master, and git merge upstream/master to correctly sync to treehouses.github.io as we will see below.

**Comment by XavierElon** [comment]
You are correct. If you want to make a pull request for this issue you can
