### ISSUE TITLE
Deleting a branch clarification

### ISSUE THREAD

**Issue by Nida8930** [treehouses/treehouses.github.io#269]
### Problem
I think more clarification in the Delete the Branch section of the GitHub Issues page. In this section it says to delete the branch by clicking the "Delete branch" button in the pull request. I think there could be added instructions detailing how to locate an already closed pull request to delete the branch.

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Adding written instruction to navigate to the "Pull requests" tab on treehouses.treehouses.github.io page and alter the text in the search bar to show closed pull requests.

**Comment by john-dunbar** [comment]
@Nida8930 I totally agree. I got a little lost at that step. Thanks for looking into this!

**Comment by sravya71** [comment]
@Nida8930 I agree , this can provide clear instructions.

**Comment by surferjreb** [comment]
@Nida8930 I also partly agree, but there are less expensive options.  The **micro SD** memory is a little bit of over kill.  If you are starting from scratch.  It will give you a good start, but you are going to be flashing that one card a lot.

**Comment by LordJashin32** [comment]
"and alter the text in the search bar to show closed pull requests.". What do you mean by this? Can't you just click [here](https://i.imgur.com/niqQXAf.png), and pull up the closed PR's? Then you can type in your username to pull up all your PR's. Perhaps an image would suffice to show how.

**Comment by evoong** [comment]
I too had a the same problem, this solution would be helpful

**Comment by ComputerOnFire** [comment]
This would be good to help new interns, either an image or an explanation showing how to see closed pull requests.

**Comment by jayala-29** [comment]
Thank you for adding this, definitely would make the process less confusing to perform.

**Comment by saurabh-mish** [comment]
This would be very helpful.

**Comment by saurabh-mish** [comment]
@Nida8930 @dun08015 @sravya71 @LordJashin32 @Evoong @ComputerOnFire @jayala-29 The delete branch part of the page has been updated. Can you guys check it out and see if its clearer ?

**Comment by sydneyaldo** [comment]
@saura8h I don't see the proposed solution up in the page yet, could you please clarify the changes made?

**Comment by saurabh-mish** [comment]
@sydneyaldo I had submitted a pull request in which the instructions for deleting a branch were made more clear. This is in step 6 - Github Issues (towards the bottom of the page). 

Earlier the instructions were different from whats there right now. My earlier post was to see if the instruction are clearer at this point.

**Comment by sydneyaldo** [comment]
@saura8h Oh right, the pull request was not linked to the issue. Thanks for the clarification!

**Comment by sarahrams** [comment]
Exactly! The instruction would be helpful. I had to search for it by my own on Google.

**Comment by rohansuri17** [comment]
I think this would be really helpful too! If I hadn't worked with github before I would've struggled to figure this out

**Comment by fankaiyuan** [comment]
Adding this solution would be helpful for deleting a branch that its linked pull request is merged.
