### ISSUE TITLE
Add Section on Code Documentation

### ISSUE THREAD

**Issue by tmrajper9223** [treehouses/treehouses.github.io#276]
### Problem
> The guide for git is great, but adding a section on proper documentation
> on code will be beneficial and enforce good practices early on.

### Steps to reproduce the problem
N/A

### Screenshots
N/A.

### Proposed solution
> Create a separate page for proper [documentation](https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/). The length in the link provided can be included but the page could be more short and concise.

**Comment by pattanawadee88** [comment]
where do you want to add this document?

**Comment by tmrajper9223** [comment]
@pattanawadee88 I would say the link on Step 3, [Github and Markdown](https://treehouses.io/#!./pages/vi/githubandmarkdown.md). Right before the "Open a Pull Request" header. A small paragraph explaining the importance of documentation and a link to a more in depth reference.

**Comment by pattanawadee88** [comment]
I'm not sure that we would want that. I would ask @dogi about this. :)

**Comment by dogi** [comment]
@trajper hmmm ... issue is a good start, but so far still a little bit vague ...
what about you get more concrete?
I mean here in this issue before we give it a go

**Comment by tmrajper9223** [comment]
@dogi I guess what I am trying to suggest is that the pull request should be as descriptive as possible in the description. For example, when making a pull request, in the description, aside from saying what exactly the issue is, the pull request should provide a thorough explanation on the solution to the issue.  This may help the process of helping whoever is reviewing the request easier. Maybe my initial thought on adding documentation may be a bit to general.

**Comment by pattanawadee88** [comment]
I believe we already fix this issue by adding PR template for virtual interns to follow. 
You could look it up here: https://github.com/treehouses/treehouses.github.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md
