### ISSUE TITLE
Update Docker install instructions

### ISSUE THREAD

**Issue by john-dunbar** [treehouses/treehouses.github.io#286]
### Problem:
In [dockertutorial.md](https://treehouses.io/#!./pages/vi/dockertutorial.md) there are instructions for installing "Docker Toolbox" for Windows with a link to the [Docker website](https://docs.docker.com/toolbox/toolbox_install_windows/). 

The Docker website states that Docker Toolbox is meant for "older Mac and Windows systems" and they "recommend updating to the newer applications, if possible".  The "newer applications" they are referring to are Docker Desktop for Windows or Docker Desktop for Mac.

The system requirements for Docker Desktop for Windows are 64 bit Windows 10 Pro. 

I can see these requirements as a limiting factor and a valid reason to continue to use Docker Toolbox. 

However, it is a bit confusing to see the official Docker website recommending me to download a different tool than the one proposed by dockertutorial.md.

### Steps to reproduce the problem:
N/A

### Screenshots:
N/A

### Proposed solution
I recommend that a note be added to dockertutorial.md to acknowledge that we are aware of the newer version but recommend continuing to use Docker Toolbox for those with older systems.

I also suggest adding a new link and separate instructions for Docker Desktop for Windows for those with newer computers.

**Comment by jamjakpa** [comment]
hi, i stumbled on that too, i was a little bit confused. And I am using Windows 10 as well.

**Comment by sravya71** [comment]
Hi,

To Install Docker on the Windows Version , Windows 10 Pro Operating System is required. One of the alternative way to install docker on other Windows OS version, is by installing docker in the virtual box and porting it to Windows Host.

We can specify that Windows 10 Pro, is required in the installation page . Secondly, Also specify of the alternative ways, For example say By installing Virtual Box. 
https://docs.docker.com/toolbox/toolbox_install_windows/

Thanks,
Sravya.
