### ISSUE TITLE
add an other optional to the requirements 

### ISSUE THREAD

**Issue by dogi** [treehouses/treehouses.github.io#289]
please add as 10th position
rpi serial cable https://www.amazon.com/s?k=raspberry+pi+serial+cable

**Comment by jamjakpa** [comment]
> please add as 10th position
> rpi serial cable https://www.amazon.com/s?k=raspberry+pi+serial+cable

@dogi , I fixed It , but there is weird problem, when I create the raw.githack link and go on that, raw.githack link , it shows an error .

![image](https://user-images.githubusercontent.com/44546990/70841929-67807c00-1dd3-11ea-9685-03e2c0a75ce4.png)
