### ISSUE TITLE
multiple links fail on the treehouses.io

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#294]
### Problem
Dead link in pre-requisites section (part of step0 - introductory step)

Check lists for the link:
- [x] Real Time Clock
- [x] Raspberry pi 
- [x] Raspberry pi camera
- [x] Raspberry Pi Night Vision Camera
- [x] Generic Raspberry Pi 5 Megapixel Camera

### Steps to reproduce the problem
- Clicking the links

### Screenshots
- will be forwarded to 404.md error page

### Proposed solution
- Locate the missing files on the treehouses.github.io repo.

**Comment by surferjreb** [comment]
Hi, i'm new around here, but I took a look at the links in the code and it appears they are good links.  Refering to `firststeps.md` where I found the link locations.  They would not open from the page but they did go to pages when placed in the web browser.  
**Solution**:  If you remove the quotation marks from the hyperlink the links start working.

**Comment by phamduchongan93** [comment]
@surferjreb good work, James. Can you create a **PR** and add the **raw git hack** link so that we can see if it resolves the issue?

**Comment by surferjreb** [comment]
Yah, no problem.  I'm currently at work, but I can have done this evening and submit the **PR** and include the **raw git hack** link.

**Comment by surferjreb** [comment]
@phamduchongan93 I fixed the hyperlink. **PR** #298.

**Comment by sravya71** [comment]
@phamduchongan93 I have seen this issue as well. Removing Hyperlinks can resolve this issue.
