### ISSUE TITLE
Step 2 Typo Error in SSH Tutorial 

### ISSUE THREAD

**Issue by jamjakpa** [treehouses/treehouses.github.io#295]
### Problem
While I was working on Step 2 SSH Tutorial, the section that says Add ssh key to the Raspberry Pi .  Now , on in this step : 

Now you can add the public key to run: sudo treehouses sshkey add "your SSH key" (copy-paste your SSH key in between the quotes) or just sudo <code>treehouse</code> sshkey addgithubuser <yourgithubusername>. I was getting an error. Then I finally found out what causes the error it was a  TYPO ERROR <code>treehouse</code> is missing the letter <strong>s</strong> at the end of the word <code>treehouse</code> see attached error 

### Steps to reproduce the problem
NA

### Screenshots
![typo_error](https://user-images.githubusercontent.com/44546990/70335627-446f2e80-180d-11ea-9af4-c1bee52aa4be.png)

### Proposed solution
Solution : Just add the s at the end so it should look like this :
<strong><code>treehouses</code><strong/>

**Comment by sravya71** [comment]
Defintely agree. When we try sudo treehouse sshkey. It gives an error. This typo need to be fixed.
