### ISSUE TITLE
Add Instructions to Install Docker through Virtual Box

### ISSUE THREAD

**Issue by sravya71** [treehouses/treehouses.github.io#296]
### Problem
When the OS requirements of the Host such as Windows 10 Home etc., Cannot Install Docker.

### Steps to reproduce the problem
N/A 

### Screenshots
N/A

### Proposed solution
Add Instructions to Install Docker through Virtual Box , specifying an alternative way for Interns to download docker.
[Install Docker through Virtual Box](https://wiki.cyverse.org/wiki/display/HDFDE/Installing+VirtualBox,+Ubuntu,+and+Docker)

[Install Docker through Boot2Docker ](https://www.ibm.com/developerworks/community/blogs/jfp/entry/running_ipython_notebooks_in_a_docker_container_on_windows?lang=en)

 [Install Docker through Boot2Docker]  (https://docs.docker.com/machine/drivers/virtualbox/)

**Comment by jamjakpa** [comment]
Hi , I have OS  <strong>Windows 10 Home</strong>
and installed <code>docker toolbox</code>  https://github.com/docker/toolbox/releases

**Comment by john-dunbar** [comment]
I believe @jamjakpa is right. Docker Toolbox should work for Windows 10 Home. 

Maybe a solution could be to make a change to [dockertutorial.md](https://treehouses.io/#!./pages/vi/dockertutorial.md) to make that more clear.

**Comment by CalebProvost** [comment]
@sravya71 
Having options are always nice. Keep it short as it's not necessary for us to have it on our desktop's.
Maybe just reference links to it.

**Comment by jayala-29** [comment]
Mac OS users can also use "brew install docker docker-machine" with Homebrew
