### ISSUE TITLE
Add an Optional Raspberry Pi Hardware kit Meeting the Hardware Requirements

### ISSUE THREAD

**Issue by sravya71** [treehouses/treehouses.github.io#300]
### Problem
To avoid Confusion in the initial stages of understanding the hardware requirements and give a direction to interns. Please,Add a Optional Hardware kit that matches the requirements.

### Steps to reproduce the problem
N/A 

### Screenshots
N/A 

### Proposed solution
A link to the [Sample Raspberry Kit](https://www.amazon.com/CanaKit-Raspberry-4GB-Starter-MAX/dp/B07XPHWPRB/ref=sr_1_2_sspa?keywords=raspberry+pi+4&qid=1575733651&s=toys-and-games&sr=1-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyVk5BTzhFU0cxVTUyJmVuY3J5cHRlZElkPUEwODk1NDQ5OFdSMVlSMDlRTVhUJmVuY3J5cHRlZEFkSWQ9QTAyNTMyNjAyNVE1UU1DTk43Wk1XJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==)  meeting the hardware requirements would omit confusion in the initial stages.

**Comment by jamjakpa** [comment]
Nice ! I think also as an alternative you can use a Raspberry Pi 3 B+

**Comment by surferjreb** [comment]
I started the steps using my **Pi 3 B+**.  There are however less expensive options on amazon for purchasing the **Pi 4 b (4GB)**.  You still will need to get multiple micro SD cards to flash different images, unless you want to keep flashing the same card over and over.

**Comment by pattanawadee88** [comment]
I think the kit is not really necessary. But I would suggest you make a table to separate options and requirements. 

Requirement |Options  
---|---
1.|1.
