### ISSUE TITLE
Step 7, Alternative Command Fix!

### ISSUE THREAD

**Issue by sravya71** [treehouses/treehouses.github.io#301]
### Problem
While doing step 7, the command ssh root@[ipaddress] prompts you to a password, Instead we can also try ssh pi@[ipaddress] and that works as well.

### Steps to reproduce the problem
N/A 

### Screenshots
![image](https://user-images.githubusercontent.com/54302388/70382580-4f13eb80-1913-11ea-9591-3b5b81a83a01.png)

### Proposed solution
Include ssh pi@[ip address] as well.

**Comment by surferjreb** [comment]
I agree that there could be an additional comment to instruct the user on using the `ssh pi@[IP address]` command and then log into **root** after using the `sudo -s` command.

**Comment by pattanawadee88** [comment]
You could do it but we normally do ssh root@pi :)
So you can add `ssh pi@[IP address]` and don't forget to add `sudo -s` command

**Comment by CalebProvost** [comment]
> You could do it but we normally do ssh root@pi :)
> So you can add `ssh pi@[IP address]` and don't forget to add `sudo -s` command

True, but for new members whose keys are yet to be added to images, it's good to know.

@sravya71, I've assigned you to this.

**Comment by sravya71** [comment]
@CalebProvost Yes, I have completed this issue.
