### ISSUE TITLE
Errors in Introductory Steps

### ISSUE THREAD

**Issue by sravya71** [treehouses/treehouses.github.io#302]
### Problem
The Hyperlinks for optional with numbers 8,9,10 are not displayed.

### Steps to reproduce the problem
N/A 

### Screenshots
![image](https://user-images.githubusercontent.com/54302388/70383277-eaab5900-191f-11ea-9904-196e3a1a10fa.png)

### Proposed solution
Remove the hyperlinks which are not working/ Insert new hyperlinks depending on the requirement of the hardware.

**Comment by surferjreb** [comment]
Hello, I'm James.  This was brought up by issue #294 and a pull request is waiting final approval **PR** #298.

**Comment by phamduchongan93** [comment]
@surferjreb that's right. I'm going to close this issue, but feel free to re-open if there is something new brought up.

**Comment by phamduchongan93** [comment]
@surferjreb that's right. I'm going to close this issue, but feel free to re-open if there is something new brought up.
