### ISSUE TITLE
Add a note to differ raw.githack link from the raw link available on Github.

### ISSUE THREAD

**Issue by sravya71** [treehouses/treehouses.github.io#303]
### Problem
In step 3, I propose to Add a note to differ raw.githack from the raw link available on github.

### Steps to reproduce the problem
N/A 

### Screenshots
![image](https://user-images.githubusercontent.com/54302388/70383626-c2265d80-1925-11ea-93d1-20015877f9df.png)

### Proposed solution
Add a note stating that raw.githack and raw link available on github are different.

**Comment by CalebProvost** [comment]
Haha. Good distinction for new users of Github.
