### ISSUE TITLE
Download.md appearance does not match code

### ISSUE THREAD

**Issue by surferjreb** [treehouses/treehouses.github.io#304]
### Problem
I noticed in the download page the appearance was a little weird.  Then will looking through the code on the page I noticed that a list is suppose to appear in the beginning instead of a paragraph.

### Steps to reproduce the problem
Visit: [Download](https://treehouses.io/#!pages/download.md).

### Screenshots
![download_incorrect](https://user-images.githubusercontent.com/16308165/70384129-d24f3480-1947-11ea-960f-cc4dbc1c443d.png)
![download_incorrect2](https://user-images.githubusercontent.com/16308165/70384130-e004ba00-1947-11ea-8ae2-1292b93776d3.png)

### Proposed solution
Change the code to correct the appearance of the download page.  A `hard line space` just needs to be placed after the first sentence on the page `"The main features of treehouses-powered Raspberry Pi image are"`.  This will make it easier to read.

**Comment by john-dunbar** [comment]
Nice catch! I just tried the fix in my repository. It looks like that line space is exactly what it needs.
