### ISSUE TITLE
inappropriate word ( bad language )  "Shit"  in faq.md 

### ISSUE THREAD

**Issue by jamjakpa** [treehouses/treehouses.github.io#318]
### Problem
I found an<code> inappropriate word</code> ( bad language )<strong> "Shit" </strong>in the <code>faq.md</code> file under the section Helpful Links ---> Reference/Advanced ---><code>"Oh,Shit,Git"</code> .  I think its not a good way to express it like that, especially when we have new interns it might fall into a negative perception at the treehouses project and it looks very unprofessionell.
### Steps to reproduce the problem

N/A

### Screenshots

![Oh_shit_git](https://user-images.githubusercontent.com/44546990/70628344-d5af1e00-1bdc-11ea-8566-2bc4548558a8.jpg)

### Proposed solution

Go in the file https://treehouses.io/#!./pages/vi/faq.md and edit and fix it and rename it to : <strong>more references</strong>

**Comment by pattanawadee88** [comment]
"Oh shit, Git"  is just a name of the website but you can change it to an appropriate name if you want to :)

**Comment by dogi** [comment]
maybe we add `the website called` ... before the link :)

**Comment by dogi** [comment]
or `Oh s***, Git`

**Comment by dogi** [comment]
@/all please vote by thumbs up

**Comment by jamjakpa** [comment]
I like that Oh s***, Git.

**Comment by surferjreb** [comment]
I do agree it is not exactly appropriate in a professional manner, but it is a great reference and the name really explains that moment when you need it.
