### ISSUE TITLE
Google analytics, website performance.

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#331]
### Problem
**treehouses.github.io's website** can be given a **google analytics tracker** to see how many people are visiting it. The Github statistics only track how many users visit the repo not the website. The admin or whomever at treehouses will have to make the account and give us a tracking ID that we can add to the pages. As for performance it is pretty good but we can clean this up quite a bit anyway. The number of requests could be trimmed down for instance. **[GTMetrix Performance Scores](https://gtmetrix.com/reports/treehouses.io/uWZVbjxD)**

### Steps to reproduce the problem
1. Search treehouses.github.io for google analytics tracking codes and find none.
2. Click link above for GTMetrix and analyze results.

### Screenshots
[Test](https://i.imgur.com/4iIcsCN.png)

### Proposed solution
Since it seems Index.html is running the whole website anyway. That is the only place that should have a tracking code perhaps. I don't know what the goal was here either to have the whole site load on Index but it seems to be working pretty well. I think the Index page should be minified and another index should be somewhere for backup (un minified so people can edit it). Seeing as its the bulk of the coding minifying it would greatly **decrease** page load times.

**Comment by dogi** [comment]
@LordJashin32 too high issue for PR on 10 steps ;)

closing it for now ok?

**Comment by LordJashin32** [comment]
Yes, it's okay to close ;)
