### ISSUE TITLE
add Github profile pics 

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#333]
Right now there isn't any **Github profile pictures** on the website for any of the **Virtual Interns**. We can change this with an image tag. I'm not sure how this affects **copyright**. I assume its okay because Github owns and hosts the website anyway and they require no copyright notice according to https://github.com/logos.

Cheers.

**Comment by dogi** [comment]
@LordJashin32 we will keep this issue in mind,
but for now we set it `on hold`
