### ISSUE TITLE
Failed burning the treehouses image onto the microSD card

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#335]
### Problem
We should always run with the latest version of Etcher.
If the software has been installed in the past and a new version has been released, burning will failed.

### Steps to reproduce the problem
N/A (If you already have Etcher of old version, You can reproduce.)

### Screenshots
N/A

### Proposed solution
Install to Etcher of new version.

**Comment by kjong** [comment]
I'm using an older version of Etcher (1.5.59 to be exact) and haven't had any problems with flashing.

But it's probably better to be using the latest version anyways.

Maybe add a note [here](https://treehouses.io/#!./pages/vi/pi-setup.md) saying that if you run into any issues with flashing, to try and update Etcher?

**Comment by ghost** [comment]
Can I fix directly to a file in the pages/vi/pi-setup.md ?  or Can I need create new pull request?

**Comment by dogi** [comment]
@sabe-lab yes ... work on a PR ;D
