### ISSUE TITLE
fix grammer in download.md

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#337]
### Problem
Educational applications that are **only few commands** away

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Change to "Educational applications that are only **a** few commands away"

**Comment by phamduchongan93** [comment]
@LordJashin32 I believe the original version is correct. :)

**Comment by LordJashin32** [comment]
@phamduchongan93  Maybe I'm crazy. But my Firefox addon Grammarly agrees with me so I'm in a bit of a pinch lol. https://i.imgur.com/0SvXHhC.png
