### ISSUE TITLE
[feature] use gui section for gitrepositories.md (TortoiseGit, etc.)

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#341]
### Problem
Learning how to use git commands in the command line can be overwhelming for some. Some people may have experience in languages but not in git command line usage or GitHub in general. 
Using the command line can also slow down developer workflow or discourage otherwise would be interns from contributing. The time it takes to look up a fork reset command for instance. I would never memorize that unless it's simply 2 words. But sometimes it can be like 4 commands in a row. Also, I have to right-click to paste inside the bash/cmd prompt which takes additional time. When I can control-v into a gui instead. 

### Steps to reproduce the problem
N/A

### Screenshots
https://i.imgur.com/fvqp700.png

### Proposed solution
I don't remember off the top of my head if we can throw this in elsewhere. But we can throw it in somewhere about how to use a gui application like TortoiseGit to do the same job as outlined in git bash code. 

EDIT: Virtual Interns should definitely know what the commands are and learn them by using them. But once they know and have done it all. They might want to switch to a gui after that as shown above.  
EDIT2: Or maybe instead of a section. Maybe just an option for it mid-article with a link to a guide on how to use a gui program instead. And not Github's gui because it lacks the ability to revert commits (and hard-reset). But TortoiseGit which can do everything the bash can do and more with right-click.

**Comment by kjong** [comment]
If everything is done properly, we shouldn't have to use any complex git commands.
However, it doesn't hurt to have alternatives.

I think it would be best to have a small section, either a link to an external tutorial or a short guide you write up, maybe in [this page](https://treehouses.io/#!./pages/vi/gitrepositories.md)?

**Comment by LordJashin32** [comment]
@kjong Yeah that's what I was thinking. Like for instance if you need to update repo to be the same commit as treehouses you just do this:
![step1](https://i.imgur.com/s4xyRYj.png)
![step2](https://i.imgur.com/iHN2FKm.png)
![step3](https://i.imgur.com/M1FozxF.png)
![step4](https://i.imgur.com/OMQdrEZ.png)
![step5](https://i.imgur.com/adamrER.png)
![step6](https://i.imgur.com/c3BxRhT.png)
![step7](https://i.imgur.com/MkD84h6.png)
![step8](https://i.imgur.com/OR8MkhG.png)

Something like this. But do note you have to enable those options on your right-click menu I think.

**Comment by LordJashin32** [comment]
After second thoughts. I will research to find the easiest GUI. There is also a "Sync" button for TortoiseGit that does the same thing. All very interesting.

**Comment by phamduchongan93** [comment]
@LordJashin32 nice tool kit :+1: . This is pretty new to us. I don't know what @dogi think about this. GUI vs CLI. Nobody brought this up before.

**Comment by LordJashin32** [comment]
https://upriver.github.io/ : That will update your forked repo with original in 1 Click!
That link and https://git-scm.com/downloads . Git-gui is cross-platform and runs just like TortoiseGit. So this is a win-win in my book I've been waiting for this technology for years!
EDIT: Check [this](https://gyazo.com/db870b703c4e94029ea461b1e66b57d9) out too!:
