### ISSUE TITLE
About "Optional Hardware"

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#344]
# Problem
The most basic thing.
The following devices are required to start Raspberry Pi and check the initial operation.

（Required）
- USB keyboard
- Mouse
- Monitor
- HDMI cable
- Power Adapter
- Dhisplay

So, not optional. Probably everyone knows.
However, there are those who need to leave everything in their home country and prepare the device from scratch.
When reading this information,
We don't know what kind of tasks are going on, so I think it should be clearly stated.

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
（Required）
- USB keyboard
- Mouse
- Monitor
- HDMI cable
- Power Adapter
- Dhisplay

**Comment by phamduchongan93** [comment]
@sabe-lab I respectfully disagree. We really want anyone to start their project with minimal resource such as Andoird app, raspberry pi computer and micro sd card . Secondly, the **Treehouses** remote app is the main tool to deploy the applications, and we promote interaction between the app and the pi.

**Comment by ghost** [comment]
@phamduchongan93 Thanks comment.
in short,if treehouses is installed correctly, This issue is not necessary because it can be controlled remotely without checking the operation?

**Comment by phamduchongan93** [comment]
@sabe-lab yes. The debugging and testing you mention would be performed via the ssh session. Rest  assured that @dogi will guide you through the testing workflow after you become one of your intern.

**Comment by ghost** [comment]
@phamduchongan93 OK, I understand it.
Thank you very much !!
