### ISSUE TITLE
Howto edit a PR after you post it

### ISSUE THREAD

**Issue by jamjakpa** [treehouses/treehouses.github.io#349]
### Problem
As I went over the markdown section : 
https://raw.githack.com/jamjakpa/jamjakpa.github.io/rpi_serial_cable/#!./pages/vi/githubandmarkdown.md 

at the end ( look at the screenshot where the yellow arrow is ) after make changes, we can implement it there right after. The user actually don't know how to edit a PR
in step 3 it shows you how to do a Pull request but not how to edit after you post it .
Not everyone actually knows that in the beginning.

### Proposed solution
<code>Howto :  files changed --> File --> Edit </code>

### Screenshot

![File_Edit](https://user-images.githubusercontent.com/44546990/71315369-f9116e80-240f-11ea-8f3c-17eb20941aaa.jpg)

**Comment by irisb1701** [comment]
looks good, you can start working on it

**Comment by jamjakpa** [comment]
its fixed
