### ISSUE TITLE
Android and Treehouses remote can't find Raspberry Pi

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#358]
### Problem
I completed the initial setup in step 1 and started the Raspberry Pi. 
I turned on Bluetooth on Android and launched Tree House, but I can't find it.
I was able to confirm Raspberry Pi from the router, and I could connect to Raspberry Pi from Laptop via SSH.

### Steps to reproduce the problem
N/A

### Screenshots
https://github.com/sabe-lab/sabe-lab.github.io/tree/master/images

### Proposed solution
N/A (Troubleshooting now)

**Comment by LordJashin32** [comment]
Try running in your ssh console -
"treehouses detectrpi"
"treehouses bluetooth on"

**Comment by ghost** [comment]
Thanks @LordJashin32 , I tried this.
Am I skipping steps or Should I install rpi?

pi@treehouses:~ $ treehouses detectrpi
nonrpi
pi@treehouses:~ $ treehouses bluetooth on
Error: Must be run with rpi system

**Comment by kjong** [comment]
It looks like it thinks that you're not running it on a raspberry pi.

What raspberry pi are you using?

**Comment by ghost** [comment]
Thanks @kjong.
I'm using the raspberry pi 4 model B.

This is picture.
https://raw.githubusercontent.com/sabe-lab/sabe-lab.github.io/master/images/raspberry_pi01.jpg

https://raw.githubusercontent.com/sabe-lab/sabe-lab.github.io/master/images/raspberry_pi02.jpg

**Comment by kjong** [comment]
@sabe-lab 
Could you try running `cat /proc/cpuinfo` in the rpi terminal? Depending on the amount of RAM your board has, you should get either `a03111`, `b03111`, `c03111`, or `c03112`.

The script to detect your rpi is pretty simple so I don't think there's an issue with the code there.

Maybe you could try to re-flash the latest image (treehouses-116) and try again?

**Comment by LordJashin32** [comment]
@kjong I don't think the latest image has ```c03112``` yet. I am also on this model. @sabe-lab you're going to have to download https://github.com/treehouses/cli after you install your RPi4, and run for instance in terminal ```./cli.sh bluetooth on``` . You should also see bluetooth icon in top right hand corner of your screen you can use too. Hit Make Discoverable. Then try connecting with your phone. 

Console: 
```bash
git clone https://github.com/treehouses/cli
cd cli
bash ./cli.sh bluetooth on
```

**Comment by ghost** [comment]
@LordJashin32 @kjong 
Thank you very much for your advice.
suddenly, raspberry pi can't get ip address from router.

I will retry from os(treehouses) install.

**Comment by ghost** [comment]
I tried again from OS reinstallation and the same phenomenon occurred, but after executing the command as indicated by @LordJashin32  , it was resolved.

However, the error output continues even if the procedure is continued according to the previous procedure. Is this normal behavior? (I tried from a laptop, but similar output results)

https://github.com/sabe-lab/sabe-lab.github.io/blob/master/images/Screenshot_20200104-221245.jpg

**Comment by LordJashin32** [comment]
> 
> 
> I tried again from OS reinstallation and the same phenomenon occurred, but after executing the command as indicated by @LordJashin32 , it was resolved.
> 
> However, the error output continues even if the procedure is continued according to the previous procedure. Is this normal behavior? (I tried from a laptop, but similar output results)
> 
> https://github.com/sabe-lab/sabe-lab.github.io/blob/master/images/Screenshot_20200104-221245.jpg

You're going to have to use this [image](http://dev.ole.org/treehouse-117.img.gz).

**Comment by ghost** [comment]
I tried to it's image. however, I can't even make an SSH connection from laptop.
It's enough. Wasted time and money.

**Comment by LordJashin32** [comment]
> 
> 
> I tried to it's image. however, I can't even make an SSH connection from laptop.
> It's enough. Wasted time and money.

The pi has to be connected to the internet. Then run ```hotname -I``` to get the ip address. Check the first steps.

**Comment by LordJashin32** [comment]
No no don't give up! 
I am sorry you feel this way.
If you need anymore help please let us know.

**Comment by ghost** [comment]
I know and appreciate your help.
However, I followed the instructions and follow the simple steps of installing the OS and connecting to the network.
I can't spend time on tasks where this simple process doesn't follow the steps.

**Comment by dogi** [comment]
> I can't spend time on tasks where this simple process doesn't follow the steps.

@sabe-lab agree ... we got surprised by a new version of the raspberry pi 4b board
as you can see based on your feedback we fixed this with https://github.com/treehouses/cli/commit/980b03a3f7ee50a202011b0a2af46d8c6acb119b

and now is part of treehouse image http://download.treehouses.io/treehouse-118.img.gz (built this Monday)

in other words **thank you** ;)
I am sorry you had a hard time
