### ISSUE TITLE
Fixes in Introductory Steps

### ISSUE THREAD

**Issue by sravya71** [treehouses/treehouses.github.io#367]
### Problem
1. Change the font of word "NOTE" at the beginning.
2. Fix the typo "troublshooting".
3. Fix the Grammar mistake "us updated a relatively good".

### Steps to reproduce the problem
N/A 

### Screenshots
![image](https://user-images.githubusercontent.com/54302388/71812651-b8ffec00-309d-11ea-8a92-0a679ca31783.png)
![image](https://user-images.githubusercontent.com/54302388/71812666-c4531780-309d-11ea-97cc-e5168110bfe1.png)
![image](https://user-images.githubusercontent.com/54302388/71812677-cf0dac80-309d-11ea-949c-6ac4a9b4ec6c.png)
![image](https://user-images.githubusercontent.com/54302388/71812685-d765e780-309d-11ea-975c-d73dab3d6975.png)

### Proposed solution
1.Change the word "NOTE" to bold and remove " ' ".
2.Change the spelling to "troubleshooting".
3. Add word "on"  - "updated on a relatively good amount".

**Comment by LordJashin32** [comment]
Good issue.
