### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by engherery** [treehouses/treehouses.github.io#370]
### Problem
I am in Step6. when i tried to create a new branch as directed by the documentation i could not see ( Create branch ) as you can see in the following screenshot. Any help please ?

### Steps to reproduce the problem
 N/A .

### Screenshots
![CreatBranStep6](https://user-images.githubusercontent.com/55458316/72202439-9c363080-3470-11ea-8163-ba6d5218788a.png)

### Proposed solution
N/A.

**Comment by Nida8930** [comment]
Glad to see you are making progress! For future issues you should fill out the template so we can see the problem/issue you encountered and what you would like to do to fix it. Let me know if you have any other questions.

**Comment by LordJashin32** [comment]
@engherery If you created a fork in Step 5. That will be on your own profile page and not on the treehouses github page does that make sense? It would be at github.com/engherery/

**Comment by engherery** [comment]
> @engherery If you created a fork in Step 5. That will be on your own profile page and not on the treehouses github page does that make sense? It would be at github.com/engherery/

Thank you LordJashin

**Comment by kjong** [comment]
You don't have the rights to create branches on the main repository yet.

While you're doing the ten steps, you should be working on your own copy of the treehouses.github.io repository that you forked.

**Comment by LordJashin32** [comment]
> > @engherery If you created a fork in Step 5. That will be on your own profile page and not on the treehouses github page does that make sense? It would be at github.com/engherery/
> 
> Thank you LordJashin

It looks like you were able to make a branch on your forked copy. Gonna go ahead and close this. Feel free to reopen if there is any other problems you run into. @engherery
