### ISSUE TITLE
Inconsistent number of required reviews for pull request.

### ISSUE THREAD

**Issue by jorgitoooo** [treehouses/treehouses.github.io#378]
### Problem
Not a huge problem but I noticed an inconsistency in the [Github and Markdown](https://treehouses.io/#!./pages/vi/githubandmarkdown.md) page. The last sentence of the second to last paragraph states that three approving reviews are required to merge your Markdown profile, but the actual number of required reviews for a pull request to be merged is two.

### Steps to reproduce the problem
N/A

### Screenshots
![issue_1_1](https://user-images.githubusercontent.com/19233614/72689631-324d0500-3ac8-11ea-8117-1123cc181857.PNG)
![issue_1_2](https://user-images.githubusercontent.com/19233614/72689633-3547f580-3ac8-11ea-8c76-b5c3b4548b86.PNG)

### Proposed solution
Two things can be done here:
1. We can modify the `pages/vi/githubandmarkdown.md` itself and reduce the number to two.
or
2. A repository administrator can increase the number of required reviews to three by following these [steps](https://help.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests).

**Comment by dogi** [comment]
@garciaj92 good job ... we dropped it from 3 to 2

**Comment by jorgitoooo** [comment]
@dogi 
Great. I'd like to be assigned to this issue if possible.
