### ISSUE TITLE
Add link to 'Helpful Videos' section of FAQ page

### ISSUE THREAD

**Issue by jorgitoooo** [treehouses/treehouses.github.io#381]
### Problem
I noticed that we don't have a link to a video explaining docker and I found a free [course](https://www.youtube.com/watch?v=fqMOX6JJhGo) online that could be very useful.

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
1. Modify the [FAQ](https://treehouses.io/#!./pages/vi/faq.md) page to include a link to the free course.

**Comment by jamjakpa** [comment]
I like that Idea, some people understand visual better than text.
