### ISSUE TITLE
Remove links leading to pages that don't exist

### ISSUE THREAD

**Issue by jorgitoooo** [treehouses/treehouses.github.io#382]
### Problem
We are linking to pages that don't exist and it is inconsistent with our other placeholder/dummy urls. I think, to remain consistent with other placeholder/dummy urls, it would be best to place  [https://YourUserName.github.io](https://YourUserName.github.io) inside of back ticks (`https://YourUserName.github.io`).

### Steps to reproduce the problem
N/A

### Screenshots
**Change these links**:
![Link](https://user-images.githubusercontent.com/19233614/72765803-06eb1880-3ba3-11ea-9170-fa1262fbada7.PNG)
**Into back tick urls such as this**:
![Back tick](https://user-images.githubusercontent.com/19233614/72765972-e8395180-3ba3-11ea-957f-670a28e74120.PNG)

### Proposed solution
1. Modify [https://treehouses.io/#!./pages/vi/githubandmarkdown.md](https://treehouses.io/#!./pages/vi/githubandmarkdown.md) by removing the links [https://YourUserName.github.io](https://YourUserName.github.io) and replacing them with `https://YourUserName.github.io`.

**Comment by LordJashin32** [comment]
Agreed
