### ISSUE TITLE
tor link needs clarification for blocked to use vpn

### ISSUE THREAD

**Issue by Neethu-Mohan** [treehouses/treehouses.github.io#386]
### Problem
The link provided to download and install Tor is not working in
    [SSHTutorial](https://treehouses.io/#!./pages/vi/sshpi.md )

### Steps to reproduce the problem
N/A
### Screenshots
![SC](https://user-images.githubusercontent.com/25002463/72980634-a0a10880-3de3-11ea-9d03-1ede2bbf9319.png)

### Proposed solution
I have used this link to install tor and I think this will be helpful others
[Tor](https://www.techspot.com/downloads/5183-tor-browser.html)

**Comment by jorgitoooo** [comment]
That's interesting. I actually used that link and it worked for me.

**Comment by jorgitoooo** [comment]
How did your browser behave after you clicked on the link?
Also, what browser are you using?

**Comment by Neethu-Mohan** [comment]
Is this link working for you? I tried this link in both chrome and Firefox.
Chrome shows this page
![chrome](https://user-images.githubusercontent.com/25002463/73049260-a8fd5000-3e84-11ea-99c7-44b371f81315.png)

Firefox shows this page
![Firefox](https://user-images.githubusercontent.com/25002463/73049268-ad296d80-3e84-11ea-8048-46883c910783.png)

**Comment by kjong** [comment]
The `Get Tor` link also works for me.

I'm not too sure about the legitimacy of techspot (although I think it should be fine), but I'm kind of hesitant to add links to third party sites, especially when the official site seems to be working fine.

**Comment by Neethu-Mohan** [comment]
Yeah I agree. If the link is working fine, there is no need to change it. It may be a problem from my side.I thought everyone faces the same issue.

**Comment by LordJashin32** [comment]
[This](https://www.reddit.com/r/TOR/comments/aj9bmm/firefox_says_connection_is_not_secure_when_trying/) might have some relevance. Usually when I run into this problem I have to reinstall the OS eventually. I used to run into it as a virus or rootkit that would screw up browser security. What version of Windows are you running? You can try a free online vpn and see if that works too but I doubt it will. Whenever I run into this usually its a major computer problem. Either you need updates on your browsers or there's something rotten.

**Comment by mickele1331** [comment]
> Yeah I agree. If the link is working fine, there is no need to change it. It may be a problem from my side.I thought everyone faces the same issue.

maybe your network administrator blocked some websits by firewall.

**Comment by Neethu-Mohan** [comment]
@mickele1331  Yeah it was the problem. I used Express VPN and it works fine.

**Comment by LordJashin32** [comment]
> @mickele1331 Yeah it was the problem. I used Express VPN and it works fine.

I thought about this and perhaps someone should add some context to use a VPN if the tor project page is unavailable for them. Were you able to complete these steps? If you can't seem to do it we can make an exception for you to skip these steps if its blocked for you.

**Comment by Neethu-Mohan** [comment]
@LordJashin32  Yes, I could complete these steps.

**Comment by evoong** [comment]
This link works for me

**Comment by vkabc** [comment]
It works for me too.

**Comment by hokageYondaime** [comment]
Be aware of using tor browsers as this is not recommended for all personal vpn, exposing your data or confidential files might alter your machine file & file systems.

**Comment by rohansuri17** [comment]
Works for me too! Didn't have any issues on macOS and ubuntu 20.04
