### ISSUE TITLE
Raspberry pi Hardware Set-up- Helpful video

### ISSUE THREAD

**Issue by Neethu-Mohan** [treehouses/treehouses.github.io#387]
### Problem
Adding a helpful video in the section "Powering on the raspberry pi" on [Setting up your Raspberry pi](https://treehouses.io/#!./pages/vi/pi-setup.md)  page will be very helpful.

### Steps to reproduce the problem
 N/A 

### Screenshots
![screen shot](https://user-images.githubusercontent.com/25002463/73126587-123caa80-3fce-11ea-9372-df55bf67b177.PNG)

### Proposed solution
I think this [video](https://www.youtube.com/watch?v=gbJB3387xUw&t=182s) will be helpful.

**Comment by LordJashin32** [comment]
Good idea again. For these last 2 issues. I would say. Make sure this is best location to add these links. If you can think of a better in context location. Or etc. Do that instead.

**Comment by Neethu-Mohan** [comment]
I think this should be added under[Helpful Links](https://treehouses.io/#!./pages/vi/faq.md) section

**Comment by evoong** [comment]
some raspberry have different hardware setups, i would suggest just noting to find instructions for your own personal raspberry on youtube

**Comment by Neethu-Mohan** [comment]
@Evoong I thought this tutorial provide an idea about how to start with a raspberry pi.

**Comment by sarahrams** [comment]
Good idea if you can find a general video that will be helpful for all versions of raspberry Pi's.

**Comment by sarahrams** [comment]
Good idea if you can find a video that will be helpful for several versions of hardware.

**Comment by rohansuri17** [comment]
I think this would be really useful especially for people new to the raspberry pi interface

**Comment by hjama15** [comment]
I agree with it being a helpful for people not familiar with it. Though I would include a video on the newer model 4.

This link might also be helpful if one wants a brief overview of what it is and what it can do.

https://opensource.com/resources/raspberry-pi
