### ISSUE TITLE
Error while running Nextcloud container

### ISSUE THREAD

**Issue by Neethu-Mohan** [treehouses/treehouses.github.io#389]
I am in step 7. I created Nextcloud container with Docker and I ran the following commands successfully,
treehouses tor add 80 8080
treehouses tor notice on
treehouses tor
But whenever I am trying to navigate to .onion address in Tor browser, it takes a long time to load the page. Sometimes I am getting the "timeout" error.

### Steps to reproduce the problem
Write N/A if not applicable.

### Screenshots
Drag and drop images below. Write N/A if not applicable.
![error](https://user-images.githubusercontent.com/25002463/73251789-47a9e980-41c2-11ea-94dc-b8eaa5040c67.png)

### Proposed solution
Write N/A if not applicable.

**Comment by LordJashin32** [comment]
@Neethu-Mohan . Try it over VPN and see if maybe it works? You can skip this if you want.

**Comment by dogi** [comment]
@Neethu-Mohan hmm redo once again ... if it still doesn't work just move on to step8

**Comment by Neethu-Mohan** [comment]
okay, I will retry once again.

**Comment by sydneyaldo** [comment]
Maybe the Raspberry Pi wasn't able to connect to the internet. I resolved this issue by flashing the SD card again to make sure the Raspberry Pi was connected to a Wifi network
