### ISSUE TITLE
Add link to helpful video section of FAQ page

### ISSUE THREAD

**Issue by Neethu-Mohan** [treehouses/treehouses.github.io#390]
### Problem
I found that an explanation for the working of ssh key and its relevance is missing in the [firststep.md](https://treehouses.io/#!pages/vi/firststeps.md) .

### Steps to reproduce the problem
 N/A 

### Screenshots
N/A 

### Proposed solution
Adding a video link in [Helpful_links](https://treehouses.io/#!./pages/vi/faq.md#Helpful_Links) section.  I found this [tutorial](https://youtu.be/y2SWzw9D4RA) very helpful.

**Comment by LordJashin32** [comment]
Good idea.

**Comment by evoong** [comment]
sounds good to me
