### ISSUE TITLE
should link faq to step 7

### ISSUE THREAD

**Issue by evoong** [treehouses/treehouses.github.io#397]
### Problem
On step 7, I ran into a error. I wasn't able to ssh over to pi. After looking for a while, I discovered that the fix was in the faq
### Steps to reproduce the problem
n/a
### Screenshots
n/a
### Proposed solution
add a warning message and add a link to the faq

**Comment by Neethu-Mohan** [comment]
That will be helpful.

**Comment by evoong** [comment]
some already fixed it
