### ISSUE TITLE
add reminder for step 7

### ISSUE THREAD

**Issue by evoong** [treehouses/treehouses.github.io#398]
### Problem
On step 7, I ran into a error. i wasn't able to u run "ssh root@[IP address]" right away. i had t go back to step 2
### Steps to reproduce the problem
n/a
### Screenshots
n/a
### Proposed solution
write a note to remind the person to add the ssh onto the pi, and link to step 2

**Comment by LordJashin32** [comment]
Why two issues for this? Seems pretty vague to me. If you need help with screenshots use - https://app.prntscr.com/en/index.html
