### ISSUE TITLE
Step 5 typo

### ISSUE THREAD

**Issue by evoong** [treehouses/treehouses.github.io#404]
### Problem
there is a typo in the cd step. the period is apart of the command

### Steps to reproduce the problem
n/a

### Screenshots
![image](https://user-images.githubusercontent.com/46852557/73487030-343e8000-4374-11ea-9081-52917b3040d7.png)

### Proposed solution
space out the period

**Comment by LordJashin32** [comment]
I think taking out the period would be better. But good idea.

**Comment by evoong** [comment]
> I think taking out the period would be better. But good idea.

you're right, that would be a better idea

**Comment by Neethu-Mohan** [comment]
sounds good to me.
