### ISSUE TITLE
Finding your PI ip unclarity in Android Step

### ISSUE THREAD

**Issue by evoong** [treehouses/treehouses.github.io#405]
### Problem
For the Android option there are two different IP addresses. I automatically assume i would require the second IP address

### Steps to reproduce the problem
N/A

### Screenshots
Drag and drop images below. Write N/A if not applicable.
![image](https://user-images.githubusercontent.com/46852557/73487657-67cdda00-4375-11ea-821c-39093faf378f.png)

### Proposed solution
just add a message to use the first IP address shown

**Comment by LordJashin32** [comment]
Looks good.
