### ISSUE TITLE
Configuring fork typo

### ISSUE THREAD

**Issue by evoong** [treehouses/treehouses.github.io#409]
### Problem
There is a period at the end of the change directory cmd

### Steps to reproduce the problem
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/46852557/73604585-0ec29980-4561-11ea-87b8-f80f30398f6c.png)

### Proposed solution
delete the period

**Comment by LordJashin32** [comment]
Looks good. Another easily looked over nuance.

**Comment by jamjakpa** [comment]
good catch
