### ISSUE TITLE
confusing instructions creating branch

### ISSUE THREAD

**Issue by Neethu-Mohan** [treehouses/treehouses.github.io#415]
### Problem
I followed these steps (Screenshot 1) and I ended up creating two branches (duplicated ones) in my Github repo. I think, if we are creating a branch in this step (screenshot 2), we don't need to create a new branch in our local repo by using git checkout -b <new_branch_name>. We can just use the following command to work on the branch we created in the Github repo
git fetch origin
git checkout <branch_name>
If branch is not created in this step (screenshot 2), then we should use git checkout -b <new_branch_name> and continue the further steps.

### Steps to reproduce the problem
Write N/A if not applicable.

### Screenshots
![Pic1](https://user-images.githubusercontent.com/25002463/73719974-93601400-4729-11ea-9ab8-bdd4fe09a33a.png)
![pic2](https://user-images.githubusercontent.com/25002463/73719978-96f39b00-4729-11ea-9ed2-2d8ca2896893.png)
![pic3](https://user-images.githubusercontent.com/25002463/73719996-9c50e580-4729-11ea-83f6-b23a1730e25b.png)

### Proposed solution
Change the text as follows:
To create a new branch, go to your github repo and create it using the same steps as you can see [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository) (do not delete your branch). Then, At the Terminal, use **git fetch origin** to get the new data and use **git checkout <  name_of_your_new_branch>**.
Or Use **git checkout master** to switch to master branch, then use **git checkout -b <New_branch_name >** to create and switch to a new branch on your local repository.

**Comment by kjong** [comment]
Yes, you are correct.

The directions specify two different ways to create a branch, but the wording makes it seems like you should do both, which results in creating two branches.

Your solution looks good: make sure that the reader understands that these are two different methods of creating branches and that they should do one or the other, not both.

**Comment by LordJashin32** [comment]
Clarification here sounds good to me.
