### ISSUE TITLE
add #! note for raw.githack link

### ISSUE THREAD

**Issue by Neethu-Mohan** [treehouses/treehouses.github.io#416]
### Problem
We are using raw.githack link at first in [Step 3](https://treehouses.io/#!./pages/vi/firststeps.md#Step_3_-_Markdown_and_Fork_Tutorial). 
But a note about adding #! after the branch name to get the link in presentation mode is missing in this [step](https://treehouses.io/#!./pages/vi/githubandmarkdown.md).

### Steps to reproduce the problem
N/A 

### Screenshots
![Screenshot from 2020-02-04 12-00-57](https://user-images.githubusercontent.com/25002463/73734522-6ff79200-4746-11ea-8f04-27fa8e9eac37.png)

### Proposed solution
I think, adding a small note regarding this at [step 3](https://treehouses.io/#!./pages/vi/firststeps.md#Step_3_-_Markdown_and_Fork_Tutorial) over here (Screenshot) will be helpful.

**Comment by dogi** [comment]
@Neethu-Mohan noticed too that we need to do something there ...

**Comment by dogi** [comment]
... too many people do not understand raw.githack stuff
