### ISSUE TITLE
Changing a Dead Link to Text

### ISSUE THREAD

**Issue by Neethu-Mohan** [treehouses/treehouses.github.io#424]
### Problem
There is a dead link in step 3. I think it should change.

### Steps to reproduce the problem
 N/A 

### Screenshots
![screen1](https://user-images.githubusercontent.com/25002463/74133988-5b0d7980-4bf2-11ea-8724-2863a51c9adc.png)

### Proposed solution
Change the link to normal text.

**Comment by evoong** [comment]
I agree

**Comment by LordJashin32** [comment]
This is better for SEO. Other than that I think for me it wouldn't really be useful. I'd rather have the speed of copy and pasting and updating it. But since we see lots of new interns just paste it in without changing the YourUsername/YourBranchName parts. I think we can change this.
