### ISSUE TITLE
firststeps.md step needs capitalization 

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#432]
### Problem
```Step 7 - other Services running from a Raspberry Pi```
https://treehouses.io/#!./pages/vi/firststeps.md#Step_7_-_other_Services_running_from_a_Raspberry_Pi

### Steps to reproduce the problem
N/A

### Screenshots
N/A

### Proposed solution
Needs to be:
```Step 7 - Other Services running from a Raspberry Pi```

**Comment by ghost** [comment]
Can I be assigned to it?
