### ISSUE TITLE
issue template causes popups

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#434]
### Problem
Whenever you create a new issue and delete the top information down to ###Problem.
The ### causes issue popups. 

### Steps to reproduce the problem
Create a new issue and delete everything before "### Problem"

### Screenshots
![](https://i.imgur.com/RUPQZZr.png)

### Proposed solution
We change https://raw.githubusercontent.com/treehouses/treehouses.github.io/master/.github/ISSUE_TEMPLATE/issue_template.md to include a space before each header would solve the problem.

**Comment by ComputerOnFire** [comment]
I can take care of this
