### ISSUE TITLE
Typos on github-issues.md

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#436]
### Problem
There are some typos on the github-issues.md page.

### Steps to reproduce the problem
Visit https://treehouses.io/#!./pages/vi/github-issues.md. I have posted screenshots and circled where the typos are.

### Screenshots
![1](https://user-images.githubusercontent.com/51290481/75416903-a798ca80-58fd-11ea-927c-f21b4da7d6a6.png)

![2](https://user-images.githubusercontent.com/51290481/75416909-aff10580-58fd-11ea-83d7-010ee99161b4.png)

### Proposed solution
"a decriptive..." should be "a descriptive..." I think that "the" should be removed from "In this case your the Pull Request..." because the rest of the sentence uses "you" and "your."

**Comment by LordJashin32** [comment]
I like the circles on the wrong text. Made my role here easier. Thanks. This is ready to be completed.
