### ISSUE TITLE
Small errors on githubandmarkdown.md

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#437]
### Problem
Under the "Markdown" heading, for the third bullet, it says "A bigger Markdown cheat sheets" instead of "A bigger Markdown cheat sheet..." Also there is no period at the end. Only reason it stood out to me was because the other bullets have periods at the end.

### Steps to reproduce the problem
Visit https://treehouses.io/#!./pages/vi/githubandmarkdown.md. I noted in red on the screenshot where the tiny errors are.

### Screenshots
![3](https://user-images.githubusercontent.com/51290481/75418279-1af00b80-5901-11ea-975f-36638c4687ca.png)

### Proposed solution
Change it from plural to singular and add the period.

**Comment by LordJashin32** [comment]
Looks good, ready for VI.
