### ISSUE TITLE
sentence structure in orientation.md

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#441]
### Problem
In the orientation.md file, under rpi-couchdb for the Active System Teams Projects, the sentence cuts off like this: "CouchDB is a document database meaning that it. This means a NOSQL database that uses..."

### Steps to reproduce the problem
Visit https://treehouses.io/#!./pages/vi/orientation.md. I noted in red on the screenshot where the error is.

### Screenshots
![4](https://user-images.githubusercontent.com/51290481/75508008-b55b5800-59b0-11ea-9656-66380f1f0f80.png)

### Proposed solution
I would suggest changing it so it reads like this: "CouchDB is a document database meaning that it is a NoSQL database that uses..."

**Comment by LordJashin32** [comment]
Good catch.
