### ISSUE TITLE
orientation.md plural needed

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#442]
### Problem 
pull request needs to be pull requests with an s. 
https://treehouses.io/#!./pages/vi/orientation.md

### Steps to reproduce the problem
https://treehouses.io/#!./pages/vi/orientation.md

### Screenshots
![](https://i.imgur.com/wE1wxug.png)

### Proposed solution
Change to ```issues / pull requests```

**Comment by ghost** [comment]
Can I do this one?

**Comment by LordJashin32** [comment]
Fantastique. Merci beaucoup.
