### ISSUE TITLE
chat.md commas not needed

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#443]
### Problem
There is no pause in reading the sentence in english. So no need for the commas in ```
Gitter provides tight integration with Github and provides full rich text support through Markdown, an important tool for clean, efficient communication.

### Steps to reproduce the problem
https://treehouses.io/#!pages/chat.md

### Screenshots
![](https://i.imgur.com/L0Q0vLE.png)

### Proposed solution
Change to
```
Gitter provides tight integration with Github and provides full rich text support through Markdown an important tool for clean and efficient communication.
```

**Comment by ghost** [comment]
I can take a shot at this one if you want.

**Comment by LordJashin32** [comment]
> I can take a shot at this one if you want.

Go for it!
