### ISSUE TITLE
index.md needs past tense verb

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#444]
### Problem
You like what? Like needs to have a past tense verb before it to make sense in this context. 
```Feel free to direct message our members in Gitter if you like.```
Needs to change to
```Feel free to direct message our members in Gitter if you'd like.```

### Steps to reproduce the problem
https://treehouses.io/#!index.md

### Screenshots
![](https://i.imgur.com/5opuw03.png)

### Proposed solution
Change to ```you'd like.```

**Comment by ghost** [comment]
Do you want me to take a stab at it?

**Comment by LordJashin32** [comment]
> Do you want me to take a stab at it?

Yup all yours buddy.
