### ISSUE TITLE
Some missing periods in firststeps.md

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#446]
### Problem
Under "Step 8 - Create Issues and Pull Requests," in the second paragraph, the way it reads is "...Get approval to work on the issues you have created Make sure someone from the System's team confirms that you should work on the issue, BEFORE you start to work on it Resolve..." I don't see a period after the word "created" and "on it."

### Steps to reproduce the problem
Visit https://treehouses.io/#!./pages/vi/firststeps.md#Step_1_-_Installing_and_finding_your_Raspberry_Pi. I have noted in red where the periods are missing.

### Screenshots
![5](https://user-images.githubusercontent.com/51290481/75599594-6bd44100-5a74-11ea-981e-7665781c6407.png)

### Proposed solution
Add the periods so it reads as "...Get approval to work on the issues you have created. Make sure someone from the System's team confirms that you should work on the issue, BEFORE you start to work on it. Resolve..."

**Comment by LordJashin32** [comment]
Amazing

**Comment by jayala-29** [comment]
nice catch :)

**Comment by ComputerOnFire** [comment]
I'll edit this page
