### ISSUE TITLE
Misspelling in faq.md

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#447]
### Problem
In the faq.md file, under "Q12: Why can't I ssh into my Raspberry Pi after installing a new treehouses image?", the second bullet reads as "To fix this tpye the command..."

### Steps to reproduce the problem
Visit https://treehouses.io/#!pages/vi/faq.md. I noted in red where the misspelling is.

### Screenshots
![6](https://user-images.githubusercontent.com/51290481/75599711-6c210c00-5a75-11ea-98f0-1693853c3221.png)

### Proposed solution
Change "tpye" to "type."

**Comment by LordJashin32** [comment]
Good catch this is impressive you are able to find all these on top of the ones i found.

**Comment by ComputerOnFire** [comment]
I'll fix the typo
