### ISSUE TITLE
Change from singular to plural in orientation.md

### ISSUE THREAD

**Issue by ghost** [treehouses/treehouses.github.io#448]
### Problem
In the orientation.md file, under "Reviewing Pull Requests and Issues," the second paragraph reads as "...coming from different background and culture, it might..." The words "background" and "culture" should be plural.

### Steps to reproduce the problem
Visit https://treehouses.io/#!./pages/vi/orientation.md. I have noted in red where the issue is.

### Screenshots
![7](https://user-images.githubusercontent.com/51290481/75599938-907de800-5a77-11ea-9ec1-14d9419aa265.png)

### Proposed solution
Change it so it reads as "...coming from different backgrounds and cultures, it might..."

**Comment by LordJashin32** [comment]
Looks good.

**Comment by dyeh123** [comment]
I think this is a good suggestion. Plural makes the sentence sound much nicer.
