### ISSUE TITLE
capitalization in orientation.md

### ISSUE THREAD

**Issue by ComputerOnFire** [treehouses/treehouses.github.io#454]
### Problem
In the oritentation.md file, the link to "Happy hacking hangout" session does not share the same capitalization as "Happy Hacking Hangout" in the above Weekly Schedule paragraph.

### Steps to reproduce the problem
Visit https://treehouses.io/#!./pages/vi/orientation.md and scroll to the Weekly Schedule section.

### Screenshots
![noy8aih7](https://user-images.githubusercontent.com/3631329/76692911-5ee64e80-662b-11ea-8b8d-cb90cadb65d9.jpg)

### Proposed solution
Change the "Happy hacking hangout" link text to read "Happy Hacking Hangout".

**Comment by LordJashin32** [comment]
I like it. We need to capitalize on this for our meetings. Good find.
