### ISSUE TITLE
navbar button redirects to 404 in index.html

### ISSUE THREAD

**Issue by ComputerOnFire** [treehouses/treehouses.github.io#456]
### Problem
In the navigation bar at the top of the page, the home button directs the user to https://treehouses.io/# which temporarily brings the user to the 404 page before they are redirected to the home page.

 ### Steps to reproduce the problem
Visit any page on the markdown wiki and click on the treehouses.io button at the top left of the navigation bar. Click it in quick succession to see the redirect page temporarily show.

 ### Screenshots
![gFNm6jB](https://user-images.githubusercontent.com/3631329/76758856-8d157c80-6758-11ea-862a-fcab085e7c5d.gif)

 ### Proposed solution
Change line 2853 of index.html from:
`navbar += '<a class="navbar-brand" href="#"></a>'; ` 
to:
`navbar += '<a class="navbar-brand" href="#!index.md"></a>';`

**Comment by LordJashin32** [comment]
Kudos. Good catch.
