### ISSUE TITLE
missing period in orientaton.md

### ISSUE THREAD

**Issue by ComputerOnFire** [treehouses/treehouses.github.io#459]
### Problem
Under "Merging A Pull Request", the first bullet point is missing a period.

 ### Steps to reproduce the problem
Go to https://treehouses.io/#!./pages/vi/orientation.md

 ### Screenshots
![Screenshot_2020-03-20_01-36-49](https://user-images.githubusercontent.com/3631329/77141573-6783be00-6a4b-11ea-8478-3982b218c577.png)

 ### Proposed solution
Add a period to the sentence `Select "Squash Merge"`

**Comment by jayala-29** [comment]
good catch :)

**Comment by dyeh123** [comment]
Nice find

**Comment by saurabh-mish** [comment]
IMO bullet points do not end with a period, unless it is a paragraph. The periods in the second and third bullet points (and its sub-bullet points) should be removed.

**Comment by warthog16** [comment]
For consistency, it might be better to remove the other periods in the bullet points

**Comment by sydneyaldo** [comment]
The issue isn't resolved yet, should I remove all the periods in the bullet points?

**Comment by ComputerOnFire** [comment]
As others suggested, removing the periods from bullet points would be more consistent with formatting.

**Comment by sydneyaldo** [comment]
Please check out my fix above
