### ISSUE TITLE
vagrant clarify install

### ISSUE THREAD

**Issue by jayala-29** [treehouses/treehouses.github.io#461]
### Problem
Another way to install Vagrant on Mac OS

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
1.  Install Homebrew from <https://brew.sh/> 
2.  In Terminal, type without quotes "brew cask install vagrant"

**Comment by LordJashin32** [comment]
Each distribution/os has their own way to install it. I think we should have an install section just pointing back to the vagrant website instead. This is too specific and not inclusive to the other os/dist's.
