### ISSUE TITLE
formatting in firststeps.md

### ISSUE THREAD

**Issue by ComputerOnFire** [treehouses/treehouses.github.io#463]
### Problem
The placement of periods is inconsistent in the Optional Hardware section of firststeps.md

 ### Steps to reproduce the problem
visit https://treehouses.io/#!./pages/vi/firststeps.md#Optional_Hardware

 ### Screenshots
![firefox_1WNyB92D7H](https://user-images.githubusercontent.com/3631329/77217328-a2d7c880-6aef-11ea-8ef4-75dc2d4a7ebf.png)

 ### Proposed solution
Add periods to steps that do not have them, or remove periods from the steps that have them to make the grammar formatting consistent (for example, remove periods from steps 3 and 5).

**Comment by LordJashin32** [comment]
Yeah that makes more sense. This is ready to go.

**Comment by dyeh123** [comment]
Yeah I noticed that too. Good suggestion.

**Comment by ali18997** [comment]
Since it's not fixed yet, can I do a pull request for this?
@LordJashin32
