### ISSUE TITLE
Update to SSH page

### ISSUE THREAD

**Issue by jayala-29** [treehouses/treehouses.github.io#466]
### Problem
Some "ssh" terms are not capitalized where they should be.

 ### Steps to reproduce the problem
Go to <https://treehouses.io/#!pages/vi/sshpi.md>

 ### Screenshots
<img width="988" alt="Screen Shot 2020-03-26 at 9 41 48 AM" src="https://user-images.githubusercontent.com/18255250/77672448-2bb69000-6f46-11ea-84e2-1a0007ca74e4.png">

 ### Proposed solution
Capitalize "ssh" where needed

**Comment by LordJashin32** [comment]
Since it's an abbreviation. I think this is better. You can go ahead and pull request these changes when you're able. Cheers.
