### ISSUE TITLE
More resources for using Vagrant

### ISSUE THREAD

**Issue by jayala-29** [treehouses/treehouses.github.io#469]
### Problem
Additional resources for using Vagrant

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="881" alt="Screen Shot 2020-03-26 at 4 52 48 PM" src="https://user-images.githubusercontent.com/18255250/77707433-59212f00-6f82-11ea-9116-0ec790f41943.png">

 ### Proposed solution
Add an extra link under Useful Links

**Comment by LordJashin32** [comment]
Good idea.
