### ISSUE TITLE
Privacy Policy for play store

### ISSUE THREAD

**Issue by dogi** [treehouses/treehouses.github.io#47]
![image](https://user-images.githubusercontent.com/13684059/63197024-b34d2f80-c044-11e9-9702-6b13f146c5d7.png)

**Comment by irisb1701** [comment]
http://freeprivacypolicy.com 

This may be helpful it will generate a privacy policy for the app in compliance with google analytics, ecommerce laws etc..

**Comment by sonAndrew** [comment]
I was also wondering about this. Was this solved?

**Comment by Nida8930** [comment]
This is interesting, I never put any thought into how to create, or the necessity of a privacy policy when publishing an app on the play store.

**Comment by jamjakpa** [comment]
it is very important having a privacy policy , to protect the end user and yourself from the company side .

**Comment by sravya71** [comment]
Having a privacy policy for VI as well can be helpful.
