### ISSUE TITLE
Broken Link on Vagrant page

### ISSUE THREAD

**Issue by jayala-29** [treehouses/treehouses.github.io#471]
### Problem
Broken Link on Vagrant page (under Useful Links)

 ### Steps to reproduce the problem
Click where it says "Other helpful links and videos" 

 ### Screenshots
<img width="881" alt="Screen Shot 2020-03-26 at 4 52 48 PM" src="https://user-images.githubusercontent.com/18255250/77707787-74406e80-6f83-11ea-90cb-8e70a8c4c332.png">

<img width="988" alt="Screen Shot 2020-03-26 at 5 01 52 PM" src="https://user-images.githubusercontent.com/18255250/77707813-84584e00-6f83-11ea-8190-c017536ea0ee.png">

 ### Proposed solution
Remove link from user

**Comment by LordJashin32** [comment]
Nice catch.
