### ISSUE TITLE
`addgithubuser` deprecated

### ISSUE THREAD

**Issue by kjong** [treehouses/treehouses.github.io#475]
### Problem
`sudo treehouses sshkey addgithubuser <yourgithubusername>` has been deprecated.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![Screenshot 2020-03-27 16 25 10](https://user-images.githubusercontent.com/36876018/77808191-a4e9dc00-7047-11ea-933c-37269273c99b.png)

 ### Proposed solution
Should be replaced with `sudo treehouses sshkey github adduser <yourgithubusername>`

**Comment by dyeh123** [comment]
Had this problem as well. Had to use the copy and paste SSH key method. Nice find

**Comment by saurabh-mish** [comment]
Just came across this issue.

**Comment by LordJashin32** [comment]
Yeah we need this gone now.
