### ISSUE TITLE
BalenaEtcher not working

### ISSUE THREAD

**Issue by dyeh123** [treehouses/treehouses.github.io#477]
### Problem
In step 1 section 1, BalenaEtcher gives this error when trying to burn treehouse image onto microSD card with Windows -> "Something went wrong. If it is a compressed image, please check that the archive is not corrupted"

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
Add [Rufus](https://rufus.ie/) as an alternative for Windows users to burn the image. It worked for me.

**Comment by LordJashin32** [comment]
I wouldn't mind in 3 to 10 words extra alternatives for burning. I really like Rufus on Windows when I had it. Etcher works fine for me on linux. There is also other options now like maybe the new one Raspbian made.
