### ISSUE TITLE
Grammar error Step 2

### ISSUE THREAD

**Issue by dyeh123** [treehouses/treehouses.github.io#478]
### Problem
In Step 2, "SSH Tutorial, Add SSH Key to the Raspberry Pi", it says "In the future on SSH login it will ask you for your sshkey passphrase where as before used the default password for pi user "raspberry".
 

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
I believe it is missing "it" after "before" and "where as" should be one word.
So it should end up being:
 "In the future on SSH login it will ask you for your sshkey passphrase whereas before it used the default password for pi user "raspberry".

**Comment by LordJashin32** [comment]
I think this is a good idea. I do think the 'it' there is required. Good job finding this.
