### ISSUE TITLE
Example error Step 5

### ISSUE THREAD

**Issue by dyeh123** [treehouses/treehouses.github.io#479]
### Problem
In "Git Repositories, Configure a Remote Repository for Your Fork", example 4 displays 

> $ git remote -v
origin  https://github.com/username/username.github.io.git (fetch)
origin  https://github.com/username/username.github.io.git (push)
upstream  https://github.com/treehouses/treehouses.github.io (fetch)
upstream  https://github.com/treehouses/treehouses.github.io (push)

This is a little confusing because I got a different result. For upstream I had 

> upstream  https://github.com/treehouses/treehouses.github.io.git (fetch)
upstream  https://github.com/treehouses/treehouses.github.io.git (push)

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
Append "git" to the end of the last two links.

**Comment by LordJashin32** [comment]
This is fantastic find. Good job.

**Comment by dogi** [comment]
@LordJashin32 @dyeh123 both is valid

it depends which of the 2 `git clone` you used:
```
git clone https://github.com/treehouses/treehouses.github.io.git
git clone https://github.com/treehouses/treehouses.github.io
```
