### ISSUE TITLE
Imperative mood clarification

### ISSUE THREAD

**Issue by dyeh123** [treehouses/treehouses.github.io#480]
### Problem
For step 6, "GitHub Issues, Commit Message Style Guide", there could be some clarification on what imperative mood is. Although it is mentioned in the linked article, it would be nice to have a short description of it on the page itself for reference.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution

1. Add a short explanation of what imperative mood is:  eg. "Giving a command"

2. Add a simple example readers can follow: eg. "Fix bug with Y"

**Comment by LordJashin32** [comment]
I agree. Its important to have verbs in there. Imperative is good.
