### ISSUE TITLE
no steps to checksum treehouse.img.gz

### ISSUE THREAD

**Issue by vkabc** [treehouses/treehouses.github.io#500]
### Problem
Under "Setting up your raspberry pi", checksum is provided for downloaded treehouse img.gz but no step is provided to check it

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="953" alt="Screenshot 2020-04-14 at 9 38 13 AM" src="https://user-images.githubusercontent.com/4152386/79176777-be569a80-7e33-11ea-8547-a8b730f113a8.png">

 ### Proposed solution
Have a step 4 that that completes the download with a shasum check. On mac/linux terminal its shasum <location of .img.gz>

**Comment by LordJashin32** [comment]
Maybe we should add this to the download page. This also conflicts with one of @law-lin 's issues. Just gonna mark as ready for now. EDIT. Since this issue was before @law-lin . We should probably do your PR first before his. Cheers.
