### ISSUE TITLE
update pi-setup.md

### ISSUE THREAD

**Issue by vkabc** [treehouses/treehouses.github.io#501]
### Problem
Under Powering on the Raspberry Pi, step 2 is not necessary as treehouses remote app will be used to set up raspberry pi wifi/ssh.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="898" alt="Screenshot 2020-04-14 at 9 55 13 AM" src="https://user-images.githubusercontent.com/4152386/79177699-11315180-7e36-11ea-84d7-496351c77c97.png">

 ### Proposed solution
Remove step 2 to avoid confusion.

**Comment by law-lin** [comment]
This is definitely confusing - I thought I needed an ethernet cable for my RPI to be discoverable via Bluetooth on the next step.

**Comment by LordJashin32** [comment]
I think its good to state the multiple options but keep the preferred way as the way taught. Right now you can connect to the RPi over bluetooth (preferred), ethernet cable (2nd way), (serial)? never tried, direct(usb/monitor/hdmi), and finally (WIFI) which has to be setup through one of the above ways first.
