### ISSUE TITLE
clarify treehouses-remote.md

### ISSUE THREAD

**Issue by vkabc** [treehouses/treehouses.github.io#502]
### Problem
Under treehouses remote , there is a notice that says 2-4 mins when rebooting. More information like flashing yellow light when booting up can be added.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="897" alt="Screenshot 2020-04-14 at 10 53 33 AM" src="https://user-images.githubusercontent.com/4152386/79181113-36c25900-7e3e-11ea-99a9-db630a6fe2b8.png">

 ### Proposed solution
More information like flashing yellow light when booting up and resting red light when done booting up can be added.

**Comment by law-lin** [comment]
There should definitely be some more information provided about the LED indicator on the Raspberry Pi. I waited 10 minutes for my Pi to reboot but then noticed that my Pi was a solid red color which meant it never booted.

**Comment by dogi** [comment]
hmm ... agree we can do more about LEDs
also think the LED you call yellow I call green

**Comment by vkabc** [comment]
How about adding (There should be a flashing yellow/green light when booting up) to the note?

**Comment by saurabh-mish** [comment]
There is actually a red LED **and** a flashing yellow/green LED when it is connected to the power source.

**Comment by warthog16** [comment]
The red LED seems to correspond to the power supply, if there is nothing wrong with the power supply the red LED should be on and stable, whereas the green/yellow LED with ACT labelled next to it should correspond to SD card activity, and it seems it should be stable after a while if there's nothing wrong with your SD card.

**Comment by sydneyaldo** [comment]
On my side, the LED lights stay the same during reboot. I don't think it's a reliable indicator. I might be wrong, however.

**Comment by rohansuri17** [comment]
My led lights stay the same too. I think waiting is enough of an indicator.

**Comment by boomzilla** [comment]
I'd assign myself to this task, but I think one has to be an admin to do assignments. Should I wait for confirmation that no one else is going to do this before working on anything? Or, can I just dive straight into working, and do a PR whenever? Regarding the reboot sequence itself, the red LED (labelled PWR in small letters on the circuit board) will briefly wink out, before coming back on, indicating it powered off, and is not again powered. The green/yellow LED (labelled ACT in small letters on the circuit board) indicates the MicroSD card is being read (so, it's like a HDD read light in a desktop computer). Basically, once the R-Pi has powered back on, it will blink rapidly at first, indicating it is doing the startup initialization, before beginning to blink more slowly once the system has loaded. My R-Pi (version 4) is able to reboot in under a minute, but I don't know if other types of R-Pis take longer, or if loading a different disk images take longer to load. **Besides improving the write-up, I'd be happy to take videos (of the reboot sequence) or photos (of the small letters printed on the board) for extra documentation**.

**Comment by vkabc** [comment]
Hi Ian Ruotsala, looking forward to it!
