### ISSUE TITLE
clarify githubandmarkdown.md

### ISSUE THREAD

**Issue by vkabc** [treehouses/treehouses.github.io#503]
### Problem
Under creating new md file for your profile page step 4,full example is not provided. 

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="866" alt="Screenshot 2020-04-14 at 11 01 16 AM" src="https://user-images.githubusercontent.com/4152386/79181686-8e14f900-7e3f-11ea-9618-32f30bead705.png">

 ### Proposed solution
Add username.md example

**Comment by LordJashin32** [comment]
Yeah, maybe in quotations or parenthesis would be good.
