### ISSUE TITLE
Update image downloads link for latest version in pi-setup.md

### ISSUE THREAD

**Issue by law-lin** [treehouses/treehouses.github.io#505]
### Problem
As of 4/14/20, the image download link in pi-setup.md does not have the latest image version 124. Instead, it links to a page with the latest version being 122. 

 ### Steps to reproduce the problem
Visit "Setting up your Raspberry Pi" under "Step 1 - Installing and finding your Raspberry Pi" or https://treehouses.io/#!./pages/vi/pi-setup.md. The link http://download.treehouses.io/ is in step 2 of "Preparing the image".

 ### Screenshots

The link here
![image](https://user-images.githubusercontent.com/35390215/79287904-36a07880-7e93-11ea-81bb-c8726b099f6a.png)

leads to this download page:
![image](https://user-images.githubusercontent.com/35390215/79287869-1ec8f480-7e93-11ea-8a59-76907501babb.png)

which is outdated as the download.md page shows this:
![image](https://user-images.githubusercontent.com/35390215/79287915-3dc78680-7e93-11ea-8aaf-2e2800ce371a.png)

 ### Proposed solution
Change step 2 of "Preparing the image" to

2. Go to https://treehouses.io/#!pages/download.md

and change step 3 to

3. Click on **Latest Image** to download the image

**Comment by LordJashin32** [comment]
Excellent idea
