### ISSUE TITLE
Consistent Bluetooth and Raspberry Pi disconnects

### ISSUE THREAD

**Issue by law-lin** [treehouses/treehouses.github.io#506]
### Problem
For some people, they may have an unstable connection between their Android device and their Raspberry Pi. 

 ### Steps to reproduce the problem
I used a OnePlus 6T phone with 8GB RAM, Android version 10, and OxygenOS version 10.3.2. I used treehouses remote to connect to my Raspberry Pi via Bluetooth. There was a connection for the first 20 seconds or so, then it would disconnect. This was consistent for every attempted connection.

 ### Proposed solution
For me, I just kept reconnecting to my RPI and entered the terminal commands.  This likely isn't the ideal fix for my problem, but it worked in the end.

I'm not quite sure how to solve these constant disconnects, but a **NOTE** could be added that states:
If you are experiencing frequent Bluetooth disconnects, keep on trying to "Connect to RPI" and enter the commands into the terminal.

**Comment by LordJashin32** [comment]
Related: https://github.com/treehouses/remote/pull/715 , https://github.com/treehouses/control/pull/17 , 
https://github.com/treehouses/control/issues/16

Thanks for posting this. I am also having problems. I've been working on this issue for the past week or so. Hopefully soon we will be able to fix these issues.

**Comment by LordJashin32** [comment]
You can also add a note as well. Good idea. Cheers. marked this ready.

**Comment by sarahrams** [comment]
I am having similar issues. I cannot connect to Raspberry Pi all the time.
The first time I had to format my micro SD card and flashed it again. I was then able to connect again to RPI. However, I would not say that this is what **truly** resolved my problem.

**Comment by LordJashin32** [comment]
> I am having similar issues. I cannot connect to Raspberry Pi all the time.
> The first time I had to format my micro SD card and flashed it again. I was then able to connect again to RPI. However, I would not say that this is what **truly** resolved my problem.

Try the new image '128'. The issues with bluetooth were fixed upstream by Debian. 
If you get a boot panic or anything with the SD card. You just need to flash it again. Sometimes the burn might not burn the image correctly. Just like with any operating system. 

Once you get connected over bluetooth you should be able to setup the Pi to connect to your Wifi.
