### ISSUE TITLE
Update latest treehouses image link in nextcloud-tor.md

### ISSUE THREAD

**Issue by law-lin** [treehouses/treehouses.github.io#507]
### Problem
As of 4/14/20, the image download link in nextcloud-tor.md does not have the latest image version 124. Instead, it links to a page with the latest version being 122. 

 ### Steps to reproduce the problem
Visit "Step 7 - Nextcloud with Tor Tutorial" The link http://download.treehouses.io/ is under "Prepare Treehouse images".

 ### Screenshots

The link here
![image](https://user-images.githubusercontent.com/35390215/79291083-b8949f80-7e9b-11ea-83ab-9550a7836f7b.png)

leads to this download page:
![image](https://user-images.githubusercontent.com/35390215/79287869-1ec8f480-7e93-11ea-8a59-76907501babb.png)

which is outdated as the download.md page shows this:
![image](https://user-images.githubusercontent.com/35390215/79287915-3dc78680-7e93-11ea-8aaf-2e2800ce371a.png)

 ### Proposed solution
Change the treehouses image link in nextcloud-tor.md to: https://treehouses.io/#!pages/download.md

**Comment by LordJashin32** [comment]
Similar to pi-setup.md issue you made. Great.
