### ISSUE TITLE
Improper letter cases in sshpi.md

### ISSUE THREAD

**Issue by law-lin** [treehouses/treehouses.github.io#515]
### Problem
Linux and macOS have improper letter cases in `sshpi.md`.

 ### Steps to reproduce the problem
Go to https://treehouses.io/#!./pages/vi/sshpi.md

 ### Screenshots
![image](https://user-images.githubusercontent.com/35390215/79410713-26f66200-7f6f-11ea-96de-5c972561cd57.png)

 ### Proposed solution

Change `linux/macosx` to `Linux/macOS`

**Comment by darthnoward** [comment]
Or even better, use the full name GNU/Linux, as i quote Richard Stallman, *"Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX"*
