### ISSUE TITLE
Spacing in nextcloud-tor.md

### ISSUE THREAD

**Issue by law-lin** [treehouses/treehouses.github.io#516]
### Problem
There is a no space after the first sentence's period and the start of the second sentence.

 ### Steps to reproduce the problem
Go to https://treehouses.io/#!./pages/vi/nextcloud-tor.md

 ### Screenshots
![image](https://user-images.githubusercontent.com/35390215/79411067-ea773600-7f6f-11ea-9cc7-70b78daba3d5.png)

 ### Proposed solution
Add a space after the period in the first sentence. It should look like this:

Replace `username` with your Github username,and replace `wifiname` and `wifipassword` with your wifi name and password that you are connecting. Save the file, and safely eject the SD card.

**Comment by vkabc** [comment]
Nice find.
