### ISSUE TITLE
Grammatical Errors in firststeps.md

### ISSUE THREAD

**Issue by piyush-sharma** [treehouses/treehouses.github.io#524]
### Problem
There are a few grammatical errors in firststeps.md.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
I am proposing to fix the following grammatical errors where I have outlined them in the format [with error] -> [without error].

on places such as Amazon, Ebay etc... ->  on places such as Amazon, eBay, etc...

The following are required hardware components -> The following are the required hardware components

However as part of the Systems team, you will need -> However, as part of the Systems team, you will need

Also include the -> Also, include the

In this step we will adopt -> In this step, we will adopt

work on the issue, before you start to work on it. -> work on the issue before you start to work on it.

**Comment by darthnoward** [comment]
Nice find. A lot of points

**Comment by LordJashin32** [comment]
Nice
