### ISSUE TITLE
Incomplete category of operating systems in vagranttutorial.md

### ISSUE THREAD

**Issue by darthnoward** [treehouses/treehouses.github.io#527]
### Problem
There is a case where operation systems category is inappropriate.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![image](https://user-images.githubusercontent.com/51189233/79682941-06712500-8259-11ea-8fac-c540d1d90c55.png)

 ### Proposed solution
change
```markdown
#### macOS or Ubuntu -Terminal
Normally we use Terminal to interact with Vagrant CLI
```
to
```markdown
#### macOS or GNU\Linux -Terminal
Normally we use a terminal emulator to interact with Vagrant CLI
```

**Comment by piyush-sharma** [comment]
I agree. Good catch.

**Comment by LordJashin32** [comment]
Being more vague is fine but theoretically if you say GNU\Linux you would have to cover a whole lot of different package managers. But i guess its fine people can lookup non Debian resources.

**Comment by saurabh-mish** [comment]
Or perhaps to:

### *NIX 
Normally we use a terminal emulator to interact with Vagrant CLI
