### ISSUE TITLE
Many keys found through steps that create confusion of what SSH key is.

### ISSUE THREAD

**Issue by sarahrams** [treehouses/treehouses.github.io#534]
### Problem
I run across many types of keys and I confused **_SSH key_** with **_ECDSA key fingerprint_** and **_Agent pid XXX_**.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![SSH_keys_5](https://user-images.githubusercontent.com/62920905/79980109-71884a80-8457-11ea-97bc-5a83806445e8.jpg)

![IMG_20200420_190945](https://user-images.githubusercontent.com/62920905/79980720-65e95380-8458-11ea-85cc-651b74081b8f.jpg)

 ### Proposed solution
Detailed explanation of what each of the above-mentioned key is, and which one to consider for which step. Provide SSH key format in the instructions in order to avoid confusion.

**Comment by LordJashin32** [comment]
The part after == is the name of the key. Which is obligatory afaik (as far as i know). Not sure on this issue.
