### ISSUE TITLE
Modifications needed on pi-setup.md

### ISSUE THREAD

**Issue by Srobin22** [treehouses/treehouses.github.io#540]
### Problem
Few modifications needed on the pi-setup.md
+ There is no Latest Image option on the download.md page. Rather, we have Beta Image option linking to the latest image link.
+ The note incorrectly indicates that the latest image will be at the bottom of the download page. As there is no image download link option at the bottom of download.md page. 
 ### Steps to Reproduce the Problem
N/A
 ### Screenshots
![image](https://user-images.githubusercontent.com/36524877/80260028-f7bdb000-8654-11ea-988b-b8b69c49fdc4.png)
![image](https://user-images.githubusercontent.com/36524877/80260052-086e2600-8655-11ea-9524-23331810264f.png)

 ### Proposed solution
+ We can change the step 3 from `Latest Image` to `Beta Image`
+ We can get rid of the Note

**Comment by LordJashin32** [comment]
Looks like a great issue.

https://treehouses.io/#!./pages/vi/pi-setup.md

**Comment by saurabh-mish** [comment]
Nice point @Srobin22 , I had also mentioned this in the chat a few days back.
