### ISSUE TITLE
Unable to SSH to Raspberry Pi

### ISSUE THREAD

**Issue by saurabh-mish** [treehouses/treehouses.github.io#541]
**Problem**

In step 1, after [completing section 1, section 2](https://drive.google.com/open?id=10DBQ5aZgTGxzHdRFJD3hbfukFHKb-_Tq), and [section 3](https://drive.google.com/open?id=1082lJcz2u1rtZ9q47OpNsER6eUeAc1jl) I am not able to proceed with step 2.

When I try to SSH and ping, I'm getting the errors:-

**SSH Error**:

```
saura8h@Saurabh-MacBookPro .ssh % 
saura8h@Saurabh-MacBookPro .ssh % ssh pi@192.168.43.252     
ssh: connect to host 192.168.43.252 port 22: Operation timed out
saura8h@Saurabh-MacBookPro .ssh % 
saura8h@Saurabh-MacBookPro .ssh % 
```

**Ping Response**:

```
saura8h@Saurabh-MacBookPro .ssh % 
saura8h@Saurabh-MacBookPro .ssh % 
saura8h@Saurabh-MacBookPro .ssh % ping 192.168.43.252
PING 192.168.43.252 (192.168.43.252): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
Request timeout for icmp_seq 12
Request timeout for icmp_seq 13
Request timeout for icmp_seq 14
Request timeout for icmp_seq 15
Request timeout for icmp_seq 16
Request timeout for icmp_seq 17
Request timeout for icmp_seq 18
Request timeout for icmp_seq 19
Request timeout for icmp_seq 20
^C
--- 192.168.43.252 ping statistics ---
22 packets transmitted, 0 packets received, 100.0% packet loss
saura8h@Saurabh-MacBookPro .ssh % 
saura8h@Saurabh-MacBookPro .ssh % 
```

**Steps to Reproduce**:

1. Connect Android phone to WiFi network of type WPA-EAP (WPA Enterprise PEAP)

2. Create mobile hotspot of type WPA2 from the Android settings applications.

3. [Complete step 1](https://treehouses.io/#!./pages/vi/treehouses-remote.md)

4. [Verify method 1 of step 1 section 3](https://treehouses.io/#!./pages/vi/find-pi.md) **WORKS (section 3 screenshot above)**

5. [Verify method 2 of step 1 section 3](https://treehouses.io/#!./pages/vi/find-pi.md) **DOES NOT WORK (Ping Response above)**

6. SSH to raspberry pi
**DOES NOT WORK - times out after a minute or so. (SSH Error above)**

**Additional Observation(s)**:

+ Replaced the first two steps in the previous section with the below:

1. Switch off Android WiFi, and switch on mobile data

2. Switch on mobile hotspot to share mobile's data connection.

+ Using the latest treehouse beta image

**Comment by saura8h** [comment]
Complete information added.

**Comment by saurabh-mish** [comment]
More observations added.

**Comment by LordJashin32** [comment]
Sorry for late reply on this. I don't think the Raspberry Pi can connect to WPA-EAP (WPA Enterprise PEAP) network. However an Ethernet cord to the Pi should connect it to the network (after a reboot). 

In the case of hotspot on the Raspberry Pi. I had problems with this myself in the past. The way I got it to work was. I had to get the IP address of the RPi, and on the android device I would connect to the hotspot ESSID (whatever you named it) and I would hit advanced options and next to ip address I would put the Pi's IP. 

You only need to do that if you get connection problems with the hotspot though. 
Umm. You might be able to manually connect to wifi on the RPi, without use of the treehouses commands but with the desktop on the Pi. Please remember that in order to SSH to the Pi, you need to have a direct connection to the Pi, or the Pi needs to be connected to the router.

**Comment by saurabh-mish** [comment]
Hey @LordJashin32 , I've been trying to do something close to what you've mentioned in the second paragraph. I will retry and upload the images by today.

**Comment by saurabh-mish** [comment]
@LordJashin32 can you please let me know what you're configuring in the network section ?

I'm not able to see advanced options in either of the following:-
WiFi
Hotspot
Bridge
Ethernet

**Comment by saura8h** [comment]
Just SSH'd !!! Posting a workaround and closing the issue

**Comment by saurabh-mish** [comment]
Steps taken to solve the `Operation Timed Out` issue:

+ Reset network profile (`treehouses default network`)

+ Ensure mobile has mobile data and mobile hostspot enabled. **WiFi should be turned off**

+ In the treehouses remote app (Bluetooth should be on), run command `treehouses bridge "android_hotspot" treehouses "mobile_hotspot_password"` to connect to the Android mobile hotspot.

+ Reboot the Pi. It will automatically connect to the hotspot set up previously.

+ Connect your desktop/laptop to the same mobile hotspot as the one configured for the Pi.
    **NOTE**: In your Android mobile hotspot settings, verify that there are two devices (`treehouses` and your laptop/desktop)

+ Check the IP address of the Pi from the Android app with `treehouses networkmode info`

+ Now from your desktop/laptop verify that you're able to ping the Pi with `ping <IP_address_of_Pi>`.
    **NOTE**: This is method 2 on [this webpage](https://treehouses.io/#!./pages/vi/find-pi.md)

+ Continue with [step 2](https://treehouses.io/#!./pages/vi/sshpi.md)
