### ISSUE TITLE
Adding Output of "treehouses" Commands

### ISSUE THREAD

**Issue by saurabh-mish** [treehouses/treehouses.github.io#543]
### Problem
In [Step 1 Section 2](https://treehouses.io/#!./pages/vi/treehouses-remote.md), output of the below treehouses commands can be added to provide more clarity on command execution:

`treehouses detectrpi`

`treehouses default network`

`treehouses bridge "wifiname" treehouses "wifipassword"`

 ### Steps to reproduce the problem
Follow along Step 1 Section 2

 ### Screenshots
<img width="853" alt="image" src="https://user-images.githubusercontent.com/52619598/80269249-c51ab400-8662-11ea-8580-0156e0b6e3a9.png">

 ### Proposed solution
Below point 11, a screenshot containing the outputs of the commands can be added:

![image](https://user-images.githubusercontent.com/52619598/80269285-2f335900-8663-11ea-9454-5f101f8739b7.png)

**Comment by LordJashin32** [comment]
Sure but make sure the picture isn't too large.
