### ISSUE TITLE
Discrepancy in Section and Page Title

### ISSUE THREAD

**Issue by saurabh-mish** [treehouses/treehouses.github.io#544]
### Problem
On the ["First Steps" Page](https://treehouses.io/#!pages/vi/firststeps.md), section 1 under step 1 is titled "Starting up your Raspberry Pi".

But on clicking this link, the title of the linked page is "Setting up your Raspberry Pi"

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="853" alt="image" src="https://user-images.githubusercontent.com/52619598/80269623-327c1400-8666-11ea-94d0-369b07bb42a8.png">

<img width="893" alt="image" src="https://user-images.githubusercontent.com/52619598/80269628-390a8b80-8666-11ea-8090-9a5805666f1b.png">

 ### Proposed solution
Rename "Starting up your Raspberry Pi" to "Setting up your Raspberry Pi" on "[First Steps](https://treehouses.io/#!pages/vi/firststeps.md)" page.

**Comment by jayala-29** [comment]
Never noticed that, nice catch
