### ISSUE TITLE
Incorrect Section Heading in Github Issues Page

### ISSUE THREAD

**Issue by saurabh-mish** [treehouses/treehouses.github.io#546]
### Problem
In the [GitHub Issues page](https://treehouses.io/#!./pages/vi/github-issues.md), the section "Create a New Branch" is wrongly labeled. 

The heading should instead be "Sync Your Fork" because the four commands below have been listed in detail in the previous step ([Step 5](https://treehouses.io/#!./pages/vi/gitrepositories.md)).

The heading "Create a New Branch" should come after the four commands.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="893" alt="image" src="https://user-images.githubusercontent.com/52619598/80272253-7f6ae500-867c-11ea-98c7-9e600a10f187.png">

 ### Proposed solution
Rename "Create a New Branch" to "Sync Your Fork"

**Comment by piyush-sharma** [comment]
Makes sense 👍. For the proposed solution, let's rename "Create a New Branch" to "Sync Your Fork" just as you said but then we also include the "Create a New Branch" heading right after the four commands.

**Comment by saurabh-mish** [comment]
Yes Piyush, I've mentioned that "Create a New Branch" **should** come after the four commands in the last part of the Problem section.

**Comment by piyush-sharma** [comment]
What I meant to say was add that part to the proposed solution section as well so that it's more clear. Otherwise looks good!

**Comment by LordJashin32** [comment]
I will approve.

**Comment by saurabh-mish** [comment]
Done.
@piyush-sharma Checkout #553

**Comment by saurabh-mish** [comment]
#553 fixed this
