### ISSUE TITLE
Commands to Create a Branch Are Not Clear

### ISSUE THREAD

**Issue by saurabh-mish** [treehouses/treehouses.github.io#547]
### Problem
In the [GitHub Issues page](https://treehouses.io/#!./pages/vi/github-issues.md), commands to create a branch are not clear (and somewhat confusing)

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="893" alt="image" src="https://user-images.githubusercontent.com/52619598/80272447-4cc1ec00-867e-11ea-8b3c-2d0ff6cc9b5d.png">

 ### Proposed solution

### Create a New Branch

+ Check for existing branches with `git branch`
**NOTE**: The branch which is active will have a `*` before its name

+ Create a new branch for the issue / fix with `git branch branch-name`

+ Switch to the newly created branch with `git checkout branch-name`

**Optional**: Confirm that you will be starting work on the newly created branch by again executing `git branch` and check for `*` before `branch-name`

### Reason

This provides better continuity from the previously executed four commands for syncing the fork.

**Comment by darthnoward** [comment]
Agreed, this avoids switching between github and terminal.

**Comment by LordJashin32** [comment]
Looks good.
