### ISSUE TITLE
Comprehensive Information to Delete a Branch

### ISSUE THREAD

**Issue by saurabh-mish** [treehouses/treehouses.github.io#549]
### Problem
In the GitHub Issues page, bullet points 2 and 3 under "Deleting the Branch" are not clear.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="893" alt="Screen Shot 2020-04-25 at 12 29 42 AM" src="https://user-images.githubusercontent.com/52619598/80273974-e3e17080-868b-11ea-91cf-78707c555a3e.png">

 ### Proposed solution

1. Switch to the master branch using `git checkout master` as you cannot be **on** the branch you want to delete.

2. Delete local branch using `git branch -d branch-name`.

3. Delete remote branch using `git push origin --delete branch-name`.

**Comment by LordJashin32** [comment]
Sure. Marking ready.
