### ISSUE TITLE
Find a better way than Default Username in Prompt Box

### ISSUE THREAD

**Issue by piyush-sharma** [treehouses/treehouses.github.io#550]
### Problem
There is an unnecessary default username in the prompt box when going to track your progress. I believe this was done during development to test but was forgotten about. 

 ### Steps to reproduce the problem
Go to the [Track Progress page](https://treehouses.io/#!pages/vi/trackprogress.md) and click the blue button.

 ### Screenshots
![image](https://user-images.githubusercontent.com/25667615/80299958-abfb2b80-8766-11ea-8873-d18eeabeffc9.png)

 ### Proposed solution
Change the initial value of the variable `user` in trackprogress.md from "dogi" to "Replace me with your GitHub username".

**Comment by LordJashin32** [comment]
Sure.

**Comment by darthnoward** [comment]
I totally agree, this will save some time and avoid some confusion.

**Comment by dogi** [comment]
@piyush-sharma our initial problem was that when empty some aspiring virtual interns was not able to get it working, so we came up with this ;)


> I totally agree, this will save some time and avoid some confusion.

@darthnoward what I mean there is confusion no matter what

**Comment by saurabh-mish** [comment]
I think leaving it blank would also cause confusion.

Using the current username may be causing confusion, because the display name and username are both "dogi".

We could use a default username like @LordJashin32 because it is different from the display name "Tristan".
This would make it easier for people to figure out which name has to be entered in the prompt.

**Comment by piyush-sharma** [comment]
Perhaps we could rename the prompt from "Please enter username" to "Please enter your GitHub username". That should clear any confusion.

**Comment by piyush-sharma** [comment]
Added a new commit to the pull request based on @dogi 's suggestion. Please review it. Thanks.

**Comment by ali18997** [comment]
Instead of any specific username, the field can be filled with text "Your username here (usually the same as your GitHub username)"

**Comment by piyush-sharma** [comment]
Yes, I made that change. I updated the issue and pull request descriptions right now.
