### ISSUE TITLE
update newfeature.md

### ISSUE THREAD

**Issue by law-lin** [treehouses/treehouses.github.io#551]
### Problem
Under Step 0 - Vim, step 5, you need to press the Esc key, type :wq and then press Enter to save and exit.

 ### Steps to reproduce the problem
Go to https://treehouses.io/#!./pages/blog/20190831-newfeature.md

 ### Screenshots
N/A

 ### Proposed solution
Change Step 0 - Vim, step 5 to "Copy the below script, press Esc, type :wq, and press Enter to save it and exit."

**Comment by jayala-29** [comment]
sounds good
