### ISSUE TITLE
Unnecessary bullet points in firststep.md

### ISSUE THREAD

**Issue by darthnoward** [treehouses/treehouses.github.io#558]
### Problem
There are a few places in firststep.md where bullet points are unnecessary. 
A single bullet point is of no necessity, since there is no other equivalent point to list along with.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![image](https://user-images.githubusercontent.com/51189233/80496690-252f9400-899c-11ea-82e8-d7d1647c2197.png)

 ### Proposed solution
Change the single bullet point line to other syntax such as quote, in this way, it serves the purpose of checkpoint and emphasis
![image](https://user-images.githubusercontent.com/51189233/80497059-8a838500-899c-11ea-8ed2-d71822a0dc26.png)

**Comment by law-lin** [comment]
This looks much nicer.

**Comment by LordJashin32** [comment]
Okay. Sure. Let's give it a go.
