### ISSUE TITLE
Treehouse Image Download Link in Nextcloud Section Not Working

### ISSUE THREAD

**Issue by saurabh-mish** [treehouses/treehouses.github.io#561]
### Problem
In the **Nextcloud with Tor Tutorial** webpage, the hyperlink from "here" in the section "Prepare Treehouses image" does not work.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="905" alt="Screen Shot 2020-04-28 at 5 21 27 PM" src="https://user-images.githubusercontent.com/52619598/80550384-cc003a00-8974-11ea-9474-020c686f4bdc.png">

<img width="1792" alt="Screen Shot 2020-04-28 at 5 21 53 PM" src="https://user-images.githubusercontent.com/52619598/80550388-d1f61b00-8974-11ea-9571-f5606d31c512.png">

 ### Proposed solution
"here" should be linked to this webpage: https://treehouses.io/#!pages/download.md

**Comment by LordJashin32** [comment]
Tested it and confirmed it wasn't working. Marked ready. Cheers.
