### ISSUE TITLE
Unclear description for android requirement

### ISSUE THREAD

**Issue by darthnoward** [treehouses/treehouses.github.io#563]
### Problem
The requirement for android operating system is unclear.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![image](https://user-images.githubusercontent.com/51189233/80624344-20431100-8a7e-11ea-88c7-aee16e69bd27.png)

 ### Proposed solution
As suggested below:

![image](https://user-images.githubusercontent.com/51189233/80624169-e40fb080-8a7d-11ea-8b76-3dcf91552a65.png)

**Comment by LordJashin32** [comment]
I wouldn't say its unclear but that it doesn't look nice. This is good to go marking ready.
