### ISSUE TITLE
"Adding a New Feature" blog post outdated information

### ISSUE THREAD

**Issue by kjong** [treehouses/treehouses.github.io#565]
### Problem
Step 3 of the "Adding a New Feature" blog post describes editing `cli.sh` to manually include the new module, which is no longer necessary.

Step 3 also includes editing `_treehouses` to add tab completion for the new module, which is still required, but the method of doing so is outdated.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
Remove the `cli.sh` section.

Update the `_treehouses` section.

**Comment by law-lin** [comment]
Was going to make the exact issue, nice
