### ISSUE TITLE
More specifications about SSH Key issue 

### ISSUE THREAD

**Issue by sarahrams** [treehouses/treehouses.github.io#570]
### Problem
I run across many types of keys: **_SSH key_**, **_ECDSA key fingerprint_** and **_Agent pid XXX_**, without really understanding the use of all them. I was even confused trying to figure out which one is SSH key.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![SSH_keys_5](https://user-images.githubusercontent.com/62920905/79980109-71884a80-8457-11ea-97bc-5a83806445e8.jpg)

![IMG_20200420_190945](https://user-images.githubusercontent.com/62920905/79980720-65e95380-8458-11ea-85cc-651b74081b8f.jpg)

 ### Proposed solution
Detailed explanations of what each of the above-mentioned key is, and which one to consider for which step. Provide SSH key format (image) in the instructions in order to avoid confusion.

**Comment by jayala-29** [comment]
I would be curious to see what you would write :)  nice idea

**Comment by kjong** [comment]
Looks like this is the same issue as #534. Please consider closing one of the two.

**Comment by jayala-29** [comment]
@kjong  nice catch, @sarahrams check out the comment above

**Comment by sarahrams** [comment]
> Looks like this is the same issue as #534. Please consider closing one of the two.

Yes. I did. Thanks

**Comment by warthog16** [comment]
So the SSH key seems to be the RSA key, or at least the public part of it, whereas the Agent PID and ECDSA fingerprint seem to be identifiers for your SSH connection and not keys themselves
