### ISSUE TITLE
Confusion in getting Global Status through Vagrant Tutorial

### ISSUE THREAD

**Issue by warthog16** [treehouses/treehouses.github.io#573]
### Problem
In the Vagrant Tutorial in the First Steps, it's mentioned to check the state of active Vagrant environments by using the command ` vagrant global-status ` followed by a screenshot of a command line showing the active Vagrant environment from the cloned cli repository. However, when I was following the steps, it initially showed nothing as active until I first ran ` vagrant up ` in order to get the environment running and then I had the cli environment show up as in the screenshot on the tutorial page, but the ` vagrant up ` command as well as other Vagrant commands are only mentioned after this section. 

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![Screen Shot](https://user-images.githubusercontent.com/45441785/80895175-f83af400-8caf-11ea-839a-5b5becedc234.png)

 ### Proposed solution
Perhaps add "If no environments show up as active, use the command ` vagrant up ` and try again. " in the section under **Global Status** before the Vagrant commands are introduced.

**Comment by LordJashin32** [comment]
Sounds good. maybe we reorder the sections?
