### ISSUE TITLE
Periods inconsistent under Hardware Requirements in firststeps.md

### ISSUE THREAD

**Issue by ali18997** [treehouses/treehouses.github.io#574]
### Problem
The placement of periods is inconsistent in the Hardware requirements section of firststeps.md under the first bullet point of Raspberry Pi 4, the 2 sub-bullets have a period in first but missing in the second. 

 ### Steps to reproduce the problem
visit https://treehouses.io/#!./pages/vi/firststeps.md#Pre-Requisites

 ### Screenshots
<img width="363" alt="Capture" src="https://user-images.githubusercontent.com/20432955/80916592-a635b500-8d27-11ea-9245-c1cfe6c8efae.PNG">

 ### Proposed solution
Remove the period from the first bullet as the rest of the bullets throughout this section don't have a period.

**Comment by law-lin** [comment]
Good catch.
