### ISSUE TITLE
Computer Terminal or Treehouses Remote Terminal not Specified

### ISSUE THREAD

**Issue by warthog16** [treehouses/treehouses.github.io#580]
### Problem
In the Finding Your Pi section, under Method 2, Pinging your Raspberry Pi, when terminal is mentioned, it isn't specified that what is meant is your computer or OS terminal, not the Treehouses Remote Terminal which could be confusing as the command doesn't work in Treehouses Remote. 

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![](https://user-images.githubusercontent.com/45441785/81524848-c44f7680-9320-11ea-9c55-a59f101b342c.png)

 ### Proposed solution
Mention that it is the computer terminal. Eg., "in your computer terminal" instead of "in your terminal" since the Treehouses Remote terminal is also referred to as 'terminal' through the tutorial.

**Comment by jayala-29** [comment]
sounds good, clarity helps :)
