### ISSUE TITLE
Adding Vi/Vim Cheatsheet to the First Steps Page

### ISSUE THREAD

**Issue by sydneyaldo** [treehouses/treehouses.github.io#593]
### Problem
Instead of the full tutorial, providing a link to Vi/Vim **Cheatsheets** can be really **useful** for newcomers/future interns

 ### Steps to reproduce the problem
Visit [https://treehouses.io/#!pages/vi/firststeps.md](https://treehouses.io/#!pages/vi/firststeps.md)

 ### Screenshots
![image](https://user-images.githubusercontent.com/58101855/81951616-4b406f80-95fd-11ea-9000-3b8921f2bb4e.png)

 ### Proposed solution
Adding Vi/Vim Cheatsheet into the **First Steps** page

**Comment by LordJashin32** [comment]
Yes, either there or to here https://treehouses.io/#!pages/vi/faq.md
approved

**Comment by sydneyaldo** [comment]
Okay, will work on it soon!
