### ISSUE TITLE
How to add remote repository to local repository

### ISSUE THREAD

**Issue by sarahrams** [treehouses/treehouses.github.io#601]
### Problem
The instructions only tell how to list an existing repository without showing how to add one

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
In order to assign the remote origin to GitHub account, first run
**$ git remote add origin https://github.com/username/username.github.io.git**
Then, we can list them with **$ git remote -v**

**Comment by LordJashin32** [comment]
If you feel it will get merged then go for it. Not entirely sure but I'll approve so you can try. Cheers.
