### ISSUE TITLE
Checking the location (the URL) of the repository

### ISSUE THREAD

**Issue by sarahrams** [treehouses/treehouses.github.io#602]
### Problem
After adding the remote repository, we  may need to verify where it lives.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
Run command **$ cat .git/config** to verify all the configurations of our remote repository.

**Comment by LordJashin32** [comment]
I guess if it makes the coder sure about it. I think you have to be in the folder you cloned too. I'll approve for now. Cheers.
