### ISSUE TITLE
Verify all the information after setting email address per local repository 

### ISSUE THREAD

**Issue by sarahrams** [treehouses/treehouses.github.io#603]
### Problem
Instructions are not provided on how to check information after global setting

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
Providing written instructions on how to set the user name and email address in Git
Then, running **$ git config --list** to check all the information + configurations

**Comment by LordJashin32** [comment]
Good idea. Approved.
