### ISSUE TITLE
Adding more information to FAQ related to International Students in US

### ISSUE THREAD

**Issue by ali18997** [treehouses/treehouses.github.io#605]
### Problem
International Students in US on F-1 visa want to know if they have to apply for CPT authorization for this internship or not which is not answered properly by the FAQs.

 ### Steps to reproduce the problem
visit Q7 in https://treehouses.io/#!./pages/vi/faq.md#Helpful_Links

 ### Screenshots
<img width="659" alt="Capture" src="https://user-images.githubusercontent.com/20432955/82130303-2af8e800-9798-11ea-8ec6-d9374e74bd45.PNG">

 ### Proposed solution
Add this link in this answer for further information:
https://isso.columbia.edu/content/unpaid-internships-and-volunteering

**Comment by LordJashin32** [comment]
Go for it. Idk if @dogi will add it or not though. But worth a shot.

**Comment by sarahrams** [comment]
It would great to add more information concerning international students, as many may not be aware of what should be done, especially those aspiring to work off-campus for the first time.

**Comment by ali18997** [comment]
Yes, there is always a bit of confusion about whether unpaid internships like these require proper CPT permissions or not.
