### ISSUE TITLE
Links provided in FAQs 3 and 4 do not work

### ISSUE THREAD

**Issue by ali18997** [treehouses/treehouses.github.io#606]
### Problem
The links to internship listing and gitter chat in the FAQs are probably old and do not work anymore.

 ### Steps to reproduce the problem
visit Q3 and Q4 here: https://treehouses.io/#!./pages/vi/faq.md#Helpful_Links

 ### Screenshots
<img width="657" alt="Capture" src="https://user-images.githubusercontent.com/20432955/82130399-05b8a980-9799-11ea-930c-f2d9b67ad907.PNG">

![screencapture-indeed-cmp-Open-Learning-Exchange-Inc-jobs-2020-05-16-17_17_14](https://user-images.githubusercontent.com/20432955/82130416-1ff28780-9799-11ea-8f34-b6cd6d705e6f.png)

![screencapture-gitter-im-open-learning-exchange-treehouses-Lobby-2020-05-16-17_17_55](https://user-images.githubusercontent.com/20432955/82130426-3567b180-9799-11ea-90dd-abdd991d9373.png)

 ### Proposed solution
Remove the links or update them.

**Comment by LordJashin32** [comment]
Nice catch. Approved.
