### ISSUE TITLE
Adding progress page link in the relevant FAQ

### ISSUE THREAD

**Issue by ali18997** [treehouses/treehouses.github.io#607]
### Problem
The FAQ Q8 answers how many PRs and Issues are needed to be completed but does not provide a way to check the progress. The only way someone would know about the progress page is if they read carefully the first steps page and find it mentioned there only once. How about we add the link to the progress page in the answer to this question as well?

 ### Steps to reproduce the problem
visit Q8 in https://treehouses.io/#!./pages/vi/faq.md#Helpful_Links

 ### Screenshots
<img width="648" alt="Capture" src="https://user-images.githubusercontent.com/20432955/82130521-1d446200-979a-11ea-9c3a-637f48682a0a.PNG">

 ### Proposed solution
The link to the progress page can be added to the answer:
https://treehouses.io/#!./pages/vi/trackprogress.md

**Comment by LordJashin32** [comment]
Sure. Approved.
