### ISSUE TITLE
treehouses remote testing link vs production

### ISSUE THREAD

**Issue by dogi** [treehouses/treehouses.github.io#61]
https://play.google.com/apps/testing/io.treehouses.remote
-> testing

https://play.google.com/store/apps/details?id=io.treehouses.remote
-> production

we want VI to use testing version

**Comment by vmnet8** [comment]
What's VI?

**Comment by vmnet8** [comment]
VI is virtual intern? Why  do  VIs use  testing version?

**Comment by dogi** [comment]
> VI is virtual intern? Why do VIs use testing version?

yes

virtual intern are suppose to help while [dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)

**Comment by dogi** [comment]
so basically aspiring VI will run production

then they will rate us and write awesome reviews ;)
(in testing no rating possible)

and later as VI they will switch to testing

**Comment by sravya71** [comment]
@dogi Intitally A VI can work on the test environment and slowly can run into production.
