### ISSUE TITLE
Step 4 Clarification Steps Needed 

### ISSUE THREAD

**Issue by rohansuri17** [treehouses/treehouses.github.io#615]
### Problem
When entering into the vagrant tutorial on https://treehouses.io/#!./pages/vi/vagranttutorial.md it immediately jumps into going to your command prompt/terminal, cd into cli directory in treehouses, and startup vm using vagrant global-status and vagrant-up. 

There are no steps to tell you to enter your bios and turn on virtualization, install virtual box, install vagrant and to clone the cli git repository from treehouses.
 ### Steps to reproduce the problem
Write N/A if not applicable.
Go to https://treehouses.io
Enter Virtual Interns Section First Steps
Proceed to Step 4 
Click hyper-link to vagrant tutorial
See missing steps indicated in Problem section

 ### Screenshots
Drag and drop images below. Write N/A if not applicable
![Screenshot from 2020-05-20 11-03-37](https://user-images.githubusercontent.com/40804537/82476315-1021be80-9a8b-11ea-8f16-b25bb5e76b06.png)

 ### Proposed solution
Write N/A if not applicable.

Add steps to enable virtualization: https://2nwiki.2n.cz/pages/viewpage.action?pageId=75202968
Add steps to install virtual box: sudo apt-get install virtualbox (for my os ubuntu this worked)
Add steps to install vagrant: sudo apt-get install vagrant (for my os ubuntu this worked)
Clone git repository cli in command line:
cd ~
git clone https://github.com/treehouses/cli.git
ls (This should show you cli folder)
cd cli
Now we can see virtualization file

**Comment by jayala-29** [comment]
curious to see what these updated steps would look like :)
