### ISSUE TITLE
add website badge for repository

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#621]
### Problem
Uptime and Website Status.

 ### Steps to reproduce the problem
N/A.

 ### Screenshots

 ### Proposed solution
Attach markdown badge to Reade me file or the homepage.
Refer to the following link for more information.  [Markdown Badges](https://github.com/Naereen/badges/)

**Comment by jayala-29** [comment]
I'm curious to see how this would look when added  :)

**Comment by fankaiyuan** [comment]
Hi, I have created a PR and added two badges on top of the Readme file, what do you think?
