### ISSUE TITLE
Firsts Steps New Interns Progess Tracking 

### ISSUE THREAD

**Issue by rohansuri17** [treehouses/treehouses.github.io#625]
### Problem
To make sure you can keep a track of progress we can add the progress links to the relevant steps on the way, steps 3 & 6

 ### Steps to reproduce the problem
Go to https://treehouses.io/#!pages/vi/firststeps.md
See Step 3 and 6

 ### Screenshots
Drag and drop images below. Write N/A if not applicable.
![image](https://user-images.githubusercontent.com/40804537/82935269-00522080-9f4a-11ea-9c14-94a16937f0ab.png)

 ### Proposed solution
Would add 
https://treehouses.io/#!./pages/vi/trackprogress.md to steps 3 & 6 similar to the format in 8 to track progress

**Comment by sydneyaldo** [comment]
I think it's a nice idea
