### ISSUE TITLE
Find your Pi in Step 1 Tutorial Issue 

### ISSUE THREAD

**Issue by rohansuri17** [treehouses/treehouses.github.io#626]
### Problem
Most people who have not been exposed to the CLI on macosx do not have brew installed. 
To set them up for better success we should have them install brew before running brew install nmap if they choose to use method 3

 ### Steps to reproduce the problem
Go to Virtual Interns first steps
Navigate to step 1 and select Finding your Pi
Go to method 3 and see nmap installation methods

 ### Screenshots
Drag and drop images below. Write N/A if not applicable.
![image](https://user-images.githubusercontent.com/40804537/82936779-51631400-9f4c-11ea-8c37-e990971a9c9d.png)

 ### Proposed solution
Add command ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" before "brew install nmap" to ensure brew is installed.

**Comment by sydneyaldo** [comment]
Maybe add a note to make sure the user has brew installed instead of the command?
