### ISSUE TITLE
Format of issue title

### ISSUE THREAD

**Issue by fankaiyuan** [treehouses/treehouses.github.io#633]
### Problem
What format of issue title should be used, I saw various types under Issues tab: all lower cases, first letter capital, Pascal Case. 

 ### Steps to reproduce the problem
This is the actual problem when I want to generate my first issue ahead.

 ### Screenshots
![image](https://user-images.githubusercontent.com/17788840/83618908-23d42700-a559-11ea-92d8-03467219b94d.png)

 ### Proposed solution
Add a note under step 6 to suggest a title format or it doesn't matter.

**Comment by Pavivenkatesan** [comment]
@fankaiyuan The tutorial suggests using a short description: The text below is the guideline. 

Ideal: 50 characters
Limit the subject line to 50 characters: Proper length of title ensures that it is readable. GitHub's UI is fully aware of these conventions, so it will warn you if you go over the 50 character limit; any subject line longer than 72 characters will be truncated

SOURCE: https://curt-park.github.io/2018-06-03/branching-commit-strategies/#:~:text=Limit%20the%20subject%20line%20to,72%20characters%20will%20be%20truncated.

**Comment by farzana184** [comment]
@fankaiyuan  I also faced the problem when I was creating my first issue. I assumed there is no format. Also the link shared by @Pavivenkatesan is helpful for future references specifically for commit message and branching.
