### ISSUE TITLE
Duplicate Tor tutorials in step 2 and step 7

### ISSUE THREAD

**Issue by fankaiyuan** [treehouses/treehouses.github.io#635]
### Problem
There are same tutorials about Tor under Step 2 and Step 7. And the commends are different (highlighted).

 ### Steps to reproduce the problem
N/A

 ### Screenshots
Step 2:

![image](https://user-images.githubusercontent.com/17788840/83613879-680ff900-a552-11ea-98af-c3da14c338c4.png)
Step 7:

![image](https://user-images.githubusercontent.com/17788840/83613931-7cec8c80-a552-11ea-8357-6f3bb2781bf0.png)

 ### Proposed solution
Add a note to inform future interns that one can skip this part in step 7 if already installed Tor in step 2. Not sure about the commend part.

**Comment by law-lin** [comment]
Good catch.
