### ISSUE TITLE
Lack solution if treehouses remote not work

### ISSUE THREAD

**Issue by fankaiyuan** [treehouses/treehouses.github.io#636]
### Problem
In step 1 on my Android device, I can detect my Rpi with the treehouses image but it keeps saying "Connection Failed. Please Try Again"

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![image](https://user-images.githubusercontent.com/17788840/83620723-bb3a7980-a55b-11ea-90bb-b9ec2c814886.png)

 ### Proposed solution
I had set up my Rpi with a monitor. Maybe add a possible solution under FAQ ``What if treehouses remote not work?``.

**Comment by Pavivenkatesan** [comment]
@fankaiyuan This problem occurred in the first try or during later trials? I had this issue coming and going but it is getting fixed by itself if I try again in few seconds. I assumed some latency in connectivity.

**Comment by fankaiyuan** [comment]
My problem occurred in the previous version of Remote, and some USB devices on Rpi may cause this to happen. This issue should be closed, but I think it's better to have someplace states "what if remote not working" than nothing.

**Comment by Pavivenkatesan** [comment]
> My problem occurred in the previous version of Remote, and some USB devices on Rpi may cause this to happen. This issue should be closed, but I think it's better to have someplace states "what if remote not working" than nothing.

I agree that would be helpful.

**Comment by leosp123** [comment]
I agree, I had some issues with this as well.

**Comment by anthonyhvo12** [comment]
I also experience the same issue every time I try to connect to my Pi using remote. The error usually goes away after 1-2 tries. Maybe add a simple note that if it says "Connection Failed", retry in a few seconds.
