### ISSUE TITLE
faq.md Additional Helpful Links

### ISSUE THREAD

**Issue by rohansuri17** [treehouses/treehouses.github.io#641]
### Problem
In faq.md I noticed there isn't any links on working with the command line interface. My first time working with the CLI was a mess and I think it would be helpful to provide new interns with the resources or a cheat sheet to remember the commands.

 ### Steps to reproduce the problem
Go to treehouses website
Click on FAQ
Scroll down to Helpful Links
See that there are no resources on working with CLI 

 ### Screenshots
Drag and drop images below. Write N/A if not applicable.
![image](https://user-images.githubusercontent.com/40804537/83918202-7a965800-a735-11ea-8a34-c5f1e171a8c0.png)

 ### Proposed solution
Add a CLI cheat sheet for every OS:
macOS- https://www.makeuseof.com/tag/mac-terminal-commands-cheat-sheet/
Ubuntu/Linux- http://images.linoxide.com/linux-cheat-sheet.pdf
Windows CMD/Powershell- https://ss64.com/nt/

**Comment by jayala-29** [comment]
good idea :)

**Comment by boomzilla** [comment]
As a prospective intern, am I allowed to assign myself to any issue I think I can fix, or should I aim to defer to other people more? I can easily add these links to my fork, and then to a PR, but my sense of "coding etiquette" tells me that I should wait to see if @rohansuri17 wants to take on this assignment. (I have a fair amount of experience writing code on my own, but I realize most coding is a social enterprise).

**Comment by rohansuri17** [comment]
I'd like to take on this assignment if possible
