### ISSUE TITLE
opening an anchor link in new tab causes a page load error

### ISSUE THREAD

**Issue by boomzilla** [treehouses/treehouses.github.io#643]
### Problem
For multiple pages in the Treehouses wiki, right-clicking on an anchor link (i.e. a hyperlink that leads to a different section on the same webpage) in the document body, and then attemping to open in a new browser tab, causes a _page not found_ error.

 ### Steps to reproduce the problem
1. navigate to https://treehouses.io/#!pages/vi/githubandmarkdown.md
2. scroll to "Start Here" section
3. right-click on the hyperlink at "Login to GitHub with your username and password", and open in new tab
4. observe the new tab has opened to an error page with the message, "Sorry, the page you are looking for doesn’t exist."

 ### Screenshots
[video recording on the sequence to reproduce](https://youtu.be/3GIrrSMZcEI)

 ### Proposed solution
I honestly am not sure. The behavior may stem more from how the markdown syntax is parsed, and vary from interpreter to interpreter; rather than how the markdown itself is written. In that case, it may be out-of-scope. If the issue is to be resolved by rewritting the markdown syntax, I would suggest setting up some sort of script in e.g. Python to fix all the links (rather than manually going through every single link).

**Comment by sonAndrew** [comment]
Hey @boomzilla  this is **not an issue**. 

The reason they do this is because they are linking to parts of the same page. They are **not external links**.
