### ISSUE TITLE
Adding a new method under find pi page

### ISSUE THREAD

**Issue by fankaiyuan** [treehouses/treehouses.github.io#652]
### Problem
Adding a new method using [Advanced IP Scanner](https://www.advanced-ip-scanner.com/) under [find pi](https://treehouses.io/#!./pages/vi/find-pi.md) page for Windows user

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
## Method 6: Advanced IP Scanner

The [Advanced IP Scanner](https://www.advanced-ip-scanner.com/) is a reliable and free network scanner with a simple and clean interface to analyze local area network, available for Windows.

In the search bar, enter your range of IP address and press **Scan** button to scan devices under your specified subnet. Advanced IP Scanner will start scanning your Ethernet and Wi-Fi LANs. Your Raspberry Pi should connect to the same LAN with your computer. The program begins to return results as it detected each machine on your local network. In the Results tab, Advanced IP Scanner displayed the Status, Name, IP, Manufacturer, and MAC Address of each device. You will find your Raspberry Pi with the name "treehouses".

**Comment by Pavivenkatesan** [comment]
@fankaiyuan, It does work on windows. It's successful in showing IP address, but name isn't being displayed. Could you clarify?

IMAGE 1: Connected via Treehouses Remote
![image](https://user-images.githubusercontent.com/37712975/87724565-af141f80-c789-11ea-8f46-e0876d0a7045.png)

IMAGE 2: Connected to Raspberry Pi directly via WiFi (treehouses)
![image (1)](https://user-images.githubusercontent.com/37712975/87724580-b2a7a680-c789-11ea-8be0-0232a02ecf33.png)

**Comment by fankaiyuan** [comment]
Good findings. What Rpi model are you using, did you change your hostname? Not really sure what's happening here, but it does show treehouses on my side.

![image](https://user-images.githubusercontent.com/17788840/87735786-7df51880-c7a4-11ea-81c0-fc644666f42b.png)

**Comment by Pavivenkatesan** [comment]
> hat Rpi model are you using, did you change your hostname? Not really sure what's happening here, but it does show treehouses on my side.

I'm using Pi 4. I did change the device name to my username as in step 7.

**Comment by Pavivenkatesan** [comment]
> > hat Rpi model are you using, did you change your hostname? Not really sure what's happening here, but it does show treehouses on my side.
> 
> I'm using Pi 4. I did change the device name to my username as in step 7. I used Windows 10 HP Envy to test this tool.

**Comment by fankaiyuan** [comment]
> 
> 
> > > hat Rpi model are you using, did you change your hostname? Not really sure what's happening here, but it does show treehouses on my side.
> > 
> > 
> > I'm using Pi 4. I did change the device name to my username as in step 7. I used Windows 10 HP Envy to test this tool.

Changing the device's hostname may cause the tool not displaying the name. It's an alternate method for Step 1 finding Rpi's IP address, but it's good to know different behaviors from other machines. Thanks for sharing.

**Comment by leosp123** [comment]
I tried it. Seems like a good method to use!

**Comment by JLKwong** [comment]
IP Scanner is not able to find my Pi with the SD card from Step 7, but my router can see it and my PC can ping it.

![image](https://user-images.githubusercontent.com/61807745/105940088-5d3d3380-600f-11eb-81e3-23dba8dd59e3.png)
![image](https://user-images.githubusercontent.com/61807745/105940146-7c3bc580-600f-11eb-8242-f4d618622497.png)
![image](https://user-images.githubusercontent.com/61807745/105939996-21a26980-600f-11eb-8bde-5901cbe6684d.png)

**Comment by fankaiyuan** [comment]
Hi @JLKwong, not sure why it does not appear on your side, I assume you are scanning in the right range, so your hostname change may be the reason your pi not showing up. Thanks for trying this method anyway!

**Comment by fankaiyuan** [comment]
Since I have finished the internship in OLE, any future interns are free to create PR for this issue.
