### ISSUE TITLE
Empty file named 0

### ISSUE THREAD

**Issue by vkabc** [treehouses/treehouses.github.io#653]
### Problem
Empty file named 0 found on the root directory of treehouses.github.io

 ### Steps to reproduce the problem

N/A

 ### Screenshots
<img width="1440" alt="Screenshot 2020-06-13 at 2 53 30 PM" src="https://user-images.githubusercontent.com/4152386/84562260-a80e8180-ad85-11ea-8b86-04c10e3068f1.png">

 ### Proposed solution
Delete empty file

**Comment by fankaiyuan** [comment]
Good catch, may I take this one?

**Comment by vkabc** [comment]
Sure. Good Luck!
