### ISSUE TITLE
raw.githack link is inconsistent

### ISSUE THREAD

**Issue by Pavivenkatesan** [treehouses/treehouses.github.io#666]
### Problem
The raw.githack link mentioned in **Step 3** is adding to ambiguity during the installation process.

 ### Steps to reproduce the problem
1. Navigate to https://treehouses.io/#!index.md
2. Select the option **Step 3: Markdown and Fork Tutorial under the Virtual interns dropdown**.
3. Scroll down to the section "**Create a new file as your personal MDwiki page and commit your changes**"

 ### Screenshots
GUIDE STYLE:
![image](https://user-images.githubusercontent.com/37712975/87594195-97219a80-c6ba-11ea-9ced-ba72208dd28b.png)
DEFECTIVE STYLE:
![image](https://user-images.githubusercontent.com/37712975/87594432-ee276f80-c6ba-11ea-9965-c2a470808ccb.png)

 ### Proposed solution
The ideal solution would be to use the red color font in the "**Introductory/First Steps" page under the "Step 3 - Markdown and Fork Tutorial**" section.

**Comment by Pavivenkatesan** [comment]
@dogi Could you please review this issue? Thank you.

**Comment by sydneyaldo** [comment]
I don't see it as ambiguous, did you mean inconsistent?

**Comment by Pavivenkatesan** [comment]
> n't see it as ambiguous, did you mean inconsistent?

Yes, you're right. I meant it was inconsistent.

**Comment by Pavivenkatesan** [comment]
> I don't see it as ambiguous, did you mean inconsistent?

Can I start working on this issue? @sydneyaldo

**Comment by law-lin** [comment]
Sure, I think that you should change the red `raw.githack` portions to be links instead though. That would make the most sense and keep it consistent.

**Comment by Pavivenkatesan** [comment]
> ould change the red `raw.githack` portions to be links instead though. That would make the most sense and keep it consistent.

The link mentioned in **red color** wouldn't necessarily work because they give details on how to construct a raw.githack link without a generator. On the other side, **https://raw.githack.com/** this link should be in **green color** because it takes us to a different page where you can generate a personalized link for yourself(it's a working link). I made the differentiation clearly.
