### ISSUE TITLE
Step 6: "Detailed Steps", link for "Sync Your Fork" doesn't take to detailed section

### ISSUE THREAD

**Issue by Pavivenkatesan** [treehouses/treehouses.github.io#668]
### Problem
In the GitHub repository tutorial section, the "Sync Your Fork" section is duplicated, and the link doesn't take to the intended detailed section. Instead, it takes to the "Summary of Steps" section
 ### Steps to reproduce the problem
1. Go to https://treehouses.io/#!./pages/vi/gitrepositories.md
2. Scroll down to Detailed Section
3. Click on "Sync Your Fork"
4. Observe that it takes the user to Sync Your Fork under "Summary of Steps" section in the top part, instead of, Sync Your Fork under "Detailed Steps" section.

 ### Screenshots
Video recording: (Willing to tear down video or change privacy settings if needed)

https://www.youtube.com/watch?v=-VzNCVb2qLA

 ### Proposed solution
The "Sync Your Fork" section will have to take users to "Detailed Steps"->"Sync Your Fork"

**Comment by fankaiyuan** [comment]
good catch

**Comment by Pavivenkatesan** [comment]
> good catch

@fankaiyuan Thanks. I have fixed both the issues you reviews and raised 2 PRs. Could you please review the PRs?
