### ISSUE TITLE
Suggested addition to "Create a New Branch" section

### ISSUE THREAD

**Issue by Pavivenkatesan** [treehouses/treehouses.github.io#674]
### Problem
Creating a New Branch every time off master is necessary in order to prevent unintentional changes to be trickled from one branch to the other. This adds a little clarity to the manual for beginners.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
<img width="1747" alt="Screen Shot 2020-07-18 at 11 17 38 AM" src="https://user-images.githubusercontent.com/37712975/87855928-8acf5480-c8e9-11ea-88bc-928a8be51c1c.png">

 ### Proposed solution
In the page, https://treehouses.io/#!pages/vi/github-issues.md a new note section could be added that says,
"**Everytime a new branch is created, make sure that you switch to master branch using the command, 
```git checkout master```**"

**Comment by Pavivenkatesan** [comment]
@/all @dogi Could you please review this Issue?

**Comment by Pavivenkatesan** [comment]
@dogi Could you please review the issue and the attached PR?

**Comment by leosp123** [comment]
Good idea

**Comment by anthonyhvo12** [comment]
I agree. Many PRs from the repo for the open-learning-exchange.github.io page have also been rejected as they were created out of another feature branch, which is not the correct way to do it.
