### ISSUE TITLE
"Track Progress" link not working

### ISSUE THREAD

**Issue by Pavivenkatesan** [treehouses/treehouses.github.io#675]
### Problem
Track progress link displays error, "User <username> does not exists"

 ### Steps to reproduce the problem
1. Go to https://treehouses.io/#!pages/vi/trackprogress.md
2. Click "PR/Issues count" link
3. Enter your github username in the pop up.

 ### Screenshots
<img width="815" alt="Screen Shot 2020-07-20 at 1 00 31 PM" src="https://user-images.githubusercontent.com/37712975/87965190-5abeb780-ca89-11ea-9e72-cbcd72c2c629.png">

 ### Proposed solution
N/A

**Comment by ali18997** [comment]
Seems to be working right now

**Comment by Pavivenkatesan** [comment]
> Seems to be working right now
 
I wasn't sure what was the issue then. Any other fixes could have temporarily impacted? Just wanted to know before closing the issue. @ali18997

**Comment by law-lin** [comment]
@Pavivenkatesan It could've been a problem with GitHub's API.

**Comment by Pavivenkatesan** [comment]
Closing issue
