### ISSUE TITLE
Missing Commas in firststeps.md

### ISSUE THREAD

**Issue by leosp123** [treehouses/treehouses.github.io#678]
### Problem
There is a comma issue regarding the word however in the first steps page.

 ### Steps to reproduce the problem
In https://treehouses.io/#!pages/vi/firststeps.md, go to Step 0. 

 ### Screenshots
![error](https://user-images.githubusercontent.com/57111412/88355023-f02fa500-cd30-11ea-993e-17815833c205.PNG)

 ### Proposed solution
Add a comma before and after the word however. It should be "If, however, you are on a windows device, Git Bash is highly recommended."

**Comment by law-lin** [comment]
Good catch
