### ISSUE TITLE
Clarification for Change Directory in Step 4

### ISSUE THREAD

**Issue by leosp123** [treehouses/treehouses.github.io#679]
### Problem
In the Vagrant tutorial, under the Stay in the Right Directory part, it says that we should use C:\Users\YOUR_USERNAME\Desktop\treehouses\cli as our directory that contains the Vagrant file.

Some users may have cli under a different directory, which leads to cd C:\Users\YOUR_USERNAME\Desktop\treehouses\cli not finding the specified path.

 ### Steps to reproduce the problem
Run cd C:\Users\YOUR_USERNAME\Desktop\treehouses\cli when the specified path does not exist.

 ### Screenshots
![error2](https://user-images.githubusercontent.com/57111412/88355630-4d2c5a80-cd33-11ea-9ce0-12626af48f8e.PNG)

 ### Proposed solution
Change it so that we tell the user to cd wherever they have the cli file under.

**Comment by law-lin** [comment]
Good idea - I don't keep my folders under Desktop.

**Comment by Pavivenkatesan** [comment]
Good find :) We can also mention that it's not a norm. So interns may not wonder if Vagrant requires them to save in this specific path.
