### ISSUE TITLE
Capitalization issue in gitrepositories.md

### ISSUE THREAD

**Issue by leosp123** [treehouses/treehouses.github.io#683]
### Problem
Under "Understand that there are three levels of a Github respository", "the" isn't capitalized in "the upstream".

 ### Steps to reproduce the problem
Go to https://treehouses.io/#!./pages/vi/gitrepositories.md

 ### Screenshots
![error4](https://user-images.githubusercontent.com/57111412/88448963-1298ef80-ce11-11ea-9f70-03ee38b764d5.png)

 ### Proposed solution
Capitalize "the" which changes the bullet to The upstream (treehouses.github.io)

**Comment by anthonyhvo12** [comment]
Good catch!
