### ISSUE TITLE
Typos on "Treehouses node deploy" blog

### ISSUE THREAD

**Issue by anthonyhvo12** [treehouses/treehouses.github.io#693]
### Problem
There are several typos on the "Treehouses node deploy" blog. In addition, multiple aliases for the Raspberry Pi were used, causing inconsistencies.

 ### Steps to reproduce the problem
Go to **Blog**, then click on **Set up headless treehouses node** .

 ### Screenshots
![Screen Shot 2020-08-08 at 10 18 27 AM](https://user-images.githubusercontent.com/43098273/89702831-7e319f80-d96f-11ea-8bf4-7a98442b7e64.png)
<img width="834" alt="Screen Shot 2020-08-08 at 10 22 56 AM" src="https://user-images.githubusercontent.com/43098273/89702833-81c52680-d96f-11ea-985e-d20295d281a8.png">
<img width="723" alt="Screen Shot 2020-08-08 at 10 35 02 AM" src="https://user-images.githubusercontent.com/43098273/89702835-82f65380-d96f-11ea-8b95-d02fe9853ed1.png">

 ### Proposed solution
Fix the typos and refer to the Raspberry Pi consistently as "Pi" or "Raspberry Pi."

**Comment by mattscodeans** [comment]
Good catch! I agree with you that Raspberry Pi should be referred to a consistent alias throughout the blog.
