### ISSUE TITLE
Lack of Indication that Installing Docker on User's Computer is Entirely Optional

### ISSUE THREAD

**Issue by mattscodeans** [treehouses/treehouses.github.io#696]
### Problem
Since Docker and Docker Compose are already installed on the Raspberry Pie by default, installing Docker and Docker Compose on the user's computer is completely optional to complete the 10 steps. However, the current way the formatting is structured does not immediately indicate to the user that this installation is optional.

 ### Steps to reproduce the problem
Visit the following link:
https://treehouses.io/#!./pages/vi/dockertutorial.md

Click on Docker Installation on the left hand side navigation bar.

Notice how it is not immediately obvious to the user that Docker installation on the user's computer is optional.

 ### Screenshots
![image](https://user-images.githubusercontent.com/42992553/89751333-731c6380-da84-11ea-8095-d5d6ebf5fc61.png)

 ### Proposed solution
Replace the heading of the section "Docker Installation" with "Docker Installation (Optional)". This will immediately notify the user that installing Docker is optional.

**Comment by gautamsethi1** [comment]
Definitely agree with this. I missed the part about it being optional, and didn't realize it until you pointed it out. Clearly labelling would avoid any of this confusion.
