### ISSUE TITLE
Fix treehouses.github.io link

### ISSUE THREAD

**Issue by lmmrssa** [treehouses/treehouses.github.io#72]
Currently treehouses.github.io repository link is pointing to `https://github.com/treehouses.github.io` it needs to be pointed to `https://github.com/treehouses/treehouses.github.io`

**Comment by phamduchongan93** [comment]
It's fixed. [treehouses.github.io](treehouses.github.io) link will point you to the treehouses homepage. If you refer to step0, the link directs you to a treehouses git page, which is [https://github.com/treehouses/treehouses.github.io](https://github.com/treehouses/treehouses.github.io)

**Comment by dogi** [comment]
thanks @phamduchongan93 

@lmmrssa can you double check on this?
or send us a picture of what we need to fix

**Comment by lmmrssa** [comment]
@dogi it was already fixed by #73 but looks like issue was not closed. closing now.
