### ISSUE TITLE
Comma use issues

### ISSUE THREAD

**Issue by gautamsethi1** [treehouses/treehouses.github.io#726]
### Problem
There is incorrect usage of commas in the 'Setting up your environment' section. 

 ### Steps to reproduce the problem
Click on the Virtual Interns tab
Then click on Introduction
Scroll to the 'Setting up your environment' section

 ### Screenshots
<img width="829" alt="Screen Shot 2020-08-16 at 3 42 00 PM" src="https://user-images.githubusercontent.com/33525794/90345880-54b0ed80-dfd9-11ea-87c1-c3c1b09f8654.png">

 ### Proposed solution
Add a comma after If, and however. Add another comma before which.

**Comment by fankaiyuan** [comment]
see #678 and #711
