### ISSUE TITLE
Mispelling in Vagrant Tutorial

### ISSUE THREAD

**Issue by gautamsethi1** [treehouses/treehouses.github.io#727]
### Problem
VirtualBox is misspelled. 

 ### Steps to reproduce the problem
Navigate to the Vagrant tutorial

 ### Screenshots
<img width="1092" alt="Screen Shot 2020-08-16 at 4 07 55 PM" src="https://user-images.githubusercontent.com/33525794/90346402-790ec900-dfdd-11ea-9039-dbbe21c0ddfc.png">

 ### Proposed solution
Fix spelling.

**Comment by fankaiyuan** [comment]
![image](https://user-images.githubusercontent.com/17788840/90452688-9f973780-e0a3-11ea-9010-f8f5858b5b97.png)
Good catch
