### ISSUE TITLE
Early Terminal Users Confusions

### ISSUE THREAD

**Issue by MichaelCado** [treehouses/treehouses.github.io#749]
### Problem
early terminal users confusion in copying/ typing commands

 ### Steps to reduce the problem
insert command guide between Method 2 instruction and Method 2 screenshot. 

  ### Screenshots
![Finding-Your-Pi-Method-2](https://user-images.githubusercontent.com/36717680/97456729-81557f80-190f-11eb-960c-e8662f69f066.jpg)

 ### Proposed solution
 1. copy and paste guide for terminal users  is visible 
 2. Output are now with labels to distinguish commands and return output
 3. Or a simple proposed solution at image no.2
 4. Suggest PuTTY for windows users

### Image 1
![Proposed-Solution](https://user-images.githubusercontent.com/36717680/97460005-bca57d80-1912-11eb-9f4e-f0615a7d72d1.jpg)

### Image 2
![Proposed-Solution-2](https://user-images.githubusercontent.com/36717680/97463628-54f13180-1916-11eb-856e-27a3dcfc082d.jpg)

**Comment by thatgirlprogrammer** [comment]
I like the idea of having commands to copy and paste with expected output. It would be helpful for people learning the command prompt. There should be screenshots of each command with expected output.

**Comment by farzana184** [comment]
I also feel that having screenshots of expected output helps to determine if we are doing the steps correctly and also it is important to make sure before proceeding to write further commands to avoid any system errors.

**Comment by MichaelCado** [comment]
to All, thanks for your feedbacks, I highly appreciate it. I'm working on the proposed fix. hope to see you guys at the pull request

**Comment by dogi** [comment]
I am closing this issue
