### ISSUE TITLE
Fixing errors in FAQ page for question 3

### ISSUE THREAD

**Issue by farzana184** [treehouses/treehouses.github.io#758]
### Problem
In the answer to the question 3 of the FAQ page (https://treehouses.io/#!pages/vi/faq.md) , the title for the intern is written as "Software Engineer Intern " and the link "here" does not provide information about the internship. 

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![err](https://user-images.githubusercontent.com/35871883/97934088-42be2b80-1d3a-11eb-8c80-2eb74378341c.PNG)

 ### Proposed solution
Change the title as "Virtual Systems Engineer Intern" and change the link as https://treehouses.io/#!index.md to redirect users to the homepage for more information.

**Comment by jbtill** [comment]
It looks to me like this link is supposed to lead to the actual job posting for the internship. Maybe the link could lead to a page that still has the internship positions posted, like on [this page](https://www.linkedin.com/jobs/search/?f_C=1520354&geoId=92000000). Just throwing ideas out though, I'm not sure if this was the intent.

**Comment by dogi** [comment]
fix it by publishing some openings
https://www.indeed.com/cmp/Open-Learning-Exchange,-Inc./jobs
