### ISSUE TITLE
Replacing link for VirtualBox under "Helpful Videos" section 

### ISSUE THREAD

**Issue by farzana184** [treehouses/treehouses.github.io#759]
### Problem
The link for "How to Use VirtualBox" (https://treehouses.io/?fbclid=IwAR35Z9y20FI7M0QaRdoUcd1OEL0ojSv--m3Hkoa3piD6OBbNlSPAW1qUkMY#!./pages/vi/faq.md#Helpful_Links) under the "Helpful Videos" section is no longer working.

 ### Steps to reproduce the problem
N /A

 ### Screenshots
![oo](https://user-images.githubusercontent.com/35871883/97945390-07792800-1d4d-11eb-930a-43b502ebc650.PNG)
![v](https://user-images.githubusercontent.com/35871883/97945413-1eb81580-1d4d-11eb-83c3-7e10182ffb96.PNG)
Clicking on the link takes the user to the page where the video is no longer available shown as the above image.

 ### Proposed solution
Replace the  current link with the link below that would provide useful information about VirtualBox: https://www.youtube.com/watch?v=sB_5fqiysi4&t=178s

**Comment by jbtill** [comment]
Good catch, I didn't even notice that the video for the link was missing. Definitely will be helpful for people who need to be introduced to Virtual Box.
