### ISSUE TITLE
Change for SSH Tutorial

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#76]
> To add your SSH key to your Raspberry Pi, run: treehouses sshkey add "your SSH key" (copy-paste your SSH key in between the quotes).

[https://treehouses.io/#!pages/vi/sshpi.md](https://treehouses.io/#!pages/vi/sshpi.md)
before running this command, users need root privilege to append keys.

**Comment by Liew211** [comment]
@phamduchongan93 Looks like your link is wrong :P it's `[text](url)`

To run this properly, you need to add `sudo` before your command -> `sudo treehouses sshkey add "your SSH key"`

You can go ahead and work on this issue.
