### ISSUE TITLE
Specify root password in Step 7

### ISSUE THREAD

**Issue by jbtill** [treehouses/treehouses.github.io#760]
### Problem
In the "Start up Nextcloud" section of Step 7, you are given the option to ssh into the Pi as root, but the default root password is not specified. Because of this, when I completed this step, my only option was to log in as the "pi" user, then change to root afterwards.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
N/A

 ### Proposed solution
Specify what the root password is in this step. Also, if the user wants to log in as "pi", it may be helpful to mention that the default password is "raspberry", in case the user forgot.

Current step:
> Find the Raspberry Pi's IP address in your network settings (it will probably be 192.168.2.1). Open up your terminal or command prompt, and run ssh root@[IP address] to enter the root of your Pi or, to log into the Pi user use ssh pi@[local IP address] and to log into root, you can run sudo -s.

Revised step:
> Find the Raspberry Pi's IP address in your network settings (it will probably be 192.168.2.1). Open up your terminal or command prompt, and run ssh root@[IP address] to enter the root of your Pi **using the password (root password)** or, to log into the Pi user use ssh pi@[local IP address] **using the password "raspberry"** and to log into root, you can run sudo -s.

**Comment by farzana184** [comment]
I ran into similar issue while working on step 7. I tried to figure out the password for root but I could not. I used the alternative way.

**Comment by dogi** [comment]
@farzana184 and @JLKwong root on rpi does not have a password
