### ISSUE TITLE
Adding a new useful link for virtualization under Vagrant Tutorial

### ISSUE THREAD

**Issue by farzana184** [treehouses/treehouses.github.io#761]
### Problem
As mentioned in step 3 (https://treehouses.io/#!./pages/vi/vagranttutorial.md), it requires to enable virtualization before proceeding with VirtualBox and Vagrant. Although there was a link provided to enable virtualization of the system it does not provide how to practically first check for virtualization and then enable virtualization if it is not enabled.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![enable_vr](https://user-images.githubusercontent.com/35871883/98011937-206df180-1dbe-11eb-9446-127c3c9a8a64.PNG)

 ### Proposed solution
Adding the video link  - https://www.youtube.com/watch?v=MOuTxfzCvMY&fbclid=IwAR0O4zfe7tY3yVY9r2adR0P1LqI8dVlSjH_lp_UpbUgppjGFZsynL-BWP-o under "Useful Links" in the Vagrant Tutorial page about checking and enabling virtualization for windows will help many with the steps.

**Comment by jbtill** [comment]
Good idea, showing how to check if virtualization is already enabled will help save time for people who already have it enabled.

**Comment by BryanGazali** [comment]
This would certainly be helpful. I had also ran into the case where virtualization was already enabled on my device, so adding this link could help save time for some people.
