### ISSUE TITLE
Add link to planet

### ISSUE THREAD

**Issue by jbtill** [treehouses/treehouses.github.io#762]
### Problem
In the Intern orientation document, it is mentioned that Docker is used by OLE for applications such as planet, but there is no link to more information about planet.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![Planet](https://user-images.githubusercontent.com/26392179/98016228-b4928580-1dcb-11eb-8be9-5b079232671e.PNG)

 ### Proposed solution
Make it so "planet" is a link to the [Planet Learning info page](https://www.ole.org/our-platform/)

**Comment by BryanGazali** [comment]
This could serve as a helpful bit of resource.
