### ISSUE TITLE
Add alternate Docker Compose installation guide

### ISSUE THREAD

**Issue by BryanGazali** [treehouses/treehouses.github.io#765]
### Problem
In the "Install Docker Compose" section on Step 4, the installation steps listed constantly resulted in errors when I tried following them, so I had to find an alternate installation solution elsewhere. Thus it may be useful to add an alternate set of installation steps, should the original installation steps fail. 

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![Docker-Compose issue](https://user-images.githubusercontent.com/46581520/98198946-22d46680-1ef8-11eb-964c-6db576c1c9c9.png)

 ### Proposed solution
Add a second set of installation steps below the first set. Said steps would involve uninstalling and reinstalling docker-compose via python 3.

**Comment by jbtill** [comment]
I agree that it's a good idea to add alternative ways for installing docker, in case the user has trouble getting it working with the steps in the tutorial. Do you have a link to the steps you used to get it working?

**Comment by BryanGazali** [comment]
The steps I came to was after trying multiple different solutions and then combining some of them. I would say these two links were the ones that helped me get to my solution.
This one showed how to uninstall docker-compose via python
https://stackoverflow.com/questions/36685980/docker-is-installed-but-docker-compose-is-not-why
This one showed how to install docker-compose via python 3
https://chrisschuld.com/2019/09/installing-docker-and-docker-compose-on-raspberry-pi4-with-raspian/

**Comment by farzana184** [comment]
I also faced difficulties while Installing Docker and Docker compose. The given steps did not work for me and I got the same error as the picture above. Adding alternative steps as stated above will be helpful.
