### ISSUE TITLE
Removing an extra character in the note section of step 6

### ISSUE THREAD

**Issue by farzana184** [treehouses/treehouses.github.io#767]
### Problem
In the "Note" section of step 6 in the "First Steps" page (https://treehouses.io/#!pages/vi/firststeps.md#Step_1_-_Installing_and_finding_your_Raspberry_Pi), there is an extra unwanted character at the end the sentence as highlighted in the picture below. 

 ### Steps to reproduce the problem
 N/A 

 ### Screenshots
![re](https://user-images.githubusercontent.com/35871883/98278455-3c0ffe00-1f5e-11eb-8c43-5ed0b6e54e62.PNG)

 ### Proposed solution
Removal of the unwanted extra character.

**Comment by samitcheema** [comment]
Good catch :)
