### ISSUE TITLE
Adding the missing word (preposition) in the fourth paragraph of the section "The Steps"

### ISSUE THREAD

**Issue by farzana184** [treehouses/treehouses.github.io#771]
### Problem
In the first line of the fourth paragraph of the section "The Steps" in the page "First Steps" (https://treehouses.io/#!pages/vi/firststeps.md#Step_1_-_Installing_and_finding_your_Raspberry_Pi), the word "on" is
 missing after the phrase "keep us updated" as highlighted in the picture below.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![pro](https://user-images.githubusercontent.com/35871883/98391810-c159e800-201c-11eb-931e-46e710666bb5.PNG)

 ### Proposed solution
Adding the word "on" after "keep us updated".

**Comment by BryanGazali** [comment]
Good catch on that grammar mistake.
