### ISSUE TITLE
For those who wish to run nested virtualization

### ISSUE THREAD

**Issue by samitcheema** [treehouses/treehouses.github.io#782]
### Problem
Users who are already working within their own dedicated VM and want to continue working within it might run into issues regarding nested virtualization. 

 ### Steps to reproduce the problem
Run vagrant up within your VM without VT-x/AMD-V support enabled.

 ### Screenshots
N/A

 ### Proposed solution
Dedicating a small section to those who are already working within a VM, to make sure their CPU has VT-x/AMD-V support and that they have VT-x/AMD-V enabled on their vm software. i.e. VMWare Workstation, Virtualbox etc.
 

**NOTE**:If you are already working within your own virtual machine and wish to continue to do so, please enable VT-x/AMD-V for your respected VM software to enable nested virtualization before proceeding forward. 
How to enable VT-x/AMD-V: [Virtualbox](https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html), [VMware](https://communities.vmware.com/t5/Nested-Virtualization-Documents/Running-Nested-VMs/ta-p/2781466).

**Comment by dogi** [comment]
@samitcheema interesting ... wonder how to say all of  this without sidelining too much

**Comment by samitcheema** [comment]
To summarize, it makes sure the user has VT-x/AMD-V capability within their CPU and it is enabled before they start to proceed and work within their own virtual machine so they avoid any errors they might encounter further on. So nothing more than a small side note. @dogi

**Comment by JLKwong** [comment]
Sami's small side note could be placed somewhere around this section:

![image](https://user-images.githubusercontent.com/61807745/105942286-c58e1400-6013-11eb-859a-cf5298a4100b.png)
