### ISSUE TITLE
change order of vagrant step

### ISSUE THREAD

**Issue by samitcheema** [treehouses/treehouses.github.io#783]
### Problem
`vagrant up` should be specified before `vagrant global-status`

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![vagrant_capture](https://user-images.githubusercontent.com/53884212/103157784-c1f13e00-4784-11eb-894c-525c9c7296d9.PNG)

 ### Proposed solution

Specifying `vagrant up` before attaining the global status. 

## Start up the Vagrant machine

Start up your vagrant environment by using the command `vagrant up`.

## Global Status

[`vagrant global-status`](https://www.vagrantup.com/docs/cli/global-status.html) will tell us the state of all active Vagrant environments on the system for the currently logged in user. You will see something similar to this:

```
id       name   provider   state   directory
---------------------------------------------------------------------------
0e6abb1  cli    virtualbox running  /Users/pattanawadee/cli

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date (use "vagrant global-status --prune" to prune invalid
entries). To interact with any of the machines, you can go to that
directory and run Vagrant, or you can use the ID directly with
Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
```
~~If no environments show up as active, use the command `vagrant up` and try again.~~

**Comment by dogi** [comment]
@samitcheema good catch

**Comment by JLKwong** [comment]
When I initially read these instructions, I was wondering if `vagrant global-status` was supposed to try to start the vagrant environment before checking the status. I definitely agree with the edit being less confusing.
