### ISSUE TITLE
Reformat the redundant steps found in Step 5

### ISSUE THREAD

**Issue by rjpadilla** [treehouses/treehouses.github.io#785]
### Problem
The steps inside the **Summary of Steps** and **Detailed Steps** sections found in the **Step 5 - Keeping Fork Updated** page are redundant.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![Redudant steps](https://github.com/rjpadilla/rjpadilla.github.io/blob/assets/gitreporedudant.jpg?raw=true)

 ### Proposed solution
When I was following the steps in **Step 5 - Keeping Fork Updated** page I had a sense of *deejay-vu*. I realized that I was going through redundant material in the **Detailed Steps** section. 
    To the potential new intern (like myself), going through the steps in **Step 5 - Keeping Fork Updated** felt very confusing and ambiguous due to **_repetitive steps_** found in **Summary of Steps** and later in **Detailed Steps**. By reformatting or removing **_either_** of those sections, you can achieve instructions that are easier and simpler to understand for the new intern.

The solutions to make the steps clearer to understand are listed in the options below:
1. Remove **Summary of Steps**
    - Despite having hints and anchored links for more information on these steps, the **Summary of Steps** instructions pales in-comparison to the detailed explanations found in the **Detailed Steps**.
2. Move  **Summary of Steps** below the **Detailed Steps**
    - When some person reaches the summary of a page, it is assumed they reached the conclusion of an objective--- with the summary reiterating the steps found in the objective.
    - By having the **Summary of  Steps** smacked in the middle of **Step 5 -Keeping Fork Updated**, the *logical flow* of the reader is broken.
    - Can be easily mitigated by moving the **Summary of Steps** markdown below **Detailed Steps**, hence having a true conclusion (and the steps ceasing to be redundant but more of a refresher) to **Step 5 - Keeping Fork Updated**.    
3. Add a disclaimer to skip over the **Detailed Steps** section if they had already completed the steps found in **Summary of Steps**

By selecting either proposed solutions 1, 2, or 3, I believe would improve the flow of steps in having the reader's fork updated.

**Comment by dogi** [comment]
hmmm agree - this could be a difficult one
@rjpadilla generally I agree
-> philosophie is sometimes less is more ;)

**Comment by samitcheema** [comment]
Good catch! Summary comes after the details.
