### ISSUE TITLE
FAQ Page missing an alternative use for 'YourUserName.github.io'

### ISSUE THREAD

**Issue by CalebProvost** [treehouses/treehouses.github.io#79]
Posting an explanation on how to create an organization and using that user name in lieu of 'yourusername' needs to be added to the FAQ page; or instead of referencing the FAQ page for the alternative, have it listed in step 3.

**Comment by Liew211** [comment]
You can work on this 👍 

I suggest that you add this as another FAQ (Q10), we can add more in the Technical Questions section.
