### ISSUE TITLE
Change 'Clone or Download' to 'Code' in gitrepositories.md

### ISSUE THREAD

**Issue by rjpadilla** [treehouses/treehouses.github.io#801]
### Problem
Github has modified the 'Clone or Download' button that's found in ones repo to now saying 'Code'.

 ### Screenshots

![updategitclonebutton2](https://user-images.githubusercontent.com/23529006/104977957-d238b980-59ce-11eb-9602-0c53dee32042.jpg)
![updategitclonebutton](https://user-images.githubusercontent.com/23529006/104977953-cd740580-59ce-11eb-8694-b98476d1dbaa.jpg)

 ### Proposed solution
Change 'Clone or Download' to 'Code' in the **Clone Your GitHub Repository username.github.io** instructions found in gitrepositories.md

**Comment by BryanGazali** [comment]
This would be a good update to make.
