### ISSUE TITLE
Grammar Error/Awkward Syntax for Steps to SSH Into Pi

### ISSUE THREAD

**Issue by JLKwong** [treehouses/treehouses.github.io#809]
### Problem
The instructions to ssh into the Raspberry Pi in Step 7 were grammatically incorrect or had awkward syntax that made it confusing to follow:

> Open up your terminal or command prompt, and run `ssh root@[IP address]` to enter the root of your Pi or, to log into the Pi user use `ssh pi@[local IP address]` and to log into root, you can run `sudo -s`.

 ### Steps to reproduce the problem
N/A

 ### Screenshots
![image](https://user-images.githubusercontent.com/61807745/105942687-94faaa00-6014-11eb-92af-baaf350529a8.png)

 ### Proposed solution
Revise the text to read:

> Use one of the following ways to enter the root of your Pi:
> 
> 1. Open up your terminal or command prompt, and run `ssh root@[IP address]`.
> 2. First log into the Pi user by using `ssh pi@[local IP address]`, then log into the root by running `sudo -s`.

**Comment by rjpadilla** [comment]
I believe option 2 is the best choice. I have trouble logging in with root, but works fine if I use pi instead.

**Comment by JLKwong** [comment]
I know this has already been approved, but is it bad practice to revise this issue with a reminder for your solution to the root login issue? Or should I just do the pull request and let that be a separate issue altogether?

Update: I'll just work on this as is since it's been approved, and we'll cross the bridge for adding a reminder when we get there. xD

> So I figured out why I couldn't SSH as root to my pi on treehouses/treehouses.github.io#809 :
> 
> I didn't add my SSH key to my pi.
> Glossed over the known_host fix when switching images on my pi.
![image](https://user-images.githubusercontent.com/61807745/106227954-25fd8c80-619f-11eb-8cc7-75ff62bc0300.png)

**Comment by JLKwong** [comment]
Per #760, I revised this pull request to add the following text:
> Find the Raspberry Pi's IP address in your network settings (it will probably be 192.168.2.1). Open up your terminal or command prompt, and use one of the following ways to enter the root of your Pi:
> * run ssh root@[IP address] to enter the root of your Pi using the password (root password).
> * First log into the Pi user by using ssh pi@[local IP address] using the (default) password "raspberry", then log into the root by running sudo -s.
