### ISSUE TITLE
Host key verification failed error

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#83]
This is error is prompted during the ssh login attempt after the RSP4 booted with a new tree houses image. I was using PC as ssh client. 

User won't be able to login to the RP4. The following command will fail to execute
`ssh -v pi@192.168.2.1`

**Comment by Liew211** [comment]
@phamduchongan93 what is the full output of the failed login?

**Comment by Liew211** [comment]
@phamduchongan93 with a new treehouses image, you should see something like `Add correct host key in /Users/user/.ssh/known_hosts to get rid of this message.`

**Comment by Liew211** [comment]
if that's the case run `rm /Users/user/.ssh/known_hosts` to remove the file, then try ssh again

**Comment by phamduchongan93** [comment]
I removed the whole .ssh as a lazy fix :)

**Comment by Liew211** [comment]
You'll have to do this every time you ssh into your pi on a different image, just keep in mind 👍 

You can make a fix by writing a note on this.

**Comment by phamduchongan93** [comment]
A note, so you want me to edit a mark down file for this?

**Comment by Liew211** [comment]
Yes, you can add it as a question in FAQ and/or add it as a note in the step to SSH into the Pi.

**Comment by dogi** [comment]
by the way @phamduchongan93 `ssh -o "StrictHostKeyChecking=no" user@host` can also work

**Comment by phamduchongan93** [comment]
@dogi thanks. should we add at to the techinical faq.

**Comment by dogi** [comment]
@phamduchongan93 yes ;)
