### ISSUE TITLE
Step 1 link under virtual interns doesn't redirect 

### ISSUE THREAD

**Issue by manav113** [treehouses/treehouses.github.io#830]
### Problem
The __Step 1 - Installing and Finding Your Raspberry Pi__ link found below the Virtual Interns dropdown doesn't get redirected to the anchor it is supposed to.

 ### Steps to reproduce the problem
1. Go to any step except Step-1 from the virtual interns' steps list.
2. Clicking the Step 1 link now from the drop down redirects to the start/beginning of the First Steps page or doesn't redirect depending on the steps.

 ### Screenshots
![Screenshot from 2021-03-24 17-49-12](https://user-images.githubusercontent.com/57234825/112309488-683bd980-8cc9-11eb-9014-68dae95c46c5.png)
![Screenshot from 2021-03-24 17-49-18](https://user-images.githubusercontent.com/57234825/112309537-7558c880-8cc9-11eb-9218-0dcaea9cbe73.png)

 ### Proposed solution
N/A

**Comment by RCW2000** [comment]
there was an error in the link 
this works:
(https://treehouses.io/#!./pages/vi/firststeps.md#Step_1_-_Installing_and_Finding_Your_Raspberry_Pi)
this (the current link doesn't):
(https://treehouses.io/#!pages/vi/firststeps.md#Step_1_-_Installing_and_finding_your_Raspberry_Pi)
the f in finding and y in your need to be capitalized
