### ISSUE TITLE
resize avatar image in pages/vi/team.md

### ISSUE THREAD

**Issue by RCW2000** [treehouses/treehouses.github.io#840]
### Problem
saura8h's avatar is significantly bigger than the others skewing cell size

 ### Steps to reproduce the problem
open [team.md](https://treehouses.io/#!pages/vi/team.md)

 ### Screenshots
![overisized avi](https://user-images.githubusercontent.com/70165226/153254686-9c89217a-6f91-4a53-a41c-f75ae52f10f6.PNG)

 ### Proposed solution
After testing I think the solution is to switch to html syntax for this specific row in the table

**Comment by dogi** [comment]
the issue is a good one
but the solution is simpler
please no switch to html

**Comment by RCW2000** [comment]
what do you suggest?
