### ISSUE TITLE
missing image and missing github link on retiredinterns.md

### ISSUE THREAD

**Issue by RCW2000** [treehouses/treehouses.github.io#843]
### Problem
There is no picture nor github link for Chiragawale

 ### Steps to reproduce the problem
go to (https://treehouses.io/#!./pages/vi/retiredinterns.md)

 ### Screenshots

![missinglink](https://user-images.githubusercontent.com/70165226/153458172-026d1d5c-defd-40d8-9b7d-f4ca1f1171f4.PNG)

 ### Proposed solution
update retiredinterns.md by adding the tree house image and linking it to the user's github

**Comment by dogi** [comment]
@RCW2000 sure ;)

there is even more there which can be fixed
-> maybe in an other issue/PR
