### ISSUE TITLE
cannot access alpha images

### ISSUE THREAD

**Issue by RCW2000** [treehouses/treehouses.github.io#849]
### Problem
When clicked alpha images and beta image links redirect to site (dev.ole.org) which is unable to be reached

 ### Steps to reproduce the problem
1. go to download (https://treehouses.io/#!pages/download.md)
2. click on alpha images or beta image
 ### Screenshots
![dwn](https://user-images.githubusercontent.com/70165226/154822409-7d1e621c-e805-4163-a4a8-f3797d3dbe45.PNG)
![oleunrespon](https://user-images.githubusercontent.com/70165226/154822412-e3e1cbc6-da22-4a69-a0c5-b08dbf3bf523.PNG)

 ### Proposed solution
N/A

**Comment by dogi** [comment]
```
root@dev:~# last
root     pts/0        obw-wifi-vip.cic Mon Feb 21 09:42   still logged in   
reboot   system boot  3.18.11-hyprioto Thu Feb 17 22:17 - 09:43 (3+11:26)
```

dev.ole.org is treehouses oldest raspberry pi server (6 years)
4 days down good catch @RCW2000
it was on a roll nearly 2 years running strait ...

![image](https://user-images.githubusercontent.com/13684059/154930725-76836b44-c3d0-4ee7-a37a-08a009a099d8.png)

... hanging like this in my office

```
root@dev:~# uname -a
Linux dev 3.18.11-hypriotos-v7+ #2 SMP PREEMPT Sun Apr 12 16:34:20 UTC 2015 armv7l GNU/Linux
```

**Comment by dogi** [comment]
forgot ... system needed a new usb power plug ... this one lasted for 3 years
