### ISSUE TITLE
Possible content add for git checkout

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#94]
[https://treehouses.io/#!./pages/vi/github-issues.md](https://treehouses.io/#!./pages/vi/github-issues.md.)  Looking at **create a new branch** section. The instruction is clear as glass.

But, as a person who works on two or more PRs before the approval of the merging, I always forget to switch back to master branch before creating a new branch.
I suggest that we add the `git checkout -b <new_branch_for_PR> master ` command in the tutorial. It will prevent us from branching from a current working branch. Then, we can freely switch branches by `git checkout <branche_name>` and work on our commit.

**Comment by dogi** [comment]
@phamduchongan93 not sure about this one

@treehouses/treehouses-io wonder what is your perspective ...
