### ISSUE TITLE
Picture missing to demo tor + nextcloud + docker 

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/treehouses.github.io#95]
Looking at [https://treehouses.io/#!pages/vi/nextcloud-tor.md](https://treehouses.io/#!pages/vi/nextcloud-tor.md) 
Picture links are missing.

**Comment by dogi** [comment]
looks like there are no pictures at all
fix and/or add pictures

**Comment by CalebProvost** [comment]
Any suggestions on what should be used for the photos?

**Comment by dogi** [comment]
@CalebProvost I am looking to you for that ;)

**Comment by phamduchongan93** [comment]
A screen shot of nextcloud used with onion address, which is ran on tor browser would be an expected result.

**Comment by CalebProvost** [comment]
Took me a bit. Ran into some conflicting container problems. But I got it. I'll add it and create a PR for it.
