### ISSUE TITLE
step1: add note to make sure latest image gets downloaded

### ISSUE THREAD

**Issue by dogi** [treehouses/treehouses.github.io#97]

**Comment by CalebProvost** [comment]
Do you mean photo image or binary image?

**Comment by dogi** [comment]
@CalebProvost I mean to look at the dates of the image
generally highest number is the best

**Comment by vmnet8** [comment]
Right now it says:
Scroll down to find the latest release, and download it to your computer.

I'd change it to:
Find the latest image  treehouse-<version>.img.gz, scroll down to find the latest one.

**Comment by dogi** [comment]
Find the latest image `treehouse-<number>.img.gz`, scroll down to find the latest one.

**Comment by dogi** [comment]
> Find the latest image `treehouse-<number>.img.gz`, scroll down to find the latest one.

@vmnet8 better but still not good enough ;)

**Comment by XavierElon** [comment]
Hi, I will work on this one since I actually downloaded the wrong image (expr one) instead of the 108 when I was first flashing my microSD card.
