### ISSUE TITLE
"NEED DIAGRAM HERE" in github-issues.md

### ISSUE THREAD

**Issue by xdmtk** [treehouses/treehouses.github.io#99]
Looks like the "Forking Workflow" diagram is missing in https://treehouses.io/#!./pages/vi/github-issues.md , with a placeholder "NEED DIAGRAM HERE".

Probably time to create the diagram and put it there.

**Comment by dogi** [comment]
@xdmtk do you have good idea for that diagram?

**Comment by XavierElon** [comment]
Looks like this issue has been fixed and can be removed

**Comment by CalebProvost** [comment]
Good catch @xavierh93.
This kind of error happens when an PR which is created to fix an issues, doesn't reference the issue its fixing.
